/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quad_payload_dynamics_cost_y_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {21, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {11, 1, 1};
static const casadi_int casadi_s5[3] = {24, 1, 1};

/* quad_payload_dynamics_cost_y_fun:(i0[21],i1[4],i2[0],i3[],i4[11])->(o0[24]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+0, *w01=w+3, *w02=w+6, *w03=w+9, *w04=w+13, w05, *w06=w+18, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, *w18=w+33, *w19=w+36;
  const casadi_real *cs;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w00);
  /* #1: output[0][0] = @0 */
  casadi_copy(w00, 3, res[0]);
  /* #2: @1 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 3, w01);
  /* #3: output[0][1] = @1 */
  if (res[0]) casadi_copy(w01, 3, res[0]+3);
  /* #4: @2 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w02);
  /* #5: output[0][2] = @2 */
  if (res[0]) casadi_copy(w02, 3, res[0]+6);
  /* #6: @3 = input[0][4] */
  casadi_copy(arg[0] ? arg[0]+13 : 0, 4, w03);
  /* #7: output[0][3] = @3 */
  if (res[0]) casadi_copy(w03, 4, res[0]+9);
  /* #8: @4 = input[1][0] */
  casadi_copy(arg[1], 4, w04);
  /* #9: output[0][4] = @4 */
  if (res[0]) casadi_copy(w04, 4, res[0]+13);
  /* #10: @4 = input[4][7] */
  casadi_copy(arg[4] ? arg[4]+7 : 0, 4, w04);
  /* #11: @5 = @4[0] */
  for (rr=(&w05), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #12: @6 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w06);
  /* #13: @7 = @6[0] */
  for (rr=(&w07), cs=w06+0; cs!=w06+1; cs+=1) *rr++ = *cs;
  /* #14: @8 = (@5*@7) */
  w08  = (w05*w07);
  /* #15: @9 = @4[1] */
  for (rr=(&w09), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #16: @10 = @6[1] */
  for (rr=(&w10), cs=w06+1; cs!=w06+2; cs+=1) *rr++ = *cs;
  /* #17: @11 = (@9*@10) */
  w11  = (w09*w10);
  /* #18: @8 = (@8+@11) */
  w08 += w11;
  /* #19: @11 = @4[2] */
  for (rr=(&w11), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #20: @12 = @6[2] */
  for (rr=(&w12), cs=w06+2; cs!=w06+3; cs+=1) *rr++ = *cs;
  /* #21: @13 = (@11*@12) */
  w13  = (w11*w12);
  /* #22: @8 = (@8+@13) */
  w08 += w13;
  /* #23: @13 = @4[3] */
  for (rr=(&w13), cs=w04+3; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #24: @14 = @6[3] */
  for (rr=(&w14), cs=w06+3; cs!=w06+4; cs+=1) *rr++ = *cs;
  /* #25: @15 = (@13*@14) */
  w15  = (w13*w14);
  /* #26: @8 = (@8+@15) */
  w08 += w15;
  /* #27: @15 = (@9*@7) */
  w15  = (w09*w07);
  /* #28: @16 = (@5*@10) */
  w16  = (w05*w10);
  /* #29: @15 = (@15-@16) */
  w15 -= w16;
  /* #30: @16 = (@11*@14) */
  w16  = (w11*w14);
  /* #31: @15 = (@15-@16) */
  w15 -= w16;
  /* #32: @16 = (@13*@12) */
  w16  = (w13*w12);
  /* #33: @15 = (@15+@16) */
  w15 += w16;
  /* #34: @16 = (@9*@14) */
  w16  = (w09*w14);
  /* #35: @17 = (@5*@12) */
  w17  = (w05*w12);
  /* #36: @16 = (@16-@17) */
  w16 -= w17;
  /* #37: @17 = (@11*@7) */
  w17  = (w11*w07);
  /* #38: @16 = (@16+@17) */
  w16 += w17;
  /* #39: @17 = (@13*@10) */
  w17  = (w13*w10);
  /* #40: @16 = (@16-@17) */
  w16 -= w17;
  /* #41: @9 = (@9*@12) */
  w09 *= w12;
  /* #42: @9 = (-@9) */
  w09 = (- w09 );
  /* #43: @5 = (@5*@14) */
  w05 *= w14;
  /* #44: @9 = (@9-@5) */
  w09 -= w05;
  /* #45: @11 = (@11*@10) */
  w11 *= w10;
  /* #46: @9 = (@9+@11) */
  w09 += w11;
  /* #47: @13 = (@13*@7) */
  w13 *= w07;
  /* #48: @9 = (@9+@13) */
  w09 += w13;
  /* #49: @4 = vertcat(@8, @15, @16, @9) */
  rr=w04;
  *rr++ = w08;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w09;
  /* #50: @18 = @4[1:4] */
  for (rr=w18, cs=w04+1; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #51: @18 = (2.*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #52: output[0][5] = @18 */
  if (res[0]) casadi_copy(w18, 3, res[0]+17);
  /* #53: @8 = input[0][5] */
  w08 = arg[0] ? arg[0][17] : 0;
  /* #54: @15 = input[0][6] */
  w15 = arg[0] ? arg[0][18] : 0;
  /* #55: @16 = input[0][7] */
  w16 = arg[0] ? arg[0][19] : 0;
  /* #56: @9 = input[0][8] */
  w09 = arg[0] ? arg[0][20] : 0;
  /* #57: @19 = vertcat(@0, @6, @1, @2, @3, @8, @15, @16, @9) */
  rr=w19;
  for (i=0, cs=w00; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w06; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w03; i<4; ++i) *rr++ = *cs++;
  *rr++ = w08;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w09;
  /* #58: @6 = @19[17:21] */
  for (rr=w06, cs=w19+17; cs!=w19+21; cs+=1) *rr++ = *cs;
  /* #59: output[0][6] = @6 */
  if (res[0]) casadi_copy(w06, 4, res[0]+20);
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_payload_dynamics_cost_y_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quad_payload_dynamics_cost_y_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_payload_dynamics_cost_y_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_payload_dynamics_cost_y_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quad_payload_dynamics_cost_y_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_payload_dynamics_cost_y_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quad_payload_dynamics_cost_y_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quad_payload_dynamics_cost_y_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quad_payload_dynamics_cost_y_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int quad_payload_dynamics_cost_y_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quad_payload_dynamics_cost_y_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_payload_dynamics_cost_y_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_payload_dynamics_cost_y_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_payload_dynamics_cost_y_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_payload_dynamics_cost_y_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quad_payload_dynamics_cost_y_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 57;
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_payload_dynamics_cost_y_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 57*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
