/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quad_payload_dynamics_cost_y_e_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[20] = 
  {0, 1, 2, 3, 4, 5, 6, 7,
  8, 9, 10, 11, 12, 13, 17, 21,
  25, 26, 27, 28};
static const casadi_int casadi_s1[3] = {21, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {11, 1, 1};
static const casadi_int casadi_s5[3] = {20, 1, 1};
static const casadi_int casadi_s6[52] = 
  {21, 20, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  17, 21, 25, 26, 27, 28, 29, 0,
  1, 2, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 3, 4, 5, 6,
  3, 4, 5, 6, 3, 4, 5, 6,
  17, 18, 19, 20};
static const casadi_int casadi_s7[3] = {20, 0, 1};

/* quad_payload_dynamics_cost_y_e_fun_jac_ut_xt:(i0[21],i1[0],i2[0],i3[],i4[11])->(o0[20],o1[21x20,29nz],o2[20x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+0, *w01=w+3, *w02=w+6, *w03=w+9, *w04=w+13, w05, *w06=w+18, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, *w18=w+33, *w19=w+36, *w20=w+57, *w21=w+86, *w22=w+104;
  const casadi_int *cii;
  const casadi_real *cs;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w00);
  /* #1: output[0][0] = @0 */
  casadi_copy(w00, 3, res[0]);
  /* #2: @1 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 3, w01);
  /* #3: output[0][1] = @1 */
  if (res[0]) casadi_copy(w01, 3, res[0]+3);
  /* #4: @2 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w02);
  /* #5: output[0][2] = @2 */
  if (res[0]) casadi_copy(w02, 3, res[0]+6);
  /* #6: @3 = input[0][4] */
  casadi_copy(arg[0] ? arg[0]+13 : 0, 4, w03);
  /* #7: output[0][3] = @3 */
  if (res[0]) casadi_copy(w03, 4, res[0]+9);
  /* #8: @4 = input[4][7] */
  casadi_copy(arg[4] ? arg[4]+7 : 0, 4, w04);
  /* #9: @5 = @4[0] */
  for (rr=(&w05), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #10: @6 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w06);
  /* #11: @7 = @6[0] */
  for (rr=(&w07), cs=w06+0; cs!=w06+1; cs+=1) *rr++ = *cs;
  /* #12: @8 = (@5*@7) */
  w08  = (w05*w07);
  /* #13: @9 = @4[1] */
  for (rr=(&w09), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #14: @10 = @6[1] */
  for (rr=(&w10), cs=w06+1; cs!=w06+2; cs+=1) *rr++ = *cs;
  /* #15: @11 = (@9*@10) */
  w11  = (w09*w10);
  /* #16: @8 = (@8+@11) */
  w08 += w11;
  /* #17: @11 = @4[2] */
  for (rr=(&w11), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #18: @12 = @6[2] */
  for (rr=(&w12), cs=w06+2; cs!=w06+3; cs+=1) *rr++ = *cs;
  /* #19: @13 = (@11*@12) */
  w13  = (w11*w12);
  /* #20: @8 = (@8+@13) */
  w08 += w13;
  /* #21: @13 = @4[3] */
  for (rr=(&w13), cs=w04+3; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #22: @14 = @6[3] */
  for (rr=(&w14), cs=w06+3; cs!=w06+4; cs+=1) *rr++ = *cs;
  /* #23: @15 = (@13*@14) */
  w15  = (w13*w14);
  /* #24: @8 = (@8+@15) */
  w08 += w15;
  /* #25: @15 = (@9*@7) */
  w15  = (w09*w07);
  /* #26: @16 = (@5*@10) */
  w16  = (w05*w10);
  /* #27: @15 = (@15-@16) */
  w15 -= w16;
  /* #28: @16 = (@11*@14) */
  w16  = (w11*w14);
  /* #29: @15 = (@15-@16) */
  w15 -= w16;
  /* #30: @16 = (@13*@12) */
  w16  = (w13*w12);
  /* #31: @15 = (@15+@16) */
  w15 += w16;
  /* #32: @16 = (@9*@14) */
  w16  = (w09*w14);
  /* #33: @17 = (@5*@12) */
  w17  = (w05*w12);
  /* #34: @16 = (@16-@17) */
  w16 -= w17;
  /* #35: @17 = (@11*@7) */
  w17  = (w11*w07);
  /* #36: @16 = (@16+@17) */
  w16 += w17;
  /* #37: @17 = (@13*@10) */
  w17  = (w13*w10);
  /* #38: @16 = (@16-@17) */
  w16 -= w17;
  /* #39: @12 = (@9*@12) */
  w12  = (w09*w12);
  /* #40: @12 = (-@12) */
  w12 = (- w12 );
  /* #41: @14 = (@5*@14) */
  w14  = (w05*w14);
  /* #42: @12 = (@12-@14) */
  w12 -= w14;
  /* #43: @10 = (@11*@10) */
  w10  = (w11*w10);
  /* #44: @12 = (@12+@10) */
  w12 += w10;
  /* #45: @7 = (@13*@7) */
  w07  = (w13*w07);
  /* #46: @12 = (@12+@7) */
  w12 += w07;
  /* #47: @4 = vertcat(@8, @15, @16, @12) */
  rr=w04;
  *rr++ = w08;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w12;
  /* #48: @18 = @4[1:4] */
  for (rr=w18, cs=w04+1; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #49: @18 = (2.*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #50: output[0][4] = @18 */
  if (res[0]) casadi_copy(w18, 3, res[0]+13);
  /* #51: @8 = input[0][5] */
  w08 = arg[0] ? arg[0][17] : 0;
  /* #52: @15 = input[0][6] */
  w15 = arg[0] ? arg[0][18] : 0;
  /* #53: @16 = input[0][7] */
  w16 = arg[0] ? arg[0][19] : 0;
  /* #54: @12 = input[0][8] */
  w12 = arg[0] ? arg[0][20] : 0;
  /* #55: @19 = vertcat(@0, @6, @1, @2, @3, @8, @15, @16, @12) */
  rr=w19;
  for (i=0, cs=w00; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w06; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w03; i<4; ++i) *rr++ = *cs++;
  *rr++ = w08;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w12;
  /* #56: @6 = @19[17:21] */
  for (rr=w06, cs=w19+17; cs!=w19+21; cs+=1) *rr++ = *cs;
  /* #57: output[0][5] = @6 */
  if (res[0]) casadi_copy(w06, 4, res[0]+16);
  /* #58: @20 = zeros(21x20,29nz) */
  casadi_clear(w20, 29);
  /* #59: @21 = ones(21x1,18nz) */
  casadi_fill(w21, 18, 1.);
  /* #60: {@0, @8, @1, @2, @6, NULL, NULL, NULL, NULL} = vertsplit(@21) */
  casadi_copy(w21, 3, w00);
  w08 = w21[3];
  casadi_copy(w21+4, 3, w01);
  casadi_copy(w21+7, 3, w02);
  casadi_copy(w21+10, 4, w06);
  /* #61: @15 = @8[0] */
  for (rr=(&w15), cs=(&w08)+0; cs!=(&w08)+1; cs+=1) *rr++ = *cs;
  /* #62: @8 = (@5*@15) */
  w08  = (w05*w15);
  /* #63: @16 = (@9*@15) */
  w16  = (w09*w15);
  /* #64: @12 = (@11*@15) */
  w12  = (w11*w15);
  /* #65: @15 = (@13*@15) */
  w15  = (w13*w15);
  /* #66: @3 = vertcat(@8, @16, @12, @15) */
  rr=w03;
  *rr++ = w08;
  *rr++ = w16;
  *rr++ = w12;
  *rr++ = w15;
  /* #67: @18 = @3[1:4] */
  for (rr=w18, cs=w03+1; cs!=w03+4; cs+=1) *rr++ = *cs;
  /* #68: @18 = (2.*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #69: @3 = ones(4x1) */
  casadi_fill(w03, 4, 1.);
  /* #70: @22 = vertcat(@0, @1, @2, @6, @18, @3) */
  rr=w22;
  for (i=0, cs=w00; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w06; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w03; i<4; ++i) *rr++ = *cs++;
  /* #71: (@20[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 17, 21, 25, 26, 27, 28] = @22) */
  for (cii=casadi_s0, rr=w20, cs=w22; cii!=casadi_s0+20; ++cii, ++cs) rr[*cii] = *cs;
  /* #72: @8 = ones(21x1,1nz) */
  w08 = 1.;
  /* #73: {NULL, @16, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@8) */
  w16 = w08;
  /* #74: @8 = @16[0] */
  for (rr=(&w08), cs=(&w16)+0; cs!=(&w16)+1; cs+=1) *rr++ = *cs;
  /* #75: @16 = (@9*@8) */
  w16  = (w09*w08);
  /* #76: @12 = (@5*@8) */
  w12  = (w05*w08);
  /* #77: @12 = (-@12) */
  w12 = (- w12 );
  /* #78: @15 = (@13*@8) */
  w15  = (w13*w08);
  /* #79: @15 = (-@15) */
  w15 = (- w15 );
  /* #80: @8 = (@11*@8) */
  w08  = (w11*w08);
  /* #81: @6 = vertcat(@16, @12, @15, @8) */
  rr=w06;
  *rr++ = w16;
  *rr++ = w12;
  *rr++ = w15;
  *rr++ = w08;
  /* #82: @0 = @6[1:4] */
  for (rr=w00, cs=w06+1; cs!=w06+4; cs+=1) *rr++ = *cs;
  /* #83: @0 = (2.*@0) */
  for (i=0, rr=w00, cs=w00; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #84: (@20[14:26:4] = @0) */
  for (rr=w20+14, cs=w00; rr!=w20+26; rr+=4) *rr = *cs++;
  /* #85: @16 = ones(21x1,1nz) */
  w16 = 1.;
  /* #86: {NULL, @12, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@16) */
  w12 = w16;
  /* #87: @16 = @12[0] */
  for (rr=(&w16), cs=(&w12)+0; cs!=(&w12)+1; cs+=1) *rr++ = *cs;
  /* #88: @12 = (@11*@16) */
  w12  = (w11*w16);
  /* #89: @15 = (@13*@16) */
  w15  = (w13*w16);
  /* #90: @8 = (@5*@16) */
  w08  = (w05*w16);
  /* #91: @8 = (-@8) */
  w08 = (- w08 );
  /* #92: @16 = (@9*@16) */
  w16  = (w09*w16);
  /* #93: @16 = (-@16) */
  w16 = (- w16 );
  /* #94: @6 = vertcat(@12, @15, @8, @16) */
  rr=w06;
  *rr++ = w12;
  *rr++ = w15;
  *rr++ = w08;
  *rr++ = w16;
  /* #95: @0 = @6[1:4] */
  for (rr=w00, cs=w06+1; cs!=w06+4; cs+=1) *rr++ = *cs;
  /* #96: @0 = (2.*@0) */
  for (i=0, rr=w00, cs=w00; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #97: (@20[15:27:4] = @0) */
  for (rr=w20+15, cs=w00; rr!=w20+27; rr+=4) *rr = *cs++;
  /* #98: @12 = ones(21x1,1nz) */
  w12 = 1.;
  /* #99: {NULL, @15, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@12) */
  w15 = w12;
  /* #100: @12 = @15[0] */
  for (rr=(&w12), cs=(&w15)+0; cs!=(&w15)+1; cs+=1) *rr++ = *cs;
  /* #101: @13 = (@13*@12) */
  w13 *= w12;
  /* #102: @11 = (@11*@12) */
  w11 *= w12;
  /* #103: @11 = (-@11) */
  w11 = (- w11 );
  /* #104: @9 = (@9*@12) */
  w09 *= w12;
  /* #105: @5 = (@5*@12) */
  w05 *= w12;
  /* #106: @5 = (-@5) */
  w05 = (- w05 );
  /* #107: @6 = vertcat(@13, @11, @9, @5) */
  rr=w06;
  *rr++ = w13;
  *rr++ = w11;
  *rr++ = w09;
  *rr++ = w05;
  /* #108: @0 = @6[1:4] */
  for (rr=w00, cs=w06+1; cs!=w06+4; cs+=1) *rr++ = *cs;
  /* #109: @0 = (2.*@0) */
  for (i=0, rr=w00, cs=w00; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #110: (@20[16:28:4] = @0) */
  for (rr=w20+16, cs=w00; rr!=w20+28; rr+=4) *rr = *cs++;
  /* #111: output[1][0] = @20 */
  casadi_copy(w20, 29, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_payload_dynamics_cost_y_e_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quad_payload_dynamics_cost_y_e_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_payload_dynamics_cost_y_e_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_payload_dynamics_cost_y_e_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quad_payload_dynamics_cost_y_e_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_payload_dynamics_cost_y_e_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quad_payload_dynamics_cost_y_e_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void quad_payload_dynamics_cost_y_e_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quad_payload_dynamics_cost_y_e_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int quad_payload_dynamics_cost_y_e_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real quad_payload_dynamics_cost_y_e_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_payload_dynamics_cost_y_e_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_payload_dynamics_cost_y_e_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_payload_dynamics_cost_y_e_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_payload_dynamics_cost_y_e_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quad_payload_dynamics_cost_y_e_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 12;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 124;
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_payload_dynamics_cost_y_e_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 12*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 124*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
