/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) load_cable_3_cost_y_e_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[24] = 
  {0, 1, 2, 3, 4, 5, 6, 10,
  14, 18, 19, 20, 21, 22, 23, 24,
  25, 26, 27, 28, 29, 30, 31, 32};
static const casadi_int casadi_s1[3] = {55, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {4, 1, 1};
static const casadi_int casadi_s5[3] = {24, 1, 1};
static const casadi_int casadi_s6[60] = 
  {55, 24, 0, 1, 2, 3, 4, 5,
  6, 10, 14, 18, 19, 20, 21, 22,
  23, 24, 25, 26, 27, 28, 29, 30,
  31, 32, 33, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 6, 7, 8,
  9, 6, 7, 8, 9, 10, 11, 12,
  25, 39, 53, 16, 17, 18, 30, 31,
  32, 44, 45, 46};
static const casadi_int casadi_s7[3] = {24, 0, 1};

static const casadi_real casadi_zeros[55] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0.};

/* load_cable_3_cost_y_e_fun_jac_ut_xt:(i0[55],i1[0],i2[0],i3[],i4[4])->(o0[24],o1[55x24,33nz],o2[24x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w01=w+55, *w02=w+58, w03, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, *w15=w+74, *w16=w+107, *w17=w+110;
  const casadi_int *cii;
  const casadi_real *cs, *wr00, *wr01;
  /* #0: @0 = input[0][0] */
  wr00 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = @0[:3] */
  wr01 = wr00+0;
  /* #2: output[0][0] = @1 */
  casadi_copy(wr01, 3, res[0]);
  /* #3: @1 = @0[3:6] */
  wr01 = wr00+3;
  /* #4: output[0][1] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+3);
  /* #5: @2 = input[4][0] */
  casadi_copy(arg[4], 4, w02);
  /* #6: @3 = @2[0] */
  for (rr=(&w03), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #7: @4 = @0[6] */
  w04 = wr00[6];
  /* #8: @5 = (@3*@4) */
  w05  = (w03*w04);
  /* #9: @6 = @2[1] */
  for (rr=(&w06), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #10: @7 = @0[7] */
  w07 = wr00[7];
  /* #11: @8 = (@6*@7) */
  w08  = (w06*w07);
  /* #12: @5 = (@5+@8) */
  w05 += w08;
  /* #13: @8 = @2[2] */
  for (rr=(&w08), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #14: @9 = @0[8] */
  w09 = wr00[8];
  /* #15: @10 = (@8*@9) */
  w10  = (w08*w09);
  /* #16: @5 = (@5+@10) */
  w05 += w10;
  /* #17: @10 = @2[3] */
  for (rr=(&w10), cs=w02+3; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #18: @11 = @0[9] */
  w11 = wr00[9];
  /* #19: @12 = (@10*@11) */
  w12  = (w10*w11);
  /* #20: @5 = (@5+@12) */
  w05 += w12;
  /* #21: @12 = (@6*@4) */
  w12  = (w06*w04);
  /* #22: @13 = (@3*@7) */
  w13  = (w03*w07);
  /* #23: @12 = (@12-@13) */
  w12 -= w13;
  /* #24: @13 = (@8*@11) */
  w13  = (w08*w11);
  /* #25: @12 = (@12-@13) */
  w12 -= w13;
  /* #26: @13 = (@10*@9) */
  w13  = (w10*w09);
  /* #27: @12 = (@12+@13) */
  w12 += w13;
  /* #28: @13 = (@6*@11) */
  w13  = (w06*w11);
  /* #29: @14 = (@3*@9) */
  w14  = (w03*w09);
  /* #30: @13 = (@13-@14) */
  w13 -= w14;
  /* #31: @14 = (@8*@4) */
  w14  = (w08*w04);
  /* #32: @13 = (@13+@14) */
  w13 += w14;
  /* #33: @14 = (@10*@7) */
  w14  = (w10*w07);
  /* #34: @13 = (@13-@14) */
  w13 -= w14;
  /* #35: @9 = (@6*@9) */
  w09  = (w06*w09);
  /* #36: @9 = (-@9) */
  w09 = (- w09 );
  /* #37: @11 = (@3*@11) */
  w11  = (w03*w11);
  /* #38: @9 = (@9-@11) */
  w09 -= w11;
  /* #39: @7 = (@8*@7) */
  w07  = (w08*w07);
  /* #40: @9 = (@9+@7) */
  w09 += w07;
  /* #41: @4 = (@10*@4) */
  w04  = (w10*w04);
  /* #42: @9 = (@9+@4) */
  w09 += w04;
  /* #43: @2 = vertcat(@5, @12, @13, @9) */
  rr=w02;
  *rr++ = w05;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w09;
  /* #44: @1 = @2[1:4] */
  for (rr=w01, cs=w02+1; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #45: @1 = (2.*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #46: output[0][2] = @1 */
  if (res[0]) casadi_copy(w01, 3, res[0]+6);
  /* #47: @1 = @0[10:13] */
  wr01 = wr00+10;
  /* #48: output[0][3] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+9);
  /* #49: @5 = @0[25] */
  w05 = wr00[25];
  /* #50: output[0][4] = @5 */
  if (res[0]) res[0][12] = w05;
  /* #51: @5 = @0[39] */
  w05 = wr00[39];
  /* #52: output[0][5] = @5 */
  if (res[0]) res[0][13] = w05;
  /* #53: @5 = @0[53] */
  w05 = wr00[53];
  /* #54: output[0][6] = @5 */
  if (res[0]) res[0][14] = w05;
  /* #55: @1 = @0[16:19] */
  wr01 = wr00+16;
  /* #56: output[0][7] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+15);
  /* #57: @1 = @0[30:33] */
  wr01 = wr00+30;
  /* #58: output[0][8] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+18);
  /* #59: @1 = @0[44:47] */
  wr01 = wr00+44;
  /* #60: output[0][9] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+21);
  /* #61: @15 = zeros(55x24,33nz) */
  casadi_clear(w15, 33);
  /* #62: @1 = ones(3x1) */
  casadi_fill(w01, 3, 1.);
  /* #63: @2 = vertcat(@3, @6, @8, @10) */
  rr=w02;
  *rr++ = w03;
  *rr++ = w06;
  *rr++ = w08;
  *rr++ = w10;
  /* #64: @16 = @2[1:4] */
  for (rr=w16, cs=w02+1; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #65: @16 = (2.*@16) */
  for (i=0, rr=w16, cs=w16; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #66: @5 = 1 */
  w05 = 1.;
  /* #67: @17 = vertcat(@1, @1, @16, @1, @5, @5, @5, @1, @1, @1) */
  rr=w17;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  *rr++ = w05;
  *rr++ = w05;
  *rr++ = w05;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  /* #68: (@15[0, 1, 2, 3, 4, 5, 6, 10, 14, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32] = @17) */
  for (cii=casadi_s0, rr=w15, cs=w17; cii!=casadi_s0+24; ++cii, ++cs) rr[*cii] = *cs;
  /* #69: @3 = (-@3) */
  w03 = (- w03 );
  /* #70: @5 = (-@10) */
  w05 = (- w10 );
  /* #71: @2 = vertcat(@6, @3, @5, @8) */
  rr=w02;
  *rr++ = w06;
  *rr++ = w03;
  *rr++ = w05;
  *rr++ = w08;
  /* #72: @1 = @2[1:4] */
  for (rr=w01, cs=w02+1; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #73: @1 = (2.*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #74: (@15[7:19:4] = @1) */
  for (rr=w15+7, cs=w01; rr!=w15+19; rr+=4) *rr = *cs++;
  /* #75: @5 = (-@6) */
  w05 = (- w06 );
  /* #76: @2 = vertcat(@8, @10, @3, @5) */
  rr=w02;
  *rr++ = w08;
  *rr++ = w10;
  *rr++ = w03;
  *rr++ = w05;
  /* #77: @1 = @2[1:4] */
  for (rr=w01, cs=w02+1; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #78: @1 = (2.*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #79: (@15[8:20:4] = @1) */
  for (rr=w15+8, cs=w01; rr!=w15+20; rr+=4) *rr = *cs++;
  /* #80: @8 = (-@8) */
  w08 = (- w08 );
  /* #81: @2 = vertcat(@10, @8, @6, @3) */
  rr=w02;
  *rr++ = w10;
  *rr++ = w08;
  *rr++ = w06;
  *rr++ = w03;
  /* #82: @1 = @2[1:4] */
  for (rr=w01, cs=w02+1; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #83: @1 = (2.*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #84: (@15[9:21:4] = @1) */
  for (rr=w15+9, cs=w01; rr!=w15+21; rr+=4) *rr = *cs++;
  /* #85: output[1][0] = @15 */
  casadi_copy(w15, 33, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_3_cost_y_e_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int load_cable_3_cost_y_e_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_3_cost_y_e_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void load_cable_3_cost_y_e_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int load_cable_3_cost_y_e_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void load_cable_3_cost_y_e_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void load_cable_3_cost_y_e_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void load_cable_3_cost_y_e_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int load_cable_3_cost_y_e_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int load_cable_3_cost_y_e_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real load_cable_3_cost_y_e_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* load_cable_3_cost_y_e_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* load_cable_3_cost_y_e_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* load_cable_3_cost_y_e_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* load_cable_3_cost_y_e_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int load_cable_3_cost_y_e_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 134;
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_3_cost_y_e_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 134*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
