"""
fleet_viz.py
------------
Visualization-only node: turns mocap state into things RViz can draw, for the
drones AND the payload, WITHOUT any controller running.

Why this exists: the TF frames the drone meshes attach to (map -> drone_i_mocap)
used to be broadcast by each tracker's TrajectoryVisualizer. That meant nothing
appeared in RViz until the controllers were up, so you could not bring up RViz
first and confirm the fleet was present and publishing before committing to a
flight. This node owns those frames instead, so the viz stack stands alone.
(The tracker no longer broadcasts them — two publishers of the same frame just
produces TF_REPEATED_DATA warnings.)

Publishes:
    TF  map -> drone_i_mocap     one per drone, from /drone_i/motion_capture_state
    TF  map -> payload_mocap     from /payload/motion_capture_state
    /payload/marker              the payload ring + magnet plates (matches the world SDF)
    /payload/actual_path         where the payload has actually been
    /fleet/id_markers            floating text label (drone id) above each drone

Params:
    num_drones      (int)   fleet size
    payload_size    (float[3]) payload ring diameter dx,dy (radius = dx/2) and thickness
    path_max_len    (int)   ring-buffer length for the payload track
"""


import math
import rclpy
from rclpy.node import Node
from geometry_msgs.msg import TransformStamped, PoseStamped
from nav_msgs.msg import Path
from std_msgs.msg import String
from visualization_msgs.msg import Marker, MarkerArray
from geometry_msgs.msg import Point
from std_msgs.msg import ColorRGBA
from tf2_ros import TransformBroadcaster

from interfaces.msg import MotionCaptureState

FRAME = 'map'


# Ring payload geometry in the payload frame (m2a_ring_fixture.sdf as regenerated by
# generate_rigid_world.py): plate tops at z=0.025 (the attach plane), ring 30 mm thick
# below them, 60 mm wide.
RING_WIDTH = 0.06
RING_Z = 0.005
PLATE_RADIUS = 0.03
PLATE_THICK = 0.005
PLATE_Z = 0.0225


class FleetViz(Node):
    def __init__(self):
        super().__init__('fleet_viz')
        self.n = int(self.declare_parameter('num_drones', 3).value)
        self.payload_size = [float(v) for v in self.declare_parameter(
            'payload_size', [0.5, 0.5, 0.05]).value]
        # The track is thinned to one point per path_dt (10 Hz) so a whole flight fits:
        # 12000 points is 20 min. Cleared on ARM so each flight starts a fresh track.
        self.path_max_len = int(self.declare_parameter('path_max_len', 12000).value)
        self.path_dt = float(self.declare_parameter('path_dt', 0.10).value)
        self._path_last_t = None

        # TF + marker rate ceiling (Hz), 0 = once per mocap message (300-500 Hz in sim,
        # which is CPU spent drawing frames nobody can see).
        self.viz_hz = float(self.declare_parameter('viz_hz', 0.0).value)
        self._viz_min_dt = (1.0 / self.viz_hz) if self.viz_hz > 0 else 0.0
        self._viz_last = {}
        self.id_label_z = float(self.declare_parameter('id_label_z', 0.15).value)
        self.id_label_size = float(self.declare_parameter('id_label_size', 0.15).value)

        self.tf = TransformBroadcaster(self)
        self.marker_pub = self.create_publisher(Marker, '/payload/marker', 1)
        self.id_pub = self.create_publisher(MarkerArray, '/fleet/id_markers', 1)
        self.path_pub = self.create_publisher(Path, '/payload/actual_path', 5)
        self._payload_path = []
        self.create_subscription(String, '/fleet/command', self._command_cb, 5)

        for i in range(self.n):
            self.create_subscription(
                MotionCaptureState, f'/drone_{i}/motion_capture_state',
                lambda m, k=i: self._drone_cb(m, k), 5)
        self.create_subscription(
            MotionCaptureState, '/payload/motion_capture_state',
            self._payload_cb, 5)

        self.get_logger().info(
            f'fleet_viz up: broadcasting TF for {self.n} drones + payload, '
            f'payload box {self.payload_size}')

    def _send_tf(self, msg, child):
        t = TransformStamped()
        t.header.stamp = self.get_clock().now().to_msg()
        t.header.frame_id = FRAME
        t.child_frame_id = child
        p, o = msg.pose.position, msg.pose.orientation
        t.transform.translation.x = float(p.x)
        t.transform.translation.y = float(p.y)
        t.transform.translation.z = float(p.z)
        t.transform.rotation.w = float(o.w)
        t.transform.rotation.x = float(o.x)
        t.transform.rotation.y = float(o.y)
        t.transform.rotation.z = float(o.z)
        self.tf.sendTransform(t)

    def _viz_due(self, key):
        if not self._viz_min_dt:
            return True
        now = self.get_clock().now().nanoseconds * 1e-9
        last = self._viz_last.get(key)
        if last is not None and 0.0 <= now - last < self._viz_min_dt:
            return False
        self._viz_last[key] = now
        return True

    def _drone_cb(self, msg, i):
        if not self._viz_due(i):
            return
        self._send_tf(msg, f'drone_{i}_mocap')

        # floating text label with the drone id, anchored to the drone frame so it
        # follows the live pose (published each tick so it stays alive in RViz).
        m = Marker()
        m.header.frame_id = f'drone_{i}_mocap'
        m.header.stamp = self.get_clock().now().to_msg()
        m.ns = 'drone_id'
        m.id = i
        m.type = Marker.TEXT_VIEW_FACING
        m.action = Marker.ADD
        m.text = str(i + 1)             # drones are numbered 1-4 on the rig
        m.pose.position.z = self.id_label_z
        m.pose.orientation.w = 1.0
        m.scale.z = self.id_label_size
        m.color.r, m.color.g, m.color.b, m.color.a = 1.0, 1.0, 1.0, 1.0
        self.id_pub.publish(MarkerArray(markers=[m]))

    def _command_cb(self, msg):
        if msg.data.strip().upper() == 'ARM':
            self._payload_path = []
            self._path_last_t = None

    def _payload_cb(self, msg):
        if not self._viz_due('payload'):
            return
        self._send_tf(msg, 'payload_mocap')
        # ring marker, anchored to the payload frame so it moves with it: the 500 mm ring
        # as a thick line strip and its 12 magnet plates (plate 0 orange, on +x), the same
        # geometry as the world SDF (generate_rigid_world.payload_geometry_block)
        stamp = self.get_clock().now().to_msg()
        r = self.payload_size[0] / 2.0
        ring = Marker()
        ring.header.frame_id = 'payload_mocap'
        ring.header.stamp = stamp
        ring.ns = 'payload'
        ring.id = 0
        ring.type = Marker.LINE_STRIP
        ring.action = Marker.ADD
        ring.pose.orientation.w = 1.0
        ring.scale.x = RING_WIDTH
        ring.color.r, ring.color.g, ring.color.b, ring.color.a = 0.25, 0.25, 0.25, 0.95
        for k in range(49):
            th = 2.0 * math.pi * k / 48
            ring.points.append(Point(x=r * math.cos(th), y=r * math.sin(th), z=RING_Z))
        self.marker_pub.publish(ring)
        plates = Marker()
        plates.header = ring.header
        plates.ns = 'payload'
        plates.id = 1
        plates.type = Marker.CUBE_LIST
        plates.action = Marker.ADD
        plates.pose.orientation.w = 1.0
        plates.scale.x = plates.scale.y = 2.0 * PLATE_RADIUS
        plates.scale.z = PLATE_THICK
        for k in range(12):
            th = 2.0 * math.pi * k / 12
            plates.points.append(Point(x=r * math.cos(th), y=r * math.sin(th), z=PLATE_Z))
            c = ColorRGBA(r=1.0, g=0.35, b=0.15, a=1.0) if k == 0 else ColorRGBA(r=0.8, g=0.8, b=0.82, a=1.0)
            plates.colors.append(c)
        self.marker_pub.publish(plates)
        # plate numbers, 0 on +x then clockwise like a clock (geometry.plate_of_azimuth)
        nums = MarkerArray()
        for k in range(12):
            th = -2.0 * math.pi * k / 12
            t = Marker()
            t.header = ring.header
            t.ns = 'plate_number'
            t.id = k
            t.type = Marker.TEXT_VIEW_FACING
            t.action = Marker.ADD
            t.pose.position = Point(x=1.25 * r * math.cos(th), y=1.25 * r * math.sin(th), z=PLATE_Z)
            t.pose.orientation.w = 1.0
            t.scale.z = 0.05
            t.color.r = t.color.g = t.color.b = t.color.a = 1.0
            t.text = str(k)
            nums.markers.append(t)
        self.id_pub.publish(nums)
        m = ring

        # actual track, thinned to one point per path_dt
        now = self.get_clock().now().nanoseconds * 1e-9
        if self._path_last_t is not None and now - self._path_last_t < self.path_dt:
            return
        self._path_last_t = now
        ps = PoseStamped()
        ps.header.frame_id = FRAME
        ps.header.stamp = m.header.stamp
        ps.pose = msg.pose
        self._payload_path.append(ps)
        if len(self._payload_path) > self.path_max_len:
            self._payload_path = self._payload_path[-self.path_max_len:]
        path = Path()
        path.header.frame_id = FRAME
        path.header.stamp = m.header.stamp
        path.poses = self._payload_path
        self.path_pub.publish(path)


def main(args=None):
    rclpy.init(args=args)
    node = FleetViz()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        try:
            node.destroy_node()
        except Exception:
            pass
        try:
            rclpy.shutdown()
        except Exception:
            pass


if __name__ == '__main__':
    main()
