"""
dissipative_launch.py
----------------------
DECENTRALIZED DISSIPATIVE stack for the cable-suspended payload -- the detach-capable
counterpart of mpc_quad_load_launch.py. Identical wiring (per-drone cable-aware MPC
tracker + central fleet manager). Takeoff reuses the proven OCP planner unchanged, then at
the first /fleet/detach it hands over to the dissipative spring-damper network
(controller_dissipative `dissipative`, an OCP-takeoff subclass of LoadPlanner) which holds
the load and re-settles the reduced fleet. The trackers are UNCHANGED: same reference wire
format.

The point of this stack: a drone can detach mid-flight (4->3, then 3->2) and the
remaining fleet re-settles with the load still suspended -- no solver switch, no
hand-designed redistribution transient.

Run Gazebo with a DETACHABLE ground world (regenerated by generate_rigid_world.py
--detachable), then RViz, then this:
    gz sim simulation_assets/four_rigid_ground.sdf -v 4 -r
    ros2 launch controller_quad_load rviz_quad_load_launch.py  num_drones:=4   # FIRST
    ros2 launch controller_quad_load dissipative_launch.py     num_drones:=4

Fleet control (same as the MPC stack):
    ros2 topic pub -t 3 /fleet/command std_msgs/msg/String "{data: ARM}"
    ros2 topic pub -t 3 /fleet/command std_msgs/msg/String "{data: TAKEOFF}"
Then, mid-hover, detach a drone (physical id):
    ros2 topic pub -t 3 /fleet/detach std_msgs/msg/Int32 "{data: 1}"
    ros2 topic pub -t 3 /fleet/command std_msgs/msg/String "{data: LAND}"

RUN ORDER: rviz_quad_load_launch.py owns the clock/pose bridges, mocap emulators and
fleet_viz -- bring it up first, then this. This launch adds only the trackers, the
fleet manager, the dissipative node, and the per-drone /drone_k/detach bridges.
"""

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, OpaqueFunction
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node, SetParameter
from launch_ros.parameter_descriptions import ParameterValue

PARENT_MODEL = 'lift_system'


def _args():
    return [
        DeclareLaunchArgument('num_drones', default_value='4'),
        DeclareLaunchArgument('cable_len', default_value='0.5'),
        DeclareLaunchArgument('start_taut', default_value='false'),
        DeclareLaunchArgument('handover_elev_deg', default_value='45.0'),
        DeclareLaunchArgument('handover_settle_s', default_value='2.0'),
        DeclareLaunchArgument('load_mass', default_value='0.4'),
        DeclareLaunchArgument('target_z', default_value='0.6'),
        DeclareLaunchArgument('lift_ramp_vel', default_value='0.12'),
        DeclareLaunchArgument('land_vel', default_value='0.20'),
        DeclareLaunchArgument('cable_ff_scale', default_value='1.0'),
        DeclareLaunchArgument('attitude_ff', default_value='true'),
        DeclareLaunchArgument('cable_source', default_value='model'),
        DeclareLaunchArgument('payload_rest_z', default_value='-0.1'),
        DeclareLaunchArgument('takeoff_spool_s', default_value='0.5'),
        DeclareLaunchArgument('thrust_ratio', default_value='45.0'),
        DeclareLaunchArgument('thrust_quad_c', default_value='203.0'),
        DeclareLaunchArgument('auto_slot_assign', default_value='true'),
        DeclareLaunchArgument('load_traj', default_value='hover'),
        DeclareLaunchArgument('traj_speed', default_value='0.6'),
        DeclareLaunchArgument('traj_distance', default_value='1.0'),
        DeclareLaunchArgument('traj_radius', default_value='0.5'),
        # dissipative network tuning (see DissipativeParams; defaults are the tuned
        # rigid-short values). Exposed so a different geometry can be retuned live.
        DeclareLaunchArgument('diss_k_pay', default_value='40.0'),
        DeclareLaunchArgument('diss_k_anchor', default_value='40.0'),
        DeclareLaunchArgument('diss_c', default_value='6.0'),
        DeclareLaunchArgument('diss_k_ring', default_value='20.0'),
        DeclareLaunchArgument('diss_k_slot', default_value='18.0'),
        DeclareLaunchArgument('diss_node_mass', default_value='0.5'),
        DeclareLaunchArgument('diss_substeps', default_value='10'),
        DeclareLaunchArgument('diss_elev_deg', default_value='45.0'),
        # floor the network descends the held load to on a network-phase LAND.
        DeclareLaunchArgument('net_land_z', default_value='0.06'),
    ]


def launch_setup(context, *args, **kwargs):
    n = int(LaunchConfiguration('num_drones').perform(context))
    if n < 1:
        raise RuntimeError(f'num_drones must be >= 1, got {n}')
    drone_names = [f'x3_drone{i}' for i in range(n)]

    f = lambda name: ParameterValue(LaunchConfiguration(name), value_type=float)
    b = lambda name: ParameterValue(LaunchConfiguration(name), value_type=bool)
    i_ = lambda name: ParameterValue(LaunchConfiguration(name), value_type=int)

    nodes = [SetParameter(name='use_sim_time', value=True)]

    for i, drone_name in enumerate(drone_names):
        nodes.append(Node(
            package='ros_gz_bridge', executable='parameter_bridge',
            name=f'motor_bridge_{i}',
            arguments=[f'/{drone_name}/gazebo/command/motor_speed'
                       f'@actuator_msgs/msg/Actuators]ignition.msgs.Actuators']))
        nodes.append(Node(
            package='ros_gz_bridge', executable='parameter_bridge',
            name=f'imu_bridge_{i}',
            arguments=[f'/{drone_name}/imu@sensor_msgs/msg/Imu[gz.msgs.IMU'],
            remappings=[(f'/{drone_name}/imu', f'/drone_{i}/imu')]))
        # DETACH trigger bridge: ROS std_msgs/Empty -> gz.msgs.Empty on the
        # DetachableJoint's detach_topic (/drone_i/detach in the --detachable world).
        # ']' = ROS-to-GZ only. If the installed bridge uses the 'ignition.msgs'
        # namespace (as the motor bridge above does), change gz.msgs.Empty to
        # ignition.msgs.Empty.
        nodes.append(Node(
            package='ros_gz_bridge', executable='parameter_bridge',
            name=f'detach_bridge_{i}',
            arguments=[f'/drone_{i}/detach@std_msgs/msg/Empty]gz.msgs.Empty']))
        nodes.append(Node(
            package='simulation_communication', executable='payload_betaflight_comm',
            name=f'bf_comm_{i}',
            parameters=[{'drone_id': i, 'drone_name': drone_name,
                         'parent_model': PARENT_MODEL}]))
        nodes.append(Node(
            package='controller_quad_load', executable='controller',
            name=f'controller_{i}',
            parameters=[{'drone_id': i,
                         'cable_ff_scale': f('cable_ff_scale'),
                         'attitude_ff': b('attitude_ff'),
                         'cable_source': LaunchConfiguration('cable_source'),
                         'payload_rest_z': f('payload_rest_z'),
                         'takeoff_spool_s': f('takeoff_spool_s'),
                         'thrust_ratio': f('thrust_ratio'),
                         'thrust_quad_c': f('thrust_quad_c')}],
            output='screen'))

    # ── Central fleet manager ──────────────────────────────────────────────
    nodes.append(Node(
        package='controller_quad_load', executable='main', name='central_controller',
        parameters=[{'num_drones': n}], output='screen'))

    # ── Decentralized dissipative reference generator ──────────────────────
    nodes.append(Node(
        package='controller_dissipative', executable='dissipative', name='dissipative_controller',
        parameters=[{'num_drones': n,
                     'cable_len': f('cable_len'),
                     'start_taut': b('start_taut'),
                     'load_mass': f('load_mass'),
                     'target_z': f('target_z'),
                     'lift_ramp_vel': f('lift_ramp_vel'),
                     'land_vel': f('land_vel'),
                     'handover_elev_deg': f('handover_elev_deg'),
                     'handover_settle_s': f('handover_settle_s'),
                     'auto_slot_assign': b('auto_slot_assign'),
                     'load_traj': LaunchConfiguration('load_traj'),
                     'traj_speed': f('traj_speed'),
                     'traj_distance': f('traj_distance'),
                     'traj_radius': f('traj_radius'),
                     'diss_k_pay': f('diss_k_pay'),
                     'diss_k_anchor': f('diss_k_anchor'),
                     'diss_c': f('diss_c'),
                     'diss_k_ring': f('diss_k_ring'),
                     'diss_k_slot': f('diss_k_slot'),
                     'diss_node_mass': f('diss_node_mass'),
                     'diss_substeps': i_('diss_substeps'),
                     'diss_elev_deg': f('diss_elev_deg'),
                     'net_land_z': f('net_land_z')}],
        output='screen'))

    return nodes


def generate_launch_description():
    return LaunchDescription(_args() + [OpaqueFunction(function=launch_setup)])
