"""
dissipative_launch.py
----------------------
DECENTRALIZED DISSIPATIVE stack for the cable-suspended payload -- the detach-capable
counterpart of mpc_quad_load_launch.py. Identical wiring (per-drone cable-aware MPC
tracker + central fleet manager). Takeoff reuses the proven OCP planner unchanged, then at
the first /fleet/detach it hands over to the dissipative spring-damper network
(controller_dissipative `dissipative`, an OCP-takeoff subclass of LoadPlanner) which holds
the load and re-settles the reduced fleet. The trackers are UNCHANGED: same reference wire
format.

The point of this stack: a drone can detach mid-flight (4->3, then 3->2) and the
remaining fleet re-settles with the load still suspended -- no solver switch, no
hand-designed redistribution transient.

Run Gazebo with a DETACHABLE ground world (regenerated by generate_rigid_world.py
--detachable), then RViz, then this:
    gz sim simulation_assets/four_rigid_ground.sdf -v 4 -r
    ros2 launch controller_quad_load rviz_quad_load_launch.py  num_drones:=4   # FIRST
    ros2 launch controller_quad_load dissipative_launch.py     num_drones:=4

Fleet control (same as the MPC stack):
    ros2 topic pub -t 3 /fleet/command std_msgs/msg/String "{data: ARM}"
    ros2 topic pub -t 3 /fleet/command std_msgs/msg/String "{data: TAKEOFF}"
Then, mid-hover, detach a drone (physical id):
    ros2 topic pub -t 3 /fleet/detach std_msgs/msg/Int32 "{data: 1}"
    ros2 topic pub -t 3 /fleet/command std_msgs/msg/String "{data: LAND}"

RUN ORDER: rviz_quad_load_launch.py owns the clock/pose bridges, mocap emulators and
fleet_viz -- bring it up first, then this. This launch adds only the trackers, the
fleet manager, the dissipative node, and the per-drone /drone_k/detach bridges.
"""

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, LogInfo, OpaqueFunction
from controller_quad_load.thrust_model import resolve_thrust_ratio
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node, SetParameter
from launch_ros.parameter_descriptions import ParameterValue

PARENT_MODEL = 'lift_system'


def _args():
    return [
        DeclareLaunchArgument('num_drones', default_value='4'),
        # sim Betaflight rate loop source for every bf_comm: 'imu' (the gyro on /drone_i/imu,
        # bridged below; default since 2026-09-28) or 'pose' (difference the gz poses)
        DeclareLaunchArgument('rate_source', default_value='imu'),
        # our Gazebo bridges + Betaflight nodes; false when another stack owns the sim
        DeclareLaunchArgument('sim_interface', default_value='true'),
        # our stack on top of Tejen's M2 (see launch_setup)
        DeclareLaunchArgument('partner_m2', default_value='false'),
        # partner_m2 only: 'all' | 'muxes' (before his fleet flies) | 'controllers' (at his
        # success hold; our trackers idle through his whole join otherwise, ~150 % CPU)
        DeclareLaunchArgument('partner_m2_part', default_value='all'),
        DeclareLaunchArgument('airborne_start', default_value='false'),
        DeclareLaunchArgument('cable_elev_deg', default_value='45.0'),
        DeclareLaunchArgument('attach_z', default_value='0.025'),
        DeclareLaunchArgument('cable_len', default_value='0.5'),
        # where the rim attachments are (deg, load frame, sized by num_drones); '' = even
        # ring. Clock face: 3 o'clock = 0, 12 = 90, 9 = 180, 6 = 270.
        DeclareLaunchArgument('attach_azimuths_deg', default_value=''),
        # true = SKIP THE CREEP PHASE: the planner hands straight to the coupled OCP
        # instead of arc-sweeping the rods up to handover_elev_deg. Takeoff is the
        # same LoadPlanner OCP in every launch, so this is the same skip-the-creep
        # decision mpc_quad_load_launch.py and dissipative_only_launch.py already
        # make. It defaulted FALSE here alone, which is why takeoff on this launch was
        # visibly slower than running the MPC by itself (Wesley, 2026-08-06) — the
        # extra time was the creep sweep, not the lift.
        DeclareLaunchArgument('start_taut', default_value='false'),
        DeclareLaunchArgument('handover_elev_deg', default_value='45.0'),
        DeclareLaunchArgument('handover_settle_s', default_value='1.0'),
        DeclareLaunchArgument('creep_vel', default_value='0.2'),   # m/s creep sweep rate before the handover
        DeclareLaunchArgument('load_mass', default_value='0.86'),
        DeclareLaunchArgument('drone_mass', default_value='0.64'),   # x3 model over all links
        DeclareLaunchArgument('target_z', default_value='0.6'),
        DeclareLaunchArgument('lift_ramp_vel', default_value='0.22'),
        DeclareLaunchArgument('z_ki', default_value='0.4'),      # planner height integral, 0 = off (card 2026-09-24_planner_offset)
        DeclareLaunchArgument('z_i_max', default_value='0.15'),
        DeclareLaunchArgument('z_taut_gate', default_value='0.99'),
        DeclareLaunchArgument('land_vel', default_value='0.20'),
        DeclareLaunchArgument('cable_ff_scale', default_value='1.0'),
        DeclareLaunchArgument('attitude_ff', default_value='true'),
        DeclareLaunchArgument('cable_source', default_value='model'),
        DeclareLaunchArgument('payload_rest_z', default_value='-0.1'),
        DeclareLaunchArgument('takeoff_spool_s', default_value='0.5'),
        # ── kT (thrust ratio) -- kept in step with mpc_quad_load_launch.py ──
        # See mpc_quad_load_launch.py for the full explanation of these four.
        DeclareLaunchArgument('thrust_ratio', default_value='auto'),
        # per-drone thrust-gain trim (kt_trim.py, card 2026-09-23_kt_trim.md): off until the matrix passes
        # tracker pose watchdog (wall clock); 0.25 is the node default and the rig value.
        # Headless sim runs under CPU load trip it before liftoff (R0493/R0511/R0551/R0555).
        DeclareLaunchArgument('pose_timeout_s', default_value='0.25'),
        # tracker reference-staleness gate (wall clock). 1.0 s = the rig; Gazebo runs at ~0.1
        # RTF (GUI) may pass 3.0 (Wesley 2026-09-26: planner slow ticks of 0.8 s tripped it)
        DeclareLaunchArgument('safety_ref_timeout_s', default_value='1.0'),
        DeclareLaunchArgument('kt_trim', default_value='true'),
        DeclareLaunchArgument('kt_trim_max', default_value='0.25'),
        DeclareLaunchArgument('kt_trim_tau', default_value='1.5'),
        DeclareLaunchArgument('takeoff_thrust_ratio', default_value='auto'),
        DeclareLaunchArgument('kt_batt_sag_frac', default_value='0.0'),
        DeclareLaunchArgument('kt_batt_v_full', default_value='25.2'),   # 6S 4.20 V/cell
        DeclareLaunchArgument('kt_batt_v_empty', default_value='21.0'),  # 6S 3.50 V/cell
        DeclareLaunchArgument('kt_print_period_s', default_value='1.0'),
        DeclareLaunchArgument('auto_slot_assign', default_value='true'),
        # measure each rod from mocap at handover instead of trusting cable_len (2026-09-23)
        DeclareLaunchArgument('measure_rod_len', default_value='true'),
        # Experiment T1 (finding F10): terminal cost tracks ref_vel instead
        # of commanding a stop at the end of the horizon. Default false =
        # historical behaviour, so this only changes a run you asked it to.
        DeclareLaunchArgument('terminal_vel_ref', default_value='false'),
        DeclareLaunchArgument('load_traj', default_value='hover'),
        DeclareLaunchArgument('traj_speed', default_value='0.6'),
        DeclareLaunchArgument('traj_distance', default_value='1.0'),
        DeclareLaunchArgument('traj_radius', default_value='0.5'),
        # dissipative network tuning (see DissipativeParams; defaults are the tuned
        # rigid-short values). Exposed so a different geometry can be retuned live.
        # Reference-shaping for the NETWORK phase (see dissipative_node).
        #   net_horizon_preview: carry the load trajectory's future displacement along
        #     the published horizon instead of repeating node 0. ON by default -- logged
        #     A/B: payload lag 3.11 s -> 1.11 s, mean error 0.172 -> 0.081 m.
        #   net_traj_lean: tilt the reference cone onto g_eff = g - a_traj so the
        #     formation leads the load into the maneuver (the OCP's flatness relation).
        #     OFF by default: unvalidated, mini_plant cannot reproduce the radius
        #     deficit it targets. Fly it as an A/B against the logs.
        DeclareLaunchArgument('net_horizon_preview', default_value='true'),
        DeclareLaunchArgument('net_traj_lean', default_value='false'),
        # ── How a fleet-size change is handled (THESIS_PLAN §12.2) ──────────
        # 'network' (default, verified): the dissipative network takes the fleet on a
        #     detach, redistributes, and carries the trajectory on itself.
        # 'ocp': the OCP is RESIZED in place to the new fleet size and keeps flying.
        #     The cables do not move when a drone leaves, so the survivors are just a
        #     smaller (uneven) ring the OCP can solve for directly.
        DeclareLaunchArgument('reconfig_mode', default_value='network'),
        DeclareLaunchArgument('reconfig_hold_s', default_value='1.5'),
        DeclareLaunchArgument('min_survivors', default_value='3'),   # 3 -> 2 capsizes in SIL; 2 only for a deliberate test
        DeclareLaunchArgument('diss_k_pay', default_value='40.0'),
        DeclareLaunchArgument('diss_k_anchor', default_value='40.0'),
        DeclareLaunchArgument('diss_c', default_value='6.0'),
        DeclareLaunchArgument('diss_k_ring', default_value='20.0'),
        DeclareLaunchArgument('diss_k_slot', default_value='18.0'),
        DeclareLaunchArgument('diss_node_mass', default_value='0.5'),
        DeclareLaunchArgument('diss_substeps', default_value='10'),
        DeclareLaunchArgument('diss_elev_deg', default_value='45.0'),
        # floor the network descends the held load to on a network-phase LAND.
        DeclareLaunchArgument('net_land_z', default_value='0.06'),
    ]


def launch_setup(context, *args, **kwargs):
    n = int(LaunchConfiguration('num_drones').perform(context))
    if n < 1:
        raise RuntimeError(f'num_drones must be >= 1, got {n}')
    drone_names = [f'x3_drone{i}' for i in range(n)]
    # kT is an operating point of the sim's quadratic motor model (thrust_model.py):
    # 'auto' derives it from load_mass and the fleet size, a number is used verbatim.
    kt, kt_to, kt_note = resolve_thrust_ratio(
        LaunchConfiguration('thrust_ratio').perform(context),
        LaunchConfiguration('takeoff_thrust_ratio').perform(context),
        LaunchConfiguration('load_mass').perform(context), n)

    f = lambda name: ParameterValue(LaunchConfiguration(name), value_type=float)
    b = lambda name: ParameterValue(LaunchConfiguration(name), value_type=bool)
    i_ = lambda name: ParameterValue(LaunchConfiguration(name), value_type=int)

    nodes = [SetParameter(name='use_sim_time', value=True),
             LogInfo(msg=f'[launch] {kt_note}; takeoff {kt_to:.2f}')]

    # partner_m2 (multi_drone_control 2026-09-26): our stack on top of Tejen's M2 world
    # after his four drones have joined the ring. His per-drone stacks own the /drone_i
    # command/arming names, so ours move under /ours; each drone gets an ELRS mux that
    # forwards his MPC (/drone_i/ELRSCommand_tejen) until /fleet/handover, then ours.
    sim_interface = LaunchConfiguration('sim_interface').perform(context).lower() in ('1', 'true', 'yes')
    partner_m2 = LaunchConfiguration('partner_m2').perform(context).lower() in ('1', 'true', 'yes')
    part = LaunchConfiguration('partner_m2_part').perform(context) if partner_m2 else 'all'
    want_muxes = part in ('all', 'muxes')
    want_ctrl = part in ('all', 'controllers')

    def ours(i):
        return [(f'/drone_{i}/arming_service', f'/ours/drone_{i}/arming_service'),
                (f'/drone_{i}/arming_state_feedback', f'/ours/drone_{i}/arming_state_feedback'),
                (f'/drone_{i}/command', f'/ours/drone_{i}/command'),
                (f'/drone_{i}/ELRSCommand', f'/drone_{i}/ELRSCommand_diss')] if partner_m2 else []

    for i, drone_name in enumerate(drone_names):
        if partner_m2 and want_muxes:
            nodes.append(Node(
                package='drone_magnet', executable='elrs_mux', name=f'elrs_mux_{i}',
                parameters=[{'drone_id': i, 'latch': True, 'approach_stream': True,
                             'handoff_topic': '/fleet/handover'}], output='screen'))
        if not want_ctrl:
            continue
        if not sim_interface:
            nodes.append(Node(
                package='controller_quad_load', executable='controller',
                name=f'controller_{i}', remappings=ours(i),
                parameters=[{'drone_id': i,
                             'terminal_vel_ref': b('terminal_vel_ref'),
                             'cable_ff_scale': f('cable_ff_scale'),
                             'attitude_ff': b('attitude_ff'),
                             'cable_source': LaunchConfiguration('cable_source'),
                             'payload_rest_z': f('payload_rest_z'),
                             'takeoff_spool_s': f('takeoff_spool_s'),
                             'pose_timeout_s': ParameterValue(LaunchConfiguration('pose_timeout_s'), value_type=float),
                             'safety_ref_timeout_s': f('safety_ref_timeout_s'),
                             'thrust_ratio': kt,
                             'kt_trim': ParameterValue(LaunchConfiguration('kt_trim'), value_type=bool),
                             'kt_trim_max': ParameterValue(LaunchConfiguration('kt_trim_max'), value_type=float),
                             'kt_trim_tau': ParameterValue(LaunchConfiguration('kt_trim_tau'), value_type=float),
                             'takeoff_thrust_ratio': kt_to,
                             'kt_batt_sag_frac': f('kt_batt_sag_frac'),
                             'kt_batt_v_full': f('kt_batt_v_full'),
                             'kt_batt_v_empty': f('kt_batt_v_empty'),
                             'kt_print_period_s': f('kt_print_period_s')}],
                output='screen'))
            continue
        nodes.append(Node(
            package='ros_gz_bridge', executable='parameter_bridge',
            name=f'motor_bridge_{i}',
            arguments=[f'/{drone_name}/gazebo/command/motor_speed'
                       f'@actuator_msgs/msg/Actuators]ignition.msgs.Actuators']))
        nodes.append(Node(
            package='ros_gz_bridge', executable='parameter_bridge',
            name=f'imu_bridge_{i}',
            arguments=[f'/{drone_name}/imu@sensor_msgs/msg/Imu[gz.msgs.IMU'],
            remappings=[(f'/{drone_name}/imu', f'/drone_{i}/imu')]))
        # DETACH trigger bridge: ROS std_msgs/Empty -> gz.msgs.Empty on the
        # DetachableJoint's detach_topic (/drone_i/detach in the --detachable world).
        # ']' = ROS-to-GZ only. If the installed bridge uses the 'ignition.msgs'
        # namespace (as the motor bridge above does), change gz.msgs.Empty to
        # ignition.msgs.Empty.
        nodes.append(Node(
            package='ros_gz_bridge', executable='parameter_bridge',
            name=f'detach_bridge_{i}',
            arguments=[f'/drone_{i}/detach@std_msgs/msg/Empty]gz.msgs.Empty']))
        nodes.append(Node(
            package='simulation_communication', executable='payload_betaflight_comm',
            name=f'bf_comm_{i}',
            parameters=[{'drone_id': i, 'drone_name': drone_name,
                         'parent_model': PARENT_MODEL,
                         'rate_source': LaunchConfiguration('rate_source'),
                         'imu_topic': f'/drone_{i}/imu'}]))
        nodes.append(Node(
            package='controller_quad_load', executable='controller',
            name=f'controller_{i}',
            parameters=[{'drone_id': i,
                         'terminal_vel_ref': b('terminal_vel_ref'),
                         'cable_ff_scale': f('cable_ff_scale'),
                         'attitude_ff': b('attitude_ff'),
                         'cable_source': LaunchConfiguration('cable_source'),
                         'payload_rest_z': f('payload_rest_z'),
                         'takeoff_spool_s': f('takeoff_spool_s'),
                         'pose_timeout_s': ParameterValue(LaunchConfiguration('pose_timeout_s'), value_type=float),
                             'safety_ref_timeout_s': f('safety_ref_timeout_s'),
                         'thrust_ratio': kt,
                         'kt_trim': ParameterValue(LaunchConfiguration('kt_trim'), value_type=bool),
                         'kt_trim_max': ParameterValue(LaunchConfiguration('kt_trim_max'), value_type=float),
                         'kt_trim_tau': ParameterValue(LaunchConfiguration('kt_trim_tau'), value_type=float),
                         'takeoff_thrust_ratio': kt_to,
                         'kt_batt_sag_frac': f('kt_batt_sag_frac'),
                         'kt_batt_v_full': f('kt_batt_v_full'),
                         'kt_batt_v_empty': f('kt_batt_v_empty'),
                         'kt_print_period_s': f('kt_print_period_s')}],
            output='screen'))

    if not want_ctrl:
        return nodes

    # ── Central fleet manager ──────────────────────────────────────────────
    if partner_m2:
        # his ring (M2A fixture, made dynamic) -> our payload mocap
        nodes.append(Node(
            package='simulation_communication', executable='tejen_motion_capture_emulator',
            name='payload_mocap', parameters=[{
                'pose_topic': '/model/payload_model/pose', 'target_object_id': 1,
                'motion_capture_state_topic': '/payload/motion_capture_state',
                'rviz_pose_topic': '/payload/rviz_pose'}], output='screen'))
    fleet_remaps = [r for i in range(n) for r in ours(i)]
    nodes.append(Node(
        package='controller_quad_load', executable='main', name='central_controller',
        remappings=fleet_remaps, parameters=[{'num_drones': n}], output='screen'))

    # ── Decentralized dissipative reference generator ──────────────────────
    nodes.append(Node(
        package='controller_dissipative', executable='dissipative', name='dissipative_controller',
        parameters=[{'num_drones': n,
                     'cable_len': f('cable_len'),
                     'attach_azimuths_deg': LaunchConfiguration('attach_azimuths_deg'),
                     'start_taut': b('start_taut'),
                     'load_mass': f('load_mass'),
                     'drone_mass': f('drone_mass'),
                     'target_z': f('target_z'),
                     'lift_ramp_vel': f('lift_ramp_vel'),
                     'z_ki': f('z_ki'),
                     'z_i_max': f('z_i_max'),
                     'z_taut_gate': f('z_taut_gate'),
                     'land_vel': f('land_vel'),
                     'handover_elev_deg': f('handover_elev_deg'),
                     'handover_settle_s': f('handover_settle_s'),
                     'creep_vel': f('creep_vel'),
                     'auto_slot_assign': b('auto_slot_assign'),
                     'measure_rod_len': b('measure_rod_len'),
                     'load_traj': LaunchConfiguration('load_traj'),
                     'traj_speed': f('traj_speed'),
                     'traj_distance': f('traj_distance'),
                     'traj_radius': f('traj_radius'),
                     'net_horizon_preview': b('net_horizon_preview'),
                     'net_traj_lean': b('net_traj_lean'),
                     'diss_k_pay': f('diss_k_pay'),
                     'diss_k_anchor': f('diss_k_anchor'),
                     'diss_c': f('diss_c'),
                     'diss_k_ring': f('diss_k_ring'),
                     'diss_k_slot': f('diss_k_slot'),
                     'diss_node_mass': f('diss_node_mass'),
                     'diss_substeps': i_('diss_substeps'),
                     'diss_elev_deg': f('diss_elev_deg'),
                     'reconfig_mode': LaunchConfiguration('reconfig_mode'),
                     'reconfig_hold_s': f('reconfig_hold_s'),
                     'min_survivors': i_('min_survivors'),
                     'net_land_z': f('net_land_z'),
                     'attach_z': f('attach_z'),
                     'airborne_start': b('airborne_start'),
                     'cable_elev_deg': f('cable_elev_deg')}],
        output='screen'))

    return nodes


def generate_launch_description():
    return LaunchDescription(_args() + [OpaqueFunction(function=launch_setup)])
