/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) load_cable_2_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

static const casadi_int casadi_s0[3] = {41, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {4, 1, 1};
static const casadi_int casadi_s4[3] = {2, 1, 1};

static const casadi_real casadi_c0[3] = {0., 0., -9.8100000000000005e+00};
static const casadi_real casadi_c1[9] = 
  {5.9880239520958082e+02, 0., 0., 0., 5.9880239520958082e+02, 0., 0., 0.,
  3.0030030030030031e+02};
static const casadi_real casadi_c2[3] = {8.0000000000000002e-02, 0., 2.5000000000000001e-02};
static const casadi_real casadi_c3[3] = {-8.0000000000000002e-02, 9.7971743931788255e-18, 2.5000000000000001e-02};
static const casadi_real casadi_c4[9] = 
  {1.6700000000000000e-03, 0., 0., 0., 1.6700000000000000e-03, 0., 0., 0.,
  3.3300000000000001e-03};

static const casadi_real casadi_zeros[41] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* load_cable_2_constr_h_fun:(i0[41],i1[8],i2[0],i3[4])->(o0[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+4, w03, *w04=w+49, *w05=w+52, w06, *w07=w+56, *w08=w+59, *w09=w+62, w10, *w11=w+66;
  casadi_real w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23;
  casadi_real w24, *w25=w+82, *w26=w+85, *w27=w+88, *w28=w+91, *w29=w+100, w31, w32, w33;
  const casadi_real *cr, *cs, *ct, *wr02, *wr04, *wr07, *wr28, *wr30;
  /* #0: @0 = 0.6 */
  w00 = 5.9999999999999998e-01;
  /* #1: @1 = [0, 0, -9.81] */
  casadi_copy(casadi_c0, 3, w01);
  /* #2: @2 = input[0][0] */
  wr02 = arg[0] ? arg[0] : casadi_zeros;
  /* #3: @3 = @2[25] */
  w03 = wr02[25];
  /* #4: @4 = @2[13:16] */
  wr04 = wr02+13;
  /* #5: @5 = (@3*@4) */
  for (i=0, rr=w05, cs=wr04; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #6: @6 = @2[39] */
  w06 = wr02[39];
  /* #7: @7 = @2[27:30] */
  wr07 = wr02+27;
  /* #8: @8 = (@6*@7) */
  for (i=0, rr=w08, cs=wr07; i<3; ++i) (*rr++)  = (w06*(*cs++));
  /* #9: @9 = (@5+@8) */
  for (i=0, rr=w09, cr=w05, cs=w08; i<3; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #10: @10 = 0.4 */
  w10 = 4.0000000000000002e-01;
  /* #11: @9 = (@9/@10) */
  for (i=0, rr=w09; i<3; ++i) (*rr++) /= w10;
  /* #12: @9 = (@1-@9) */
  for (i=0, rr=w09, cr=w01, cs=w09; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #13: @11 = zeros(3x1) */
  casadi_clear(w11, 3);
  /* #14: @10 = 1 */
  w10 = 1.;
  /* #15: @12 = @2[8] */
  w12 = wr02[8];
  /* #16: @13 = sq(@12) */
  w13 = casadi_sq( w12 );
  /* #17: @14 = @2[9] */
  w14 = wr02[9];
  /* #18: @15 = sq(@14) */
  w15 = casadi_sq( w14 );
  /* #19: @16 = (@13+@15) */
  w16  = (w13+w15);
  /* #20: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #21: @16 = (@10-@16) */
  w16  = (w10-w16);
  /* #22: @17 = @2[7] */
  w17 = wr02[7];
  /* #23: @18 = (@17*@12) */
  w18  = (w17*w12);
  /* #24: @19 = @2[6] */
  w19 = wr02[6];
  /* #25: @20 = (@19*@14) */
  w20  = (w19*w14);
  /* #26: @21 = (@18-@20) */
  w21  = (w18-w20);
  /* #27: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #28: @22 = (@17*@14) */
  w22  = (w17*w14);
  /* #29: @23 = (@19*@12) */
  w23  = (w19*w12);
  /* #30: @24 = (@22+@23) */
  w24  = (w22+w23);
  /* #31: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #32: @25 = horzcat(@16, @21, @24) */
  rr=w25;
  *rr++ = w16;
  *rr++ = w21;
  *rr++ = w24;
  /* #33: @25 = @25' */
  /* #34: @18 = (@18+@20) */
  w18 += w20;
  /* #35: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #36: @20 = sq(@17) */
  w20 = casadi_sq( w17 );
  /* #37: @15 = (@20+@15) */
  w15  = (w20+w15);
  /* #38: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #39: @15 = (@10-@15) */
  w15  = (w10-w15);
  /* #40: @12 = (@12*@14) */
  w12 *= w14;
  /* #41: @19 = (@19*@17) */
  w19 *= w17;
  /* #42: @17 = (@12-@19) */
  w17  = (w12-w19);
  /* #43: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #44: @26 = horzcat(@18, @15, @17) */
  rr=w26;
  *rr++ = w18;
  *rr++ = w15;
  *rr++ = w17;
  /* #45: @26 = @26' */
  /* #46: @22 = (@22-@23) */
  w22 -= w23;
  /* #47: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #48: @12 = (@12+@19) */
  w12 += w19;
  /* #49: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #50: @20 = (@20+@13) */
  w20 += w13;
  /* #51: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #52: @10 = (@10-@20) */
  w10 -= w20;
  /* #53: @27 = horzcat(@22, @12, @10) */
  rr=w27;
  *rr++ = w22;
  *rr++ = w12;
  *rr++ = w10;
  /* #54: @27 = @27' */
  /* #55: @28 = horzcat(@25, @26, @27) */
  rr=w28;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<3; ++i) *rr++ = *cs++;
  /* #56: @29 = @28' */
  for (i=0, rr=w29, cs=w28; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #57: @30 = 
  [[598.802, 0, 0], 
   [0, 598.802, 0], 
   [0, 0, 300.3]] */
  wr30 = casadi_c1;
  /* #58: @25 = mac(@28,@4,@11) */
  casadi_copy(w11, 3, w25);
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w28+j, ct=wr04+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #59: @22 = @25[1] */
  for (rr=(&w22), cs=w25+1; cs!=w25+2; cs+=1) *rr++ = *cs;
  /* #60: @4 = [0.08, 0, 0.025] */
  casadi_copy(casadi_c2, 3, w04);
  /* #61: @12 = @4[2] */
  for (rr=(&w12), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #62: @10 = (@22*@12) */
  w10  = (w22*w12);
  /* #63: @20 = @25[2] */
  for (rr=(&w20), cs=w25+2; cs!=w25+3; cs+=1) *rr++ = *cs;
  /* #64: @13 = @4[1] */
  for (rr=(&w13), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #65: @19 = (@20*@13) */
  w19  = (w20*w13);
  /* #66: @10 = (@10-@19) */
  w10 -= w19;
  /* #67: @19 = @4[0] */
  for (rr=(&w19), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #68: @20 = (@20*@19) */
  w20 *= w19;
  /* #69: @23 = @25[0] */
  for (rr=(&w23), cs=w25+0; cs!=w25+1; cs+=1) *rr++ = *cs;
  /* #70: @18 = (@23*@12) */
  w18  = (w23*w12);
  /* #71: @20 = (@20-@18) */
  w20 -= w18;
  /* #72: @23 = (@23*@13) */
  w23 *= w13;
  /* #73: @22 = (@22*@19) */
  w22 *= w19;
  /* #74: @23 = (@23-@22) */
  w23 -= w22;
  /* #75: @25 = vertcat(@10, @20, @23) */
  rr=w25;
  *rr++ = w10;
  *rr++ = w20;
  *rr++ = w23;
  /* #76: @25 = (@3*@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #77: @4 = mac(@28,@7,@11) */
  casadi_copy(w11, 3, w04);
  for (i=0, rr=w04; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w28+j, ct=wr07+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #78: @3 = @4[1] */
  for (rr=(&w03), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #79: @7 = [-0.08, 9.79717e-18, 0.025] */
  casadi_copy(casadi_c3, 3, w07);
  /* #80: @10 = @7[2] */
  for (rr=(&w10), cs=w07+2; cs!=w07+3; cs+=1) *rr++ = *cs;
  /* #81: @20 = (@3*@10) */
  w20  = (w03*w10);
  /* #82: @23 = @4[2] */
  for (rr=(&w23), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #83: @22 = @7[1] */
  for (rr=(&w22), cs=w07+1; cs!=w07+2; cs+=1) *rr++ = *cs;
  /* #84: @18 = (@23*@22) */
  w18  = (w23*w22);
  /* #85: @20 = (@20-@18) */
  w20 -= w18;
  /* #86: @18 = @7[0] */
  for (rr=(&w18), cs=w07+0; cs!=w07+1; cs+=1) *rr++ = *cs;
  /* #87: @23 = (@23*@18) */
  w23 *= w18;
  /* #88: @15 = @4[0] */
  for (rr=(&w15), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #89: @17 = (@15*@10) */
  w17  = (w15*w10);
  /* #90: @23 = (@23-@17) */
  w23 -= w17;
  /* #91: @15 = (@15*@22) */
  w15 *= w22;
  /* #92: @3 = (@3*@18) */
  w03 *= w18;
  /* #93: @15 = (@15-@3) */
  w15 -= w03;
  /* #94: @4 = vertcat(@20, @23, @15) */
  rr=w04;
  *rr++ = w20;
  *rr++ = w23;
  *rr++ = w15;
  /* #95: @4 = (@6*@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) (*rr++)  = (w06*(*cs++));
  /* #96: @25 = (@25+@4) */
  for (i=0, rr=w25, cs=w04; i<3; ++i) (*rr++) += (*cs++);
  /* #97: @6 = @2[11] */
  w06 = wr02[11];
  /* #98: @28 = 
  [[0.00167, 0, 0], 
   [0, 0.00167, 0], 
   [0, 0, 0.00333]] */
  wr28 = casadi_c4;
  /* #99: @4 = @2[10:13] */
  wr04 = wr02+10;
  /* #100: @7 = mac(@28,@4,@11) */
  casadi_copy(w11, 3, w07);
  for (i=0, rr=w07; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr28+j, ct=wr04+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #101: @20 = @7[2] */
  for (rr=(&w20), cs=w07+2; cs!=w07+3; cs+=1) *rr++ = *cs;
  /* #102: @23 = (@6*@20) */
  w23  = (w06*w20);
  /* #103: @15 = @2[12] */
  w15 = wr02[12];
  /* #104: @3 = @7[1] */
  for (rr=(&w03), cs=w07+1; cs!=w07+2; cs+=1) *rr++ = *cs;
  /* #105: @17 = (@15*@3) */
  w17  = (w15*w03);
  /* #106: @23 = (@23-@17) */
  w23 -= w17;
  /* #107: @17 = @7[0] */
  for (rr=(&w17), cs=w07+0; cs!=w07+1; cs+=1) *rr++ = *cs;
  /* #108: @14 = (@15*@17) */
  w14  = (w15*w17);
  /* #109: @16 = @2[10] */
  w16 = wr02[10];
  /* #110: @20 = (@16*@20) */
  w20  = (w16*w20);
  /* #111: @14 = (@14-@20) */
  w14 -= w20;
  /* #112: @3 = (@16*@3) */
  w03  = (w16*w03);
  /* #113: @17 = (@6*@17) */
  w17  = (w06*w17);
  /* #114: @3 = (@3-@17) */
  w03 -= w17;
  /* #115: @7 = vertcat(@23, @14, @3) */
  rr=w07;
  *rr++ = w23;
  *rr++ = w14;
  *rr++ = w03;
  /* #116: @25 = (@25-@7) */
  for (i=0, rr=w25, cs=w07; i<3; ++i) (*rr++) -= (*cs++);
  /* #117: @7 = mac(@30,@25,@11) */
  casadi_copy(w11, 3, w07);
  for (i=0, rr=w07; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr30+j, ct=w25+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #118: @23 = @7[1] */
  for (rr=(&w23), cs=w07+1; cs!=w07+2; cs+=1) *rr++ = *cs;
  /* #119: @14 = (@23*@12) */
  w14  = (w23*w12);
  /* #120: @3 = @7[2] */
  for (rr=(&w03), cs=w07+2; cs!=w07+3; cs+=1) *rr++ = *cs;
  /* #121: @17 = (@3*@13) */
  w17  = (w03*w13);
  /* #122: @14 = (@14-@17) */
  w14 -= w17;
  /* #123: @17 = (@3*@19) */
  w17  = (w03*w19);
  /* #124: @20 = @7[0] */
  for (rr=(&w20), cs=w07+0; cs!=w07+1; cs+=1) *rr++ = *cs;
  /* #125: @21 = (@20*@12) */
  w21  = (w20*w12);
  /* #126: @17 = (@17-@21) */
  w17 -= w21;
  /* #127: @21 = (@20*@13) */
  w21  = (w20*w13);
  /* #128: @24 = (@23*@19) */
  w24  = (w23*w19);
  /* #129: @21 = (@21-@24) */
  w21 -= w24;
  /* #130: @7 = vertcat(@14, @17, @21) */
  rr=w07;
  *rr++ = w14;
  *rr++ = w17;
  *rr++ = w21;
  /* #131: @14 = (@16*@13) */
  w14  = (w16*w13);
  /* #132: @17 = (@6*@19) */
  w17  = (w06*w19);
  /* #133: @14 = (@14-@17) */
  w14 -= w17;
  /* #134: @17 = (@6*@14) */
  w17  = (w06*w14);
  /* #135: @19 = (@15*@19) */
  w19  = (w15*w19);
  /* #136: @21 = (@16*@12) */
  w21  = (w16*w12);
  /* #137: @19 = (@19-@21) */
  w19 -= w21;
  /* #138: @21 = (@15*@19) */
  w21  = (w15*w19);
  /* #139: @17 = (@17-@21) */
  w17 -= w21;
  /* #140: @12 = (@6*@12) */
  w12  = (w06*w12);
  /* #141: @13 = (@15*@13) */
  w13  = (w15*w13);
  /* #142: @12 = (@12-@13) */
  w12 -= w13;
  /* #143: @13 = (@15*@12) */
  w13  = (w15*w12);
  /* #144: @14 = (@16*@14) */
  w14  = (w16*w14);
  /* #145: @13 = (@13-@14) */
  w13 -= w14;
  /* #146: @19 = (@16*@19) */
  w19  = (w16*w19);
  /* #147: @12 = (@6*@12) */
  w12  = (w06*w12);
  /* #148: @19 = (@19-@12) */
  w19 -= w12;
  /* #149: @25 = vertcat(@17, @13, @19) */
  rr=w25;
  *rr++ = w17;
  *rr++ = w13;
  *rr++ = w19;
  /* #150: @7 = (@7+@25) */
  for (i=0, rr=w07, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #151: @25 = mac(@29,@7,@11) */
  casadi_copy(w11, 3, w25);
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w29+j, ct=w07+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #152: @25 = (@9+@25) */
  for (i=0, rr=w25, cr=w09, cs=w25; i<3; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #153: @17 = 0.5 */
  w17 = 5.0000000000000000e-01;
  /* #154: @13 = @2[20] */
  w13 = wr02[20];
  /* #155: @19 = @2[15] */
  w19 = wr02[15];
  /* #156: @12 = (@13*@19) */
  w12  = (w13*w19);
  /* #157: @14 = @2[21] */
  w14 = wr02[21];
  /* #158: @21 = @2[14] */
  w21 = wr02[14];
  /* #159: @24 = (@14*@21) */
  w24  = (w14*w21);
  /* #160: @12 = (@12-@24) */
  w12 -= w24;
  /* #161: @24 = @2[13] */
  w24 = wr02[13];
  /* #162: @14 = (@14*@24) */
  w14 *= w24;
  /* #163: @31 = @2[19] */
  w31 = wr02[19];
  /* #164: @32 = (@31*@19) */
  w32  = (w31*w19);
  /* #165: @14 = (@14-@32) */
  w14 -= w32;
  /* #166: @31 = (@31*@21) */
  w31 *= w21;
  /* #167: @13 = (@13*@24) */
  w13 *= w24;
  /* #168: @31 = (@31-@13) */
  w31 -= w13;
  /* #169: @7 = vertcat(@12, @14, @31) */
  rr=w07;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w31;
  /* #170: @12 = @2[17] */
  w12 = wr02[17];
  /* #171: @14 = @2[16] */
  w14 = wr02[16];
  /* #172: @31 = (@14*@21) */
  w31  = (w14*w21);
  /* #173: @13 = (@12*@24) */
  w13  = (w12*w24);
  /* #174: @31 = (@31-@13) */
  w31 -= w13;
  /* #175: @13 = (@12*@31) */
  w13  = (w12*w31);
  /* #176: @32 = @2[18] */
  w32 = wr02[18];
  /* #177: @24 = (@32*@24) */
  w24  = (w32*w24);
  /* #178: @33 = (@14*@19) */
  w33  = (w14*w19);
  /* #179: @24 = (@24-@33) */
  w24 -= w33;
  /* #180: @33 = (@32*@24) */
  w33  = (w32*w24);
  /* #181: @13 = (@13-@33) */
  w13 -= w33;
  /* #182: @19 = (@12*@19) */
  w19  = (w12*w19);
  /* #183: @21 = (@32*@21) */
  w21  = (w32*w21);
  /* #184: @19 = (@19-@21) */
  w19 -= w21;
  /* #185: @32 = (@32*@19) */
  w32 *= w19;
  /* #186: @31 = (@14*@31) */
  w31  = (w14*w31);
  /* #187: @32 = (@32-@31) */
  w32 -= w31;
  /* #188: @14 = (@14*@24) */
  w14 *= w24;
  /* #189: @12 = (@12*@19) */
  w12 *= w19;
  /* #190: @14 = (@14-@12) */
  w14 -= w12;
  /* #191: @4 = vertcat(@13, @32, @14) */
  rr=w04;
  *rr++ = w13;
  *rr++ = w32;
  *rr++ = w14;
  /* #192: @7 = (@7+@4) */
  for (i=0, rr=w07, cs=w04; i<3; ++i) (*rr++) += (*cs++);
  /* #193: @7 = (@17*@7) */
  for (i=0, rr=w07, cs=w07; i<3; ++i) (*rr++)  = (w17*(*cs++));
  /* #194: @25 = (@25-@7) */
  for (i=0, rr=w25, cs=w07; i<3; ++i) (*rr++) -= (*cs++);
  /* #195: @25 = (@25-@1) */
  for (i=0, rr=w25, cs=w01; i<3; ++i) (*rr++) -= (*cs++);
  /* #196: @25 = (@0*@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #197: @25 = (@25-@5) */
  for (i=0, rr=w25, cs=w05; i<3; ++i) (*rr++) -= (*cs++);
  /* #198: @13 = ||@25||_F */
  w13 = casadi_norm_2(3, w25);
  /* #199: output[0][0] = @13 */
  if (res[0]) res[0][0] = w13;
  /* #200: @13 = (@23*@10) */
  w13  = (w23*w10);
  /* #201: @32 = (@3*@22) */
  w32  = (w03*w22);
  /* #202: @13 = (@13-@32) */
  w13 -= w32;
  /* #203: @3 = (@3*@18) */
  w03 *= w18;
  /* #204: @32 = (@20*@10) */
  w32  = (w20*w10);
  /* #205: @3 = (@3-@32) */
  w03 -= w32;
  /* #206: @20 = (@20*@22) */
  w20 *= w22;
  /* #207: @23 = (@23*@18) */
  w23 *= w18;
  /* #208: @20 = (@20-@23) */
  w20 -= w23;
  /* #209: @25 = vertcat(@13, @3, @20) */
  rr=w25;
  *rr++ = w13;
  *rr++ = w03;
  *rr++ = w20;
  /* #210: @13 = (@16*@22) */
  w13  = (w16*w22);
  /* #211: @3 = (@6*@18) */
  w03  = (w06*w18);
  /* #212: @13 = (@13-@3) */
  w13 -= w03;
  /* #213: @3 = (@6*@13) */
  w03  = (w06*w13);
  /* #214: @18 = (@15*@18) */
  w18  = (w15*w18);
  /* #215: @20 = (@16*@10) */
  w20  = (w16*w10);
  /* #216: @18 = (@18-@20) */
  w18 -= w20;
  /* #217: @20 = (@15*@18) */
  w20  = (w15*w18);
  /* #218: @3 = (@3-@20) */
  w03 -= w20;
  /* #219: @10 = (@6*@10) */
  w10  = (w06*w10);
  /* #220: @22 = (@15*@22) */
  w22  = (w15*w22);
  /* #221: @10 = (@10-@22) */
  w10 -= w22;
  /* #222: @15 = (@15*@10) */
  w15 *= w10;
  /* #223: @13 = (@16*@13) */
  w13  = (w16*w13);
  /* #224: @15 = (@15-@13) */
  w15 -= w13;
  /* #225: @16 = (@16*@18) */
  w16 *= w18;
  /* #226: @6 = (@6*@10) */
  w06 *= w10;
  /* #227: @16 = (@16-@6) */
  w16 -= w06;
  /* #228: @5 = vertcat(@3, @15, @16) */
  rr=w05;
  *rr++ = w03;
  *rr++ = w15;
  *rr++ = w16;
  /* #229: @25 = (@25+@5) */
  for (i=0, rr=w25, cs=w05; i<3; ++i) (*rr++) += (*cs++);
  /* #230: @11 = mac(@29,@25,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w29+j, ct=w25+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #231: @9 = (@9+@11) */
  for (i=0, rr=w09, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #232: @3 = @2[34] */
  w03 = wr02[34];
  /* #233: @15 = @2[29] */
  w15 = wr02[29];
  /* #234: @16 = (@3*@15) */
  w16  = (w03*w15);
  /* #235: @6 = @2[35] */
  w06 = wr02[35];
  /* #236: @10 = @2[28] */
  w10 = wr02[28];
  /* #237: @18 = (@6*@10) */
  w18  = (w06*w10);
  /* #238: @16 = (@16-@18) */
  w16 -= w18;
  /* #239: @18 = @2[27] */
  w18 = wr02[27];
  /* #240: @6 = (@6*@18) */
  w06 *= w18;
  /* #241: @13 = @2[33] */
  w13 = wr02[33];
  /* #242: @22 = (@13*@15) */
  w22  = (w13*w15);
  /* #243: @6 = (@6-@22) */
  w06 -= w22;
  /* #244: @13 = (@13*@10) */
  w13 *= w10;
  /* #245: @3 = (@3*@18) */
  w03 *= w18;
  /* #246: @13 = (@13-@3) */
  w13 -= w03;
  /* #247: @11 = vertcat(@16, @6, @13) */
  rr=w11;
  *rr++ = w16;
  *rr++ = w06;
  *rr++ = w13;
  /* #248: @16 = @2[31] */
  w16 = wr02[31];
  /* #249: @6 = @2[30] */
  w06 = wr02[30];
  /* #250: @13 = (@6*@10) */
  w13  = (w06*w10);
  /* #251: @3 = (@16*@18) */
  w03  = (w16*w18);
  /* #252: @13 = (@13-@3) */
  w13 -= w03;
  /* #253: @3 = (@16*@13) */
  w03  = (w16*w13);
  /* #254: @22 = @2[32] */
  w22 = wr02[32];
  /* #255: @18 = (@22*@18) */
  w18  = (w22*w18);
  /* #256: @20 = (@6*@15) */
  w20  = (w06*w15);
  /* #257: @18 = (@18-@20) */
  w18 -= w20;
  /* #258: @20 = (@22*@18) */
  w20  = (w22*w18);
  /* #259: @3 = (@3-@20) */
  w03 -= w20;
  /* #260: @15 = (@16*@15) */
  w15  = (w16*w15);
  /* #261: @10 = (@22*@10) */
  w10  = (w22*w10);
  /* #262: @15 = (@15-@10) */
  w15 -= w10;
  /* #263: @22 = (@22*@15) */
  w22 *= w15;
  /* #264: @13 = (@6*@13) */
  w13  = (w06*w13);
  /* #265: @22 = (@22-@13) */
  w22 -= w13;
  /* #266: @6 = (@6*@18) */
  w06 *= w18;
  /* #267: @16 = (@16*@15) */
  w16 *= w15;
  /* #268: @6 = (@6-@16) */
  w06 -= w16;
  /* #269: @25 = vertcat(@3, @22, @6) */
  rr=w25;
  *rr++ = w03;
  *rr++ = w22;
  *rr++ = w06;
  /* #270: @11 = (@11+@25) */
  for (i=0, rr=w11, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #271: @11 = (@17*@11) */
  for (i=0, rr=w11, cs=w11; i<3; ++i) (*rr++)  = (w17*(*cs++));
  /* #272: @9 = (@9-@11) */
  for (i=0, rr=w09, cs=w11; i<3; ++i) (*rr++) -= (*cs++);
  /* #273: @9 = (@9-@1) */
  for (i=0, rr=w09, cs=w01; i<3; ++i) (*rr++) -= (*cs++);
  /* #274: @9 = (@0*@9) */
  for (i=0, rr=w09, cs=w09; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #275: @9 = (@9-@8) */
  for (i=0, rr=w09, cs=w08; i<3; ++i) (*rr++) -= (*cs++);
  /* #276: @0 = ||@9||_F */
  w00 = casadi_norm_2(3, w09);
  /* #277: output[0][1] = @0 */
  if (res[0]) res[0][1] = w00;
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_2_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int load_cable_2_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_2_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void load_cable_2_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int load_cable_2_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void load_cable_2_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void load_cable_2_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void load_cable_2_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int load_cable_2_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int load_cable_2_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real load_cable_2_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* load_cable_2_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* load_cable_2_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* load_cable_2_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* load_cable_2_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int load_cable_2_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 121;
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_2_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 121*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
