/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) load_cable_4_cost_y_0_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[56] = 
  {0, 1, 2, 3, 4, 5, 6, 10,
  14, 18, 19, 20, 21, 22, 23, 24,
  25, 26, 27, 28, 29, 30, 31, 32,
  33, 34, 35, 36, 37, 38, 39, 40,
  41, 42, 43, 44, 45, 46, 47, 48,
  49, 50, 51, 52, 53, 54, 55, 56,
  57, 58, 59, 60, 61, 62, 63, 64};
static const casadi_int casadi_s1[3] = {69, 1, 1};
static const casadi_int casadi_s2[3] = {16, 1, 1};
static const casadi_int casadi_s3[3] = {0, 1, 1};
static const casadi_int casadi_s4[3] = {0, 0, 1};
static const casadi_int casadi_s5[3] = {4, 1, 1};
static const casadi_int casadi_s6[3] = {56, 1, 1};
static const casadi_int casadi_s7[124] = 
  {85, 56, 0, 1, 2, 3, 4, 5,
  6, 10, 14, 18, 19, 20, 21, 22,
  23, 24, 25, 26, 27, 28, 29, 30,
  31, 32, 33, 34, 35, 36, 37, 38,
  39, 40, 41, 42, 43, 44, 45, 46,
  47, 48, 49, 50, 51, 52, 53, 54,
  55, 56, 57, 58, 59, 60, 61, 62,
  63, 64, 65, 16, 17, 18, 19, 20,
  21, 22, 23, 24, 25, 22, 23, 24,
  25, 22, 23, 24, 25, 26, 27, 28,
  29, 30, 31, 43, 44, 45, 57, 58,
  59, 71, 72, 73, 41, 55, 69, 83,
  32, 33, 34, 46, 47, 48, 60, 61,
  62, 74, 75, 76, 0, 1, 2, 3,
  4, 5, 6, 7, 8, 9, 10, 11,
  12, 13, 14, 15};
static const casadi_int casadi_s8[3] = {56, 0, 1};

static const casadi_real casadi_zeros[69] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0.};

/* load_cable_4_cost_y_0_fun_jac_ut_xt:(i0[69],i1[16],i2[0],i3[],i4[4])->(o0[56],o1[85x56,65nz],o2[56x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w01=w+69, *w02=w+72, w03, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, *w15=w+88, *w16=w+104, *w17=w+169, *w18=w+251, *w19=w+317, *w20=w+320, *w21=w+323, *w22=w+326, *w23=w+329;
  casadi_real *w24=w+332, *w25=w+335, *w26=w+338, *w27=w+341, *w28=w+344, *w29=w+347, *w30=w+350;
  const casadi_int *cii;
  const casadi_real *cs, *wr00, *wr01, *wr15;
  /* #0: @0 = input[0][0] */
  wr00 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = @0[:3] */
  wr01 = wr00+0;
  /* #2: output[0][0] = @1 */
  casadi_copy(wr01, 3, res[0]);
  /* #3: @1 = @0[3:6] */
  wr01 = wr00+3;
  /* #4: output[0][1] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+3);
  /* #5: @2 = input[4][0] */
  casadi_copy(arg[4], 4, w02);
  /* #6: @3 = @2[0] */
  for (rr=(&w03), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #7: @4 = @0[6] */
  w04 = wr00[6];
  /* #8: @5 = (@3*@4) */
  w05  = (w03*w04);
  /* #9: @6 = @2[1] */
  for (rr=(&w06), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #10: @7 = @0[7] */
  w07 = wr00[7];
  /* #11: @8 = (@6*@7) */
  w08  = (w06*w07);
  /* #12: @5 = (@5+@8) */
  w05 += w08;
  /* #13: @8 = @2[2] */
  for (rr=(&w08), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #14: @9 = @0[8] */
  w09 = wr00[8];
  /* #15: @10 = (@8*@9) */
  w10  = (w08*w09);
  /* #16: @5 = (@5+@10) */
  w05 += w10;
  /* #17: @10 = @2[3] */
  for (rr=(&w10), cs=w02+3; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #18: @11 = @0[9] */
  w11 = wr00[9];
  /* #19: @12 = (@10*@11) */
  w12  = (w10*w11);
  /* #20: @5 = (@5+@12) */
  w05 += w12;
  /* #21: @12 = (@6*@4) */
  w12  = (w06*w04);
  /* #22: @13 = (@3*@7) */
  w13  = (w03*w07);
  /* #23: @12 = (@12-@13) */
  w12 -= w13;
  /* #24: @13 = (@8*@11) */
  w13  = (w08*w11);
  /* #25: @12 = (@12-@13) */
  w12 -= w13;
  /* #26: @13 = (@10*@9) */
  w13  = (w10*w09);
  /* #27: @12 = (@12+@13) */
  w12 += w13;
  /* #28: @13 = (@6*@11) */
  w13  = (w06*w11);
  /* #29: @14 = (@3*@9) */
  w14  = (w03*w09);
  /* #30: @13 = (@13-@14) */
  w13 -= w14;
  /* #31: @14 = (@8*@4) */
  w14  = (w08*w04);
  /* #32: @13 = (@13+@14) */
  w13 += w14;
  /* #33: @14 = (@10*@7) */
  w14  = (w10*w07);
  /* #34: @13 = (@13-@14) */
  w13 -= w14;
  /* #35: @9 = (@6*@9) */
  w09  = (w06*w09);
  /* #36: @9 = (-@9) */
  w09 = (- w09 );
  /* #37: @11 = (@3*@11) */
  w11  = (w03*w11);
  /* #38: @9 = (@9-@11) */
  w09 -= w11;
  /* #39: @7 = (@8*@7) */
  w07  = (w08*w07);
  /* #40: @9 = (@9+@7) */
  w09 += w07;
  /* #41: @4 = (@10*@4) */
  w04  = (w10*w04);
  /* #42: @9 = (@9+@4) */
  w09 += w04;
  /* #43: @2 = vertcat(@5, @12, @13, @9) */
  rr=w02;
  *rr++ = w05;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w09;
  /* #44: @1 = @2[1:4] */
  for (rr=w01, cs=w02+1; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #45: @1 = (2.*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #46: output[0][2] = @1 */
  if (res[0]) casadi_copy(w01, 3, res[0]+6);
  /* #47: @1 = @0[10:13] */
  wr01 = wr00+10;
  /* #48: output[0][3] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+9);
  /* #49: @1 = @0[13:16] */
  wr01 = wr00+13;
  /* #50: output[0][4] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+12);
  /* #51: @1 = @0[27:30] */
  wr01 = wr00+27;
  /* #52: output[0][5] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+15);
  /* #53: @1 = @0[41:44] */
  wr01 = wr00+41;
  /* #54: output[0][6] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+18);
  /* #55: @1 = @0[55:58] */
  wr01 = wr00+55;
  /* #56: output[0][7] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+21);
  /* #57: @5 = @0[25] */
  w05 = wr00[25];
  /* #58: output[0][8] = @5 */
  if (res[0]) res[0][24] = w05;
  /* #59: @5 = @0[39] */
  w05 = wr00[39];
  /* #60: output[0][9] = @5 */
  if (res[0]) res[0][25] = w05;
  /* #61: @5 = @0[53] */
  w05 = wr00[53];
  /* #62: output[0][10] = @5 */
  if (res[0]) res[0][26] = w05;
  /* #63: @5 = @0[67] */
  w05 = wr00[67];
  /* #64: output[0][11] = @5 */
  if (res[0]) res[0][27] = w05;
  /* #65: @1 = @0[16:19] */
  wr01 = wr00+16;
  /* #66: output[0][12] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+28);
  /* #67: @1 = @0[30:33] */
  wr01 = wr00+30;
  /* #68: output[0][13] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+31);
  /* #69: @1 = @0[44:47] */
  wr01 = wr00+44;
  /* #70: output[0][14] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+34);
  /* #71: @1 = @0[58:61] */
  wr01 = wr00+58;
  /* #72: output[0][15] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+37);
  /* #73: @15 = input[1][0] */
  wr15 = arg[1] ? arg[1] : casadi_zeros;
  /* #74: output[0][16] = @15 */
  if (res[0]) casadi_copy(wr15, 16, res[0]+40);
  /* #75: @16 = zeros(85x56,65nz) */
  casadi_clear(w16, 65);
  /* #76: @17 = ones(85x1,82nz) */
  casadi_fill(w17, 82, 1.);
  /* #77: {@15, @18} = vertsplit(@17) */
  casadi_copy(w17, 16, w15);
  casadi_copy(w17+16, 66, w18);
  /* #78: @1 = @18[:3] */
  for (rr=w01, cs=w18+0; cs!=w18+3; cs+=1) *rr++ = *cs;
  /* #79: @19 = @18[3:6] */
  for (rr=w19, cs=w18+3; cs!=w18+6; cs+=1) *rr++ = *cs;
  /* #80: @5 = @18[6] */
  for (rr=(&w05), cs=w18+6; cs!=w18+7; cs+=1) *rr++ = *cs;
  /* #81: @12 = (@3*@5) */
  w12  = (w03*w05);
  /* #82: @13 = (@6*@5) */
  w13  = (w06*w05);
  /* #83: @9 = (@8*@5) */
  w09  = (w08*w05);
  /* #84: @5 = (@10*@5) */
  w05  = (w10*w05);
  /* #85: @2 = vertcat(@12, @13, @9, @5) */
  rr=w02;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w09;
  *rr++ = w05;
  /* #86: @20 = @2[1:4] */
  for (rr=w20, cs=w02+1; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #87: @20 = (2.*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #88: @21 = @18[7:10] */
  for (rr=w21, cs=w18+7; cs!=w18+10; cs+=1) *rr++ = *cs;
  /* #89: @22 = @18[10:13] */
  for (rr=w22, cs=w18+10; cs!=w18+13; cs+=1) *rr++ = *cs;
  /* #90: @23 = @18[24:27] */
  for (rr=w23, cs=w18+24; cs!=w18+27; cs+=1) *rr++ = *cs;
  /* #91: @24 = @18[38:41] */
  for (rr=w24, cs=w18+38; cs!=w18+41; cs+=1) *rr++ = *cs;
  /* #92: @25 = @18[52:55] */
  for (rr=w25, cs=w18+52; cs!=w18+55; cs+=1) *rr++ = *cs;
  /* #93: @12 = @18[22] */
  for (rr=(&w12), cs=w18+22; cs!=w18+23; cs+=1) *rr++ = *cs;
  /* #94: @13 = @18[36] */
  for (rr=(&w13), cs=w18+36; cs!=w18+37; cs+=1) *rr++ = *cs;
  /* #95: @9 = @18[50] */
  for (rr=(&w09), cs=w18+50; cs!=w18+51; cs+=1) *rr++ = *cs;
  /* #96: @5 = @18[64] */
  for (rr=(&w05), cs=w18+64; cs!=w18+65; cs+=1) *rr++ = *cs;
  /* #97: @26 = @18[13:16] */
  for (rr=w26, cs=w18+13; cs!=w18+16; cs+=1) *rr++ = *cs;
  /* #98: @27 = @18[27:30] */
  for (rr=w27, cs=w18+27; cs!=w18+30; cs+=1) *rr++ = *cs;
  /* #99: @28 = @18[41:44] */
  for (rr=w28, cs=w18+41; cs!=w18+44; cs+=1) *rr++ = *cs;
  /* #100: @29 = @18[55:58] */
  for (rr=w29, cs=w18+55; cs!=w18+58; cs+=1) *rr++ = *cs;
  /* #101: @30 = vertcat(@1, @19, @20, @21, @22, @23, @24, @25, @12, @13, @9, @5, @26, @27, @28, @29, @15) */
  rr=w30;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w09;
  *rr++ = w05;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<16; ++i) *rr++ = *cs++;
  /* #102: (@16[0, 1, 2, 3, 4, 5, 6, 10, 14, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64] = @30) */
  for (cii=casadi_s0, rr=w16, cs=w30; cii!=casadi_s0+56; ++cii, ++cs) rr[*cii] = *cs;
  /* #103: @12 = ones(85x1,1nz) */
  w12 = 1.;
  /* #104: {NULL, @13} = vertsplit(@12) */
  w13 = w12;
  /* #105: @12 = @13[0] */
  for (rr=(&w12), cs=(&w13)+0; cs!=(&w13)+1; cs+=1) *rr++ = *cs;
  /* #106: @13 = (@6*@12) */
  w13  = (w06*w12);
  /* #107: @9 = (@3*@12) */
  w09  = (w03*w12);
  /* #108: @9 = (-@9) */
  w09 = (- w09 );
  /* #109: @5 = (@10*@12) */
  w05  = (w10*w12);
  /* #110: @5 = (-@5) */
  w05 = (- w05 );
  /* #111: @12 = (@8*@12) */
  w12  = (w08*w12);
  /* #112: @2 = vertcat(@13, @9, @5, @12) */
  rr=w02;
  *rr++ = w13;
  *rr++ = w09;
  *rr++ = w05;
  *rr++ = w12;
  /* #113: @1 = @2[1:4] */
  for (rr=w01, cs=w02+1; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #114: @1 = (2.*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #115: (@16[7:19:4] = @1) */
  for (rr=w16+7, cs=w01; rr!=w16+19; rr+=4) *rr = *cs++;
  /* #116: @13 = ones(85x1,1nz) */
  w13 = 1.;
  /* #117: {NULL, @9} = vertsplit(@13) */
  w09 = w13;
  /* #118: @13 = @9[0] */
  for (rr=(&w13), cs=(&w09)+0; cs!=(&w09)+1; cs+=1) *rr++ = *cs;
  /* #119: @9 = (@8*@13) */
  w09  = (w08*w13);
  /* #120: @5 = (@10*@13) */
  w05  = (w10*w13);
  /* #121: @12 = (@3*@13) */
  w12  = (w03*w13);
  /* #122: @12 = (-@12) */
  w12 = (- w12 );
  /* #123: @13 = (@6*@13) */
  w13  = (w06*w13);
  /* #124: @13 = (-@13) */
  w13 = (- w13 );
  /* #125: @2 = vertcat(@9, @5, @12, @13) */
  rr=w02;
  *rr++ = w09;
  *rr++ = w05;
  *rr++ = w12;
  *rr++ = w13;
  /* #126: @1 = @2[1:4] */
  for (rr=w01, cs=w02+1; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #127: @1 = (2.*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #128: (@16[8:20:4] = @1) */
  for (rr=w16+8, cs=w01; rr!=w16+20; rr+=4) *rr = *cs++;
  /* #129: @9 = ones(85x1,1nz) */
  w09 = 1.;
  /* #130: {NULL, @5} = vertsplit(@9) */
  w05 = w09;
  /* #131: @9 = @5[0] */
  for (rr=(&w09), cs=(&w05)+0; cs!=(&w05)+1; cs+=1) *rr++ = *cs;
  /* #132: @10 = (@10*@9) */
  w10 *= w09;
  /* #133: @8 = (@8*@9) */
  w08 *= w09;
  /* #134: @8 = (-@8) */
  w08 = (- w08 );
  /* #135: @6 = (@6*@9) */
  w06 *= w09;
  /* #136: @3 = (@3*@9) */
  w03 *= w09;
  /* #137: @3 = (-@3) */
  w03 = (- w03 );
  /* #138: @2 = vertcat(@10, @8, @6, @3) */
  rr=w02;
  *rr++ = w10;
  *rr++ = w08;
  *rr++ = w06;
  *rr++ = w03;
  /* #139: @1 = @2[1:4] */
  for (rr=w01, cs=w02+1; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #140: @1 = (2.*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #141: (@16[9:21:4] = @1) */
  for (rr=w16+9, cs=w01; rr!=w16+21; rr+=4) *rr = *cs++;
  /* #142: output[1][0] = @16 */
  casadi_copy(w16, 65, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_4_cost_y_0_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int load_cable_4_cost_y_0_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_4_cost_y_0_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void load_cable_4_cost_y_0_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int load_cable_4_cost_y_0_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void load_cable_4_cost_y_0_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void load_cable_4_cost_y_0_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void load_cable_4_cost_y_0_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int load_cable_4_cost_y_0_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int load_cable_4_cost_y_0_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real load_cable_4_cost_y_0_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* load_cable_4_cost_y_0_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* load_cable_4_cost_y_0_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* load_cable_4_cost_y_0_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    case 4: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* load_cable_4_cost_y_0_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int load_cable_4_cost_y_0_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 22;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 406;
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_4_cost_y_0_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 22*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 406*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
