if(NOT DEFINED DEMO)
  message(FATAL_ERROR "DEMO is required")
endif()
if(NOT DEFINED OUT_DIR)
  set(OUT_DIR "/tmp/r6_3b4_ctest")
endif()
file(MAKE_DIRECTORY "${OUT_DIR}")
foreach(SCENE static_overflight other_cable)
  execute_process(
    COMMAND "${DEMO}" --scenario "${SCENE}" --csv-prefix "${OUT_DIR}/${SCENE}"
    RESULT_VARIABLE RC
    OUTPUT_VARIABLE OUT
    ERROR_VARIABLE ERR
  )
  message(STATUS "---- suspended_system_demo stdout (${SCENE}) ----\n${OUT}")
  if(NOT "${ERR}" STREQUAL "")
    message(STATUS "---- suspended_system_demo stderr (${SCENE}) ----\n${ERR}")
  endif()
  if(NOT RC EQUAL 0)
    message(FATAL_ERROR "B.4 suspended scenario '${SCENE}' failed with exit code ${RC}")
  endif()
  string(FIND "${OUT}" "suspended Octopus samples: 9 x 9 x 9" SAMPLE_POS)
  if(SAMPLE_POS EQUAL -1)
    message(FATAL_ERROR "B.4 suspended scenario '${SCENE}' did not exercise the 9x9x9 suspended-mode default")
  endif()
  string(FIND "${OUT}" "suspended replan rate: 10" RATE_POS)
  if(RATE_POS EQUAL -1)
    message(FATAL_ERROR "B.4 suspended scenario '${SCENE}' did not exercise the 10 Hz suspended-planner default")
  endif()
  string(FIND "${OUT}" "B.4 regression contract: true" CONTRACT_POS)
  if(CONTRACT_POS EQUAL -1)
    message(FATAL_ERROR "B.4 suspended scenario '${SCENE}' did not report a true contract")
  endif()
endforeach()
