/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quad_payload_dynamics_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {21, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {11, 1, 1};

static const casadi_real casadi_c0[3] = {0., 0., 9.8100000000000005e+00};

/* x_dot:(x[21],u[4],p[7])->(x_dot[21]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+4, w01, *w02=w+8, w03, *w04=w+13, w05, w06, w07, *w08=w+19, *w09=w+23, *w10=w+27;
  casadi_real *w11=w+31, *w12=w+35, *w13=w+51, *w14=w+67, w15, w16, w17, *w18=w+73, *w19=w+76, *w20=w+79, *w21=w+82, *w22=w+91;
  casadi_real w23, w24, w25, w26, w27;
  const casadi_real *cs, *ct;
  /* #0: @0 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 3, w00);
  /* #1: output[0][0] = @0 */
  casadi_copy(w00, 3, res[0]);
  /* #2: @1 = 0.5 */
  w01 = 5.0000000000000000e-01;
  /* #3: @2 = zeros(4x1) */
  casadi_clear(w02, 4);
  /* #4: @3 = 0 */
  w03 = 0.;
  /* #5: @4 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w04);
  /* #6: @5 = @4[0] */
  for (rr=(&w05), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #7: @5 = (-@5) */
  w05 = (- w05 );
  /* #8: @6 = @4[1] */
  for (rr=(&w06), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #9: @6 = (-@6) */
  w06 = (- w06 );
  /* #10: @7 = @4[2] */
  for (rr=(&w07), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #11: @7 = (-@7) */
  w07 = (- w07 );
  /* #12: @8 = horzcat(@3, @5, @6, @7) */
  rr=w08;
  *rr++ = w03;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  /* #13: @8 = @8' */
  /* #14: @3 = @4[0] */
  for (rr=(&w03), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #15: @5 = 0 */
  w05 = 0.;
  /* #16: @6 = @4[2] */
  for (rr=(&w06), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #17: @7 = @4[1] */
  for (rr=(&w07), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #18: @7 = (-@7) */
  w07 = (- w07 );
  /* #19: @9 = horzcat(@3, @5, @6, @7) */
  rr=w09;
  *rr++ = w03;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  /* #20: @9 = @9' */
  /* #21: @3 = @4[1] */
  for (rr=(&w03), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #22: @5 = @4[2] */
  for (rr=(&w05), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #23: @5 = (-@5) */
  w05 = (- w05 );
  /* #24: @6 = 0 */
  w06 = 0.;
  /* #25: @7 = @4[0] */
  for (rr=(&w07), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #26: @10 = horzcat(@3, @5, @6, @7) */
  rr=w10;
  *rr++ = w03;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  /* #27: @10 = @10' */
  /* #28: @3 = @4[2] */
  for (rr=(&w03), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #29: @5 = @4[1] */
  for (rr=(&w05), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #30: @6 = @4[0] */
  for (rr=(&w06), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #31: @6 = (-@6) */
  w06 = (- w06 );
  /* #32: @7 = 0 */
  w07 = 0.;
  /* #33: @11 = horzcat(@3, @5, @6, @7) */
  rr=w11;
  *rr++ = w03;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  /* #34: @11 = @11' */
  /* #35: @12 = horzcat(@8, @9, @10, @11) */
  rr=w12;
  for (i=0, cs=w08; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w09; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #36: @13 = @12' */
  for (i=0, rr=w13, cs=w12; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #37: @8 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w08);
  /* #38: @2 = mac(@13,@8,@2) */
  for (i=0, rr=w02; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w13+j, ct=w08+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #39: @2 = (@1*@2) */
  for (i=0, rr=w02, cs=w02; i<4; ++i) (*rr++)  = (w01*(*cs++));
  /* #40: output[0][1] = @2 */
  if (res[0]) casadi_copy(w02, 4, res[0]+3);
  /* #41: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #42: @1 = 1 */
  w01 = 1.;
  /* #43: @3 = @8[2] */
  for (rr=(&w03), cs=w08+2; cs!=w08+3; cs+=1) *rr++ = *cs;
  /* #44: @5 = sq(@3) */
  w05 = casadi_sq( w03 );
  /* #45: @6 = @8[3] */
  for (rr=(&w06), cs=w08+3; cs!=w08+4; cs+=1) *rr++ = *cs;
  /* #46: @7 = sq(@6) */
  w07 = casadi_sq( w06 );
  /* #47: @5 = (@5+@7) */
  w05 += w07;
  /* #48: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #49: @1 = (@1-@5) */
  w01 -= w05;
  /* #50: @5 = @8[1] */
  for (rr=(&w05), cs=w08+1; cs!=w08+2; cs+=1) *rr++ = *cs;
  /* #51: @7 = (@5*@3) */
  w07  = (w05*w03);
  /* #52: @15 = @8[0] */
  for (rr=(&w15), cs=w08+0; cs!=w08+1; cs+=1) *rr++ = *cs;
  /* #53: @16 = (@15*@6) */
  w16  = (w15*w06);
  /* #54: @7 = (@7-@16) */
  w07 -= w16;
  /* #55: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #56: @16 = (@5*@6) */
  w16  = (w05*w06);
  /* #57: @17 = (@15*@3) */
  w17  = (w15*w03);
  /* #58: @16 = (@16+@17) */
  w16 += w17;
  /* #59: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #60: @18 = horzcat(@1, @7, @16) */
  rr=w18;
  *rr++ = w01;
  *rr++ = w07;
  *rr++ = w16;
  /* #61: @18 = @18' */
  /* #62: @1 = (@5*@3) */
  w01  = (w05*w03);
  /* #63: @7 = (@15*@6) */
  w07  = (w15*w06);
  /* #64: @1 = (@1+@7) */
  w01 += w07;
  /* #65: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #66: @7 = 1 */
  w07 = 1.;
  /* #67: @16 = sq(@5) */
  w16 = casadi_sq( w05 );
  /* #68: @17 = sq(@6) */
  w17 = casadi_sq( w06 );
  /* #69: @16 = (@16+@17) */
  w16 += w17;
  /* #70: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #71: @7 = (@7-@16) */
  w07 -= w16;
  /* #72: @16 = (@3*@6) */
  w16  = (w03*w06);
  /* #73: @17 = (@15*@5) */
  w17  = (w15*w05);
  /* #74: @16 = (@16-@17) */
  w16 -= w17;
  /* #75: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #76: @19 = horzcat(@1, @7, @16) */
  rr=w19;
  *rr++ = w01;
  *rr++ = w07;
  *rr++ = w16;
  /* #77: @19 = @19' */
  /* #78: @1 = (@5*@6) */
  w01  = (w05*w06);
  /* #79: @7 = (@15*@3) */
  w07  = (w15*w03);
  /* #80: @1 = (@1-@7) */
  w01 -= w07;
  /* #81: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #82: @6 = (@3*@6) */
  w06  = (w03*w06);
  /* #83: @15 = (@15*@5) */
  w15 *= w05;
  /* #84: @6 = (@6+@15) */
  w06 += w15;
  /* #85: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #86: @15 = 1 */
  w15 = 1.;
  /* #87: @5 = sq(@5) */
  w05 = casadi_sq( w05 );
  /* #88: @3 = sq(@3) */
  w03 = casadi_sq( w03 );
  /* #89: @5 = (@5+@3) */
  w05 += w03;
  /* #90: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #91: @15 = (@15-@5) */
  w15 -= w05;
  /* #92: @20 = horzcat(@1, @6, @15) */
  rr=w20;
  *rr++ = w01;
  *rr++ = w06;
  *rr++ = w15;
  /* #93: @20 = @20' */
  /* #94: @21 = horzcat(@18, @19, @20) */
  rr=w21;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  /* #95: @22 = @21' */
  for (i=0, rr=w22, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #96: @1 = 0 */
  w01 = 0.;
  /* #97: @6 = 0 */
  w06 = 0.;
  /* #98: @15 = input[2][0] */
  w15 = arg[2] ? arg[2][0] : 0;
  /* #99: @2 = input[0][4] */
  casadi_copy(arg[0] ? arg[0]+13 : 0, 4, w02);
  /* #100: @5 = @2[2] */
  for (rr=(&w05), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #101: @5 = (@15*@5) */
  w05  = (w15*w05);
  /* #102: @18 = vertcat(@1, @6, @5) */
  rr=w18;
  *rr++ = w01;
  *rr++ = w06;
  *rr++ = w05;
  /* #103: @14 = mac(@22,@18,@14) */
  for (i=0, rr=w14; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w22+j, ct=w18+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #104: @18 = [0, 0, 9.81] */
  casadi_copy(casadi_c0, 3, w18);
  /* #105: @14 = (@14-@18) */
  for (i=0, rr=w14, cs=w18; i<3; ++i) (*rr++) -= (*cs++);
  /* #106: @1 = 0 */
  w01 = 0.;
  /* #107: @6 = 0 */
  w06 = 0.;
  /* #108: @5 = input[2][1] */
  w05 = arg[2] ? arg[2][1] : 0;
  /* #109: @3 = @0[2] */
  for (rr=(&w03), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #110: @3 = (@5*@3) */
  w03  = (w05*w03);
  /* #111: @3 = (-@3) */
  w03 = (- w03 );
  /* #112: @18 = vertcat(@1, @6, @3) */
  rr=w18;
  *rr++ = w01;
  *rr++ = w06;
  *rr++ = w03;
  /* #113: @14 = (@14+@18) */
  for (i=0, rr=w14, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #114: output[0][2] = @14 */
  if (res[0]) casadi_copy(w14, 3, res[0]+7);
  /* #115: @1 = 3.14159 */
  w01 = 3.1415926535897931e+00;
  /* #116: @6 = @2[0] */
  for (rr=(&w06), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #117: @3 = 1e-06 */
  w03 = 9.9999999999999995e-07;
  /* #118: @7 = sq(@6) */
  w07 = casadi_sq( w06 );
  /* #119: @3 = (@3+@7) */
  w03 += w07;
  /* #120: @3 = sqrt(@3) */
  w03 = sqrt( w03 );
  /* #121: @6 = (@6/@3) */
  w06 /= w03;
  /* #122: @7 = input[2][3] */
  w07 = arg[2] ? arg[2][3] : 0;
  /* #123: @16 = (@7*@3) */
  w16  = (w07*w03);
  /* #124: @17 = input[2][4] */
  w17 = arg[2] ? arg[2][4] : 0;
  /* #125: @23 = (@17-@7) */
  w23  = (w17-w07);
  /* #126: @24 = 5 */
  w24 = 5.;
  /* #127: @24 = pow(@3,@24) */
  w24  = pow(w03,w24);
  /* #128: @25 = input[2][5] */
  w25 = arg[2] ? arg[2][5] : 0;
  /* #129: @24 = (@24*@25) */
  w24 *= w25;
  /* #130: @26 = 1 */
  w26 = 1.;
  /* #131: @26 = (@26-@25) */
  w26 -= w25;
  /* #132: @26 = (@3*@26) */
  w26  = (w03*w26);
  /* #133: @24 = (@24+@26) */
  w24 += w26;
  /* #134: @3 = (@3*@24) */
  w03 *= w24;
  /* #135: @23 = (@23*@3) */
  w23 *= w03;
  /* #136: @16 = (@16+@23) */
  w16 += w23;
  /* #137: @6 = (@6*@16) */
  w06 *= w16;
  /* #138: @1 = (@1*@6) */
  w01 *= w06;
  /* #139: @6 = 180 */
  w06 = 180.;
  /* #140: @1 = (@1/@6) */
  w01 /= w06;
  /* #141: @6 = 3.14159 */
  w06 = 3.1415926535897931e+00;
  /* #142: @16 = @2[1] */
  for (rr=(&w16), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #143: @23 = 1e-06 */
  w23 = 9.9999999999999995e-07;
  /* #144: @3 = sq(@16) */
  w03 = casadi_sq( w16 );
  /* #145: @23 = (@23+@3) */
  w23 += w03;
  /* #146: @23 = sqrt(@23) */
  w23 = sqrt( w23 );
  /* #147: @16 = (@16/@23) */
  w16 /= w23;
  /* #148: @3 = (@7*@23) */
  w03  = (w07*w23);
  /* #149: @24 = (@17-@7) */
  w24  = (w17-w07);
  /* #150: @26 = 5 */
  w26 = 5.;
  /* #151: @26 = pow(@23,@26) */
  w26  = pow(w23,w26);
  /* #152: @26 = (@26*@25) */
  w26 *= w25;
  /* #153: @27 = 1 */
  w27 = 1.;
  /* #154: @27 = (@27-@25) */
  w27 -= w25;
  /* #155: @27 = (@23*@27) */
  w27  = (w23*w27);
  /* #156: @26 = (@26+@27) */
  w26 += w27;
  /* #157: @23 = (@23*@26) */
  w23 *= w26;
  /* #158: @24 = (@24*@23) */
  w24 *= w23;
  /* #159: @3 = (@3+@24) */
  w03 += w24;
  /* #160: @16 = (@16*@3) */
  w16 *= w03;
  /* #161: @6 = (@6*@16) */
  w06 *= w16;
  /* #162: @16 = 180 */
  w16 = 180.;
  /* #163: @6 = (@6/@16) */
  w06 /= w16;
  /* #164: @16 = 3.14159 */
  w16 = 3.1415926535897931e+00;
  /* #165: @3 = @2[3] */
  for (rr=(&w03), cs=w02+3; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #166: @24 = 1e-06 */
  w24 = 9.9999999999999995e-07;
  /* #167: @23 = sq(@3) */
  w23 = casadi_sq( w03 );
  /* #168: @24 = (@24+@23) */
  w24 += w23;
  /* #169: @24 = sqrt(@24) */
  w24 = sqrt( w24 );
  /* #170: @3 = (@3/@24) */
  w03 /= w24;
  /* #171: @23 = (@7*@24) */
  w23  = (w07*w24);
  /* #172: @17 = (@17-@7) */
  w17 -= w07;
  /* #173: @7 = 5 */
  w07 = 5.;
  /* #174: @7 = pow(@24,@7) */
  w07  = pow(w24,w07);
  /* #175: @7 = (@7*@25) */
  w07 *= w25;
  /* #176: @26 = 1 */
  w26 = 1.;
  /* #177: @26 = (@26-@25) */
  w26 -= w25;
  /* #178: @26 = (@24*@26) */
  w26  = (w24*w26);
  /* #179: @7 = (@7+@26) */
  w07 += w26;
  /* #180: @24 = (@24*@7) */
  w24 *= w07;
  /* #181: @17 = (@17*@24) */
  w17 *= w24;
  /* #182: @23 = (@23+@17) */
  w23 += w17;
  /* #183: @3 = (@3*@23) */
  w03 *= w23;
  /* #184: @16 = (@16*@3) */
  w16 *= w03;
  /* #185: @3 = 180 */
  w03 = 180.;
  /* #186: @16 = (@16/@3) */
  w16 /= w03;
  /* #187: @16 = (-@16) */
  w16 = (- w16 );
  /* #188: @14 = vertcat(@1, @6, @16) */
  rr=w14;
  *rr++ = w01;
  *rr++ = w06;
  *rr++ = w16;
  /* #189: @14 = (@14-@4) */
  for (i=0, rr=w14, cs=w04; i<3; ++i) (*rr++) -= (*cs++);
  /* #190: @1 = input[2][2] */
  w01 = arg[2] ? arg[2][2] : 0;
  /* #191: @14 = (@14/@1) */
  for (i=0, rr=w14; i<3; ++i) (*rr++) /= w01;
  /* #192: output[0][3] = @14 */
  if (res[0]) casadi_copy(w14, 3, res[0]+10);
  /* #193: @9 = input[1][0] */
  casadi_copy(arg[1], 4, w09);
  /* #194: output[0][4] = @9 */
  if (res[0]) casadi_copy(w09, 4, res[0]+13);
  /* #195: @1 = input[0][7] */
  w01 = arg[0] ? arg[0][19] : 0;
  /* #196: output[0][5] = @1 */
  if (res[0]) res[0][17] = w01;
  /* #197: @1 = input[0][8] */
  w01 = arg[0] ? arg[0][20] : 0;
  /* #198: output[0][6] = @1 */
  if (res[0]) res[0][18] = w01;
  /* #199: @1 = 9.81 */
  w01 = 9.8100000000000005e+00;
  /* #200: @6 = input[2][6] */
  w06 = arg[2] ? arg[2][6] : 0;
  /* #201: @1 = (@1/@6) */
  w01 /= w06;
  /* #202: @16 = input[0][5] */
  w16 = arg[0] ? arg[0][17] : 0;
  /* #203: @1 = (@1*@16) */
  w01 *= w16;
  /* #204: @1 = (-@1) */
  w01 = (- w01 );
  /* #205: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #206: @16 = 1 */
  w16 = 1.;
  /* #207: @3 = @8[2] */
  for (rr=(&w03), cs=w08+2; cs!=w08+3; cs+=1) *rr++ = *cs;
  /* #208: @23 = sq(@3) */
  w23 = casadi_sq( w03 );
  /* #209: @17 = @8[3] */
  for (rr=(&w17), cs=w08+3; cs!=w08+4; cs+=1) *rr++ = *cs;
  /* #210: @24 = sq(@17) */
  w24 = casadi_sq( w17 );
  /* #211: @23 = (@23+@24) */
  w23 += w24;
  /* #212: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #213: @16 = (@16-@23) */
  w16 -= w23;
  /* #214: @23 = @8[1] */
  for (rr=(&w23), cs=w08+1; cs!=w08+2; cs+=1) *rr++ = *cs;
  /* #215: @24 = (@23*@3) */
  w24  = (w23*w03);
  /* #216: @7 = @8[0] */
  for (rr=(&w07), cs=w08+0; cs!=w08+1; cs+=1) *rr++ = *cs;
  /* #217: @26 = (@7*@17) */
  w26  = (w07*w17);
  /* #218: @24 = (@24-@26) */
  w24 -= w26;
  /* #219: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #220: @26 = (@23*@17) */
  w26  = (w23*w17);
  /* #221: @25 = (@7*@3) */
  w25  = (w07*w03);
  /* #222: @26 = (@26+@25) */
  w26 += w25;
  /* #223: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #224: @4 = horzcat(@16, @24, @26) */
  rr=w04;
  *rr++ = w16;
  *rr++ = w24;
  *rr++ = w26;
  /* #225: @4 = @4' */
  /* #226: @16 = (@23*@3) */
  w16  = (w23*w03);
  /* #227: @24 = (@7*@17) */
  w24  = (w07*w17);
  /* #228: @16 = (@16+@24) */
  w16 += w24;
  /* #229: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #230: @24 = 1 */
  w24 = 1.;
  /* #231: @26 = sq(@23) */
  w26 = casadi_sq( w23 );
  /* #232: @25 = sq(@17) */
  w25 = casadi_sq( w17 );
  /* #233: @26 = (@26+@25) */
  w26 += w25;
  /* #234: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #235: @24 = (@24-@26) */
  w24 -= w26;
  /* #236: @26 = (@3*@17) */
  w26  = (w03*w17);
  /* #237: @25 = (@7*@23) */
  w25  = (w07*w23);
  /* #238: @26 = (@26-@25) */
  w26 -= w25;
  /* #239: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #240: @18 = horzcat(@16, @24, @26) */
  rr=w18;
  *rr++ = w16;
  *rr++ = w24;
  *rr++ = w26;
  /* #241: @18 = @18' */
  /* #242: @16 = (@23*@17) */
  w16  = (w23*w17);
  /* #243: @24 = (@7*@3) */
  w24  = (w07*w03);
  /* #244: @16 = (@16-@24) */
  w16 -= w24;
  /* #245: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #246: @17 = (@3*@17) */
  w17  = (w03*w17);
  /* #247: @7 = (@7*@23) */
  w07 *= w23;
  /* #248: @17 = (@17+@7) */
  w17 += w07;
  /* #249: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #250: @7 = 1 */
  w07 = 1.;
  /* #251: @23 = sq(@23) */
  w23 = casadi_sq( w23 );
  /* #252: @3 = sq(@3) */
  w03 = casadi_sq( w03 );
  /* #253: @23 = (@23+@3) */
  w23 += w03;
  /* #254: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #255: @7 = (@7-@23) */
  w07 -= w23;
  /* #256: @19 = horzcat(@16, @17, @7) */
  rr=w19;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w07;
  /* #257: @19 = @19' */
  /* #258: @22 = horzcat(@4, @18, @19) */
  rr=w22;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  /* #259: @21 = @22' */
  for (i=0, rr=w21, cs=w22; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #260: @16 = 0 */
  w16 = 0.;
  /* #261: @17 = 0 */
  w17 = 0.;
  /* #262: @7 = @2[2] */
  for (rr=(&w07), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #263: @15 = (@15*@7) */
  w15 *= w07;
  /* #264: @4 = vertcat(@16, @17, @15) */
  rr=w04;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w15;
  /* #265: @14 = mac(@21,@4,@14) */
  for (i=0, rr=w14; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w21+j, ct=w04+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #266: @4 = [0, 0, 9.81] */
  casadi_copy(casadi_c0, 3, w04);
  /* #267: @14 = (@14-@4) */
  for (i=0, rr=w14, cs=w04; i<3; ++i) (*rr++) -= (*cs++);
  /* #268: @16 = 0 */
  w16 = 0.;
  /* #269: @17 = 0 */
  w17 = 0.;
  /* #270: @15 = @0[2] */
  for (rr=(&w15), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #271: @5 = (@5*@15) */
  w05 *= w15;
  /* #272: @5 = (-@5) */
  w05 = (- w05 );
  /* #273: @0 = vertcat(@16, @17, @5) */
  rr=w00;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w05;
  /* #274: @14 = (@14+@0) */
  for (i=0, rr=w14, cs=w00; i<3; ++i) (*rr++) += (*cs++);
  /* #275: @16 = @14[0] */
  for (rr=(&w16), cs=w14+0; cs!=w14+1; cs+=1) *rr++ = *cs;
  /* #276: @16 = (@16/@6) */
  w16 /= w06;
  /* #277: @1 = (@1-@16) */
  w01 -= w16;
  /* #278: output[0][7] = @1 */
  if (res[0]) res[0][19] = w01;
  /* #279: @1 = 9.81 */
  w01 = 9.8100000000000005e+00;
  /* #280: @1 = (@1/@6) */
  w01 /= w06;
  /* #281: @16 = input[0][6] */
  w16 = arg[0] ? arg[0][18] : 0;
  /* #282: @1 = (@1*@16) */
  w01 *= w16;
  /* #283: @1 = (-@1) */
  w01 = (- w01 );
  /* #284: @16 = @14[1] */
  for (rr=(&w16), cs=w14+1; cs!=w14+2; cs+=1) *rr++ = *cs;
  /* #285: @16 = (@16/@6) */
  w16 /= w06;
  /* #286: @1 = (@1-@16) */
  w01 -= w16;
  /* #287: output[0][8] = @1 */
  if (res[0]) res[0][20] = w01;
  return 0;
}

/* quad_payload_dynamics_expl_ode_fun:(i0[21],i1[4],i2[11])->(o0[21]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr, *w00=w+105, *w01=w+108, *w02=w+112, *w03=w+115, *w04=w+118, w05, w06, w07, w08, *w09=w+126;
  casadi_real w10, w11, w12, *w13=w+150, *w14=w+161, *w15=w+168;
  const casadi_real **arg1=arg+3, *cs;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w00);
  /* #1: @1 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w01);
  /* #2: @2 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 3, w02);
  /* #3: @3 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w03);
  /* #4: @4 = input[0][4] */
  casadi_copy(arg[0] ? arg[0]+13 : 0, 4, w04);
  /* #5: @5 = input[0][5] */
  w05 = arg[0] ? arg[0][17] : 0;
  /* #6: @6 = input[0][6] */
  w06 = arg[0] ? arg[0][18] : 0;
  /* #7: @7 = input[0][7] */
  w07 = arg[0] ? arg[0][19] : 0;
  /* #8: @8 = input[0][8] */
  w08 = arg[0] ? arg[0][20] : 0;
  /* #9: @9 = vertcat(@0, @1, @2, @3, @4, @5, @6, @7, @8) */
  rr=w09;
  for (i=0, cs=w00; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w01; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w03; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w04; i<4; ++i) *rr++ = *cs++;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  /* #10: @1 = input[1][0] */
  casadi_copy(arg[1], 4, w01);
  /* #11: @5 = input[2][0] */
  w05 = arg[2] ? arg[2][0] : 0;
  /* #12: @6 = input[2][1] */
  w06 = arg[2] ? arg[2][1] : 0;
  /* #13: @7 = input[2][2] */
  w07 = arg[2] ? arg[2][2] : 0;
  /* #14: @8 = input[2][3] */
  w08 = arg[2] ? arg[2][3] : 0;
  /* #15: @10 = input[2][4] */
  w10 = arg[2] ? arg[2][4] : 0;
  /* #16: @11 = input[2][5] */
  w11 = arg[2] ? arg[2][5] : 0;
  /* #17: @12 = input[2][6] */
  w12 = arg[2] ? arg[2][6] : 0;
  /* #18: @4 = input[2][7] */
  casadi_copy(arg[2] ? arg[2]+7 : 0, 4, w04);
  /* #19: @13 = vertcat(@5, @6, @7, @8, @10, @11, @12, @4) */
  rr=w13;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  for (i=0, cs=w04; i<4; ++i) *rr++ = *cs++;
  /* #20: @14 = @13[:7] */
  for (rr=w14, cs=w13+0; cs!=w13+7; cs+=1) *rr++ = *cs;
  /* #21: @15 = x_dot(@9, @1, @14) */
  arg1[0]=w09;
  arg1[1]=w01;
  arg1[2]=w14;
  res1[0]=w15;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #22: output[0][0] = @15 */
  casadi_copy(w15, 21, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_payload_dynamics_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quad_payload_dynamics_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_payload_dynamics_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_payload_dynamics_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quad_payload_dynamics_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_payload_dynamics_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quad_payload_dynamics_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quad_payload_dynamics_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quad_payload_dynamics_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int quad_payload_dynamics_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quad_payload_dynamics_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_payload_dynamics_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_payload_dynamics_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_payload_dynamics_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_payload_dynamics_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quad_payload_dynamics_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 189;
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_payload_dynamics_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 189*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
