/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) load_cable_3_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {55, 1, 1};
static const casadi_int casadi_s1[3] = {12, 1, 1};
static const casadi_int casadi_s2[3] = {4, 1, 1};

static const casadi_real casadi_c0[3] = {0., 0., -9.8100000000000005e+00};
static const casadi_real casadi_c1[9] = 
  {5.9880239520958082e+02, 0., 0., 0., 5.9880239520958082e+02, 0., 0., 0.,
  3.0030030030030031e+02};
static const casadi_real casadi_c2[3] = {8.0000000000000002e-02, 0., 2.5000000000000001e-02};
static const casadi_real casadi_c3[3] = {-3.9999999999999980e-02, 6.9282032302755092e-02, 2.5000000000000001e-02};
static const casadi_real casadi_c4[3] = {-4.0000000000000036e-02, -6.9282032302755078e-02, 2.5000000000000001e-02};
static const casadi_real casadi_c5[9] = 
  {1.6700000000000000e-03, 0., 0., 0., 1.6700000000000000e-03, 0., 0., 0.,
  3.3300000000000001e-03};

static const casadi_real casadi_zeros[55] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0.};

/* load_cable_3_expl_ode_fun:(i0[55],i1[12],i2[4])->(o0[55]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w01=w+58, w02, *w03=w+62, *w04=w+65, w05, *w06=w+69, *w07=w+72, w08, *w09=w+76, w10, w11;
  casadi_real w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, *w23=w+92;
  casadi_real w25, w26, w27, w28, *w29=w+109, *w30=w+112;
  const casadi_real *cs, *ct, *wr00, *wr01, *wr03, *wr06, *wr07, *wr24, *wr30, *wr31;
  /* #0: @0 = input[0][0] */
  wr00 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = @0[3:6] */
  wr01 = wr00+3;
  /* #2: output[0][0] = @1 */
  casadi_copy(wr01, 3, res[0]);
  /* #3: @1 = [0, 0, -9.81] */
  casadi_copy(casadi_c0, 3, w01);
  /* #4: @2 = @0[25] */
  w02 = wr00[25];
  /* #5: @3 = @0[13:16] */
  wr03 = wr00+13;
  /* #6: @4 = (@2*@3) */
  for (i=0, rr=w04, cs=wr03; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #7: @5 = @0[39] */
  w05 = wr00[39];
  /* #8: @6 = @0[27:30] */
  wr06 = wr00+27;
  /* #9: @7 = (@5*@6) */
  for (i=0, rr=w07, cs=wr06; i<3; ++i) (*rr++)  = (w05*(*cs++));
  /* #10: @4 = (@4+@7) */
  for (i=0, rr=w04, cs=w07; i<3; ++i) (*rr++) += (*cs++);
  /* #11: @8 = @0[53] */
  w08 = wr00[53];
  /* #12: @7 = @0[41:44] */
  wr07 = wr00+41;
  /* #13: @9 = (@8*@7) */
  for (i=0, rr=w09, cs=wr07; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #14: @4 = (@4+@9) */
  for (i=0, rr=w04, cs=w09; i<3; ++i) (*rr++) += (*cs++);
  /* #15: @10 = 0.4 */
  w10 = 4.0000000000000002e-01;
  /* #16: @4 = (@4/@10) */
  for (i=0, rr=w04; i<3; ++i) (*rr++) /= w10;
  /* #17: @1 = (@1-@4) */
  for (i=0, rr=w01, cs=w04; i<3; ++i) (*rr++) -= (*cs++);
  /* #18: output[0][1] = @1 */
  if (res[0]) casadi_copy(w01, 3, res[0]+3);
  /* #19: @10 = 0.5 */
  w10 = 5.0000000000000000e-01;
  /* #20: @11 = @0[7] */
  w11 = wr00[7];
  /* #21: @12 = @0[10] */
  w12 = wr00[10];
  /* #22: @13 = (@11*@12) */
  w13  = (w11*w12);
  /* #23: @13 = (-@13) */
  w13 = (- w13 );
  /* #24: @14 = @0[8] */
  w14 = wr00[8];
  /* #25: @15 = @0[11] */
  w15 = wr00[11];
  /* #26: @16 = (@14*@15) */
  w16  = (w14*w15);
  /* #27: @13 = (@13-@16) */
  w13 -= w16;
  /* #28: @16 = @0[9] */
  w16 = wr00[9];
  /* #29: @17 = @0[12] */
  w17 = wr00[12];
  /* #30: @18 = (@16*@17) */
  w18  = (w16*w17);
  /* #31: @13 = (@13-@18) */
  w13 -= w18;
  /* #32: @18 = @0[6] */
  w18 = wr00[6];
  /* #33: @19 = (@18*@12) */
  w19  = (w18*w12);
  /* #34: @20 = (@14*@17) */
  w20  = (w14*w17);
  /* #35: @19 = (@19+@20) */
  w19 += w20;
  /* #36: @20 = (@16*@15) */
  w20  = (w16*w15);
  /* #37: @19 = (@19-@20) */
  w19 -= w20;
  /* #38: @20 = (@18*@15) */
  w20  = (w18*w15);
  /* #39: @21 = (@11*@17) */
  w21  = (w11*w17);
  /* #40: @20 = (@20-@21) */
  w20 -= w21;
  /* #41: @21 = (@16*@12) */
  w21  = (w16*w12);
  /* #42: @20 = (@20+@21) */
  w20 += w21;
  /* #43: @21 = (@18*@17) */
  w21  = (w18*w17);
  /* #44: @22 = (@11*@15) */
  w22  = (w11*w15);
  /* #45: @21 = (@21+@22) */
  w21 += w22;
  /* #46: @22 = (@14*@12) */
  w22  = (w14*w12);
  /* #47: @21 = (@21-@22) */
  w21 -= w22;
  /* #48: @23 = vertcat(@13, @19, @20, @21) */
  rr=w23;
  *rr++ = w13;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  /* #49: @23 = (@10*@23) */
  for (i=0, rr=w23, cs=w23; i<4; ++i) (*rr++)  = (w10*(*cs++));
  /* #50: output[0][2] = @23 */
  if (res[0]) casadi_copy(w23, 4, res[0]+6);
  /* #51: @1 = zeros(3x1) */
  casadi_clear(w01, 3);
  /* #52: @24 = 
  [[598.802, 0, 0], 
   [0, 598.802, 0], 
   [0, 0, 300.3]] */
  wr24 = casadi_c1;
  /* #53: @10 = 1 */
  w10 = 1.;
  /* #54: @13 = sq(@14) */
  w13 = casadi_sq( w14 );
  /* #55: @19 = sq(@16) */
  w19 = casadi_sq( w16 );
  /* #56: @20 = (@13+@19) */
  w20  = (w13+w19);
  /* #57: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #58: @20 = (@10-@20) */
  w20  = (w10-w20);
  /* #59: @21 = (@11*@14) */
  w21  = (w11*w14);
  /* #60: @22 = (@18*@16) */
  w22  = (w18*w16);
  /* #61: @25 = (@21-@22) */
  w25  = (w21-w22);
  /* #62: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #63: @26 = (@11*@16) */
  w26  = (w11*w16);
  /* #64: @27 = (@18*@14) */
  w27  = (w18*w14);
  /* #65: @28 = (@26+@27) */
  w28  = (w26+w27);
  /* #66: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #67: @4 = horzcat(@20, @25, @28) */
  rr=w04;
  *rr++ = w20;
  *rr++ = w25;
  *rr++ = w28;
  /* #68: @4 = @4' */
  /* #69: @21 = (@21+@22) */
  w21 += w22;
  /* #70: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #71: @22 = sq(@11) */
  w22 = casadi_sq( w11 );
  /* #72: @19 = (@22+@19) */
  w19  = (w22+w19);
  /* #73: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #74: @19 = (@10-@19) */
  w19  = (w10-w19);
  /* #75: @14 = (@14*@16) */
  w14 *= w16;
  /* #76: @18 = (@18*@11) */
  w18 *= w11;
  /* #77: @11 = (@14-@18) */
  w11  = (w14-w18);
  /* #78: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #79: @9 = horzcat(@21, @19, @11) */
  rr=w09;
  *rr++ = w21;
  *rr++ = w19;
  *rr++ = w11;
  /* #80: @9 = @9' */
  /* #81: @26 = (@26-@27) */
  w26 -= w27;
  /* #82: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #83: @14 = (@14+@18) */
  w14 += w18;
  /* #84: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #85: @22 = (@22+@13) */
  w22 += w13;
  /* #86: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #87: @10 = (@10-@22) */
  w10 -= w22;
  /* #88: @29 = horzcat(@26, @14, @10) */
  rr=w29;
  *rr++ = w26;
  *rr++ = w14;
  *rr++ = w10;
  /* #89: @29 = @29' */
  /* #90: @30 = horzcat(@4, @9, @29) */
  rr=w30;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w09; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<3; ++i) *rr++ = *cs++;
  /* #91: @4 = mac(@30,@3,@1) */
  casadi_copy(w01, 3, w04);
  for (i=0, rr=w04; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w30+j, ct=wr03+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #92: @26 = @4[1] */
  for (rr=(&w26), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #93: @3 = [0.08, 0, 0.025] */
  casadi_copy(casadi_c2, 3, w03);
  /* #94: @14 = @3[2] */
  for (rr=(&w14), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #95: @10 = (@26*@14) */
  w10  = (w26*w14);
  /* #96: @22 = @4[2] */
  for (rr=(&w22), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #97: @13 = @3[1] */
  for (rr=(&w13), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #98: @18 = (@22*@13) */
  w18  = (w22*w13);
  /* #99: @10 = (@10-@18) */
  w10 -= w18;
  /* #100: @18 = @3[0] */
  for (rr=(&w18), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #101: @22 = (@22*@18) */
  w22 *= w18;
  /* #102: @27 = @4[0] */
  for (rr=(&w27), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #103: @14 = (@27*@14) */
  w14  = (w27*w14);
  /* #104: @22 = (@22-@14) */
  w22 -= w14;
  /* #105: @27 = (@27*@13) */
  w27 *= w13;
  /* #106: @26 = (@26*@18) */
  w26 *= w18;
  /* #107: @27 = (@27-@26) */
  w27 -= w26;
  /* #108: @4 = vertcat(@10, @22, @27) */
  rr=w04;
  *rr++ = w10;
  *rr++ = w22;
  *rr++ = w27;
  /* #109: @4 = (@2*@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #110: @3 = mac(@30,@6,@1) */
  casadi_copy(w01, 3, w03);
  for (i=0, rr=w03; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w30+j, ct=wr06+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #111: @2 = @3[1] */
  for (rr=(&w02), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #112: @6 = [-0.04, 0.069282, 0.025] */
  casadi_copy(casadi_c3, 3, w06);
  /* #113: @10 = @6[2] */
  for (rr=(&w10), cs=w06+2; cs!=w06+3; cs+=1) *rr++ = *cs;
  /* #114: @22 = (@2*@10) */
  w22  = (w02*w10);
  /* #115: @27 = @3[2] */
  for (rr=(&w27), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #116: @26 = @6[1] */
  for (rr=(&w26), cs=w06+1; cs!=w06+2; cs+=1) *rr++ = *cs;
  /* #117: @18 = (@27*@26) */
  w18  = (w27*w26);
  /* #118: @22 = (@22-@18) */
  w22 -= w18;
  /* #119: @18 = @6[0] */
  for (rr=(&w18), cs=w06+0; cs!=w06+1; cs+=1) *rr++ = *cs;
  /* #120: @27 = (@27*@18) */
  w27 *= w18;
  /* #121: @13 = @3[0] */
  for (rr=(&w13), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #122: @10 = (@13*@10) */
  w10  = (w13*w10);
  /* #123: @27 = (@27-@10) */
  w27 -= w10;
  /* #124: @13 = (@13*@26) */
  w13 *= w26;
  /* #125: @2 = (@2*@18) */
  w02 *= w18;
  /* #126: @13 = (@13-@2) */
  w13 -= w02;
  /* #127: @3 = vertcat(@22, @27, @13) */
  rr=w03;
  *rr++ = w22;
  *rr++ = w27;
  *rr++ = w13;
  /* #128: @3 = (@5*@3) */
  for (i=0, rr=w03, cs=w03; i<3; ++i) (*rr++)  = (w05*(*cs++));
  /* #129: @4 = (@4+@3) */
  for (i=0, rr=w04, cs=w03; i<3; ++i) (*rr++) += (*cs++);
  /* #130: @3 = mac(@30,@7,@1) */
  casadi_copy(w01, 3, w03);
  for (i=0, rr=w03; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w30+j, ct=wr07+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #131: @5 = @3[1] */
  for (rr=(&w05), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #132: @7 = [-0.04, -0.069282, 0.025] */
  casadi_copy(casadi_c4, 3, w07);
  /* #133: @22 = @7[2] */
  for (rr=(&w22), cs=w07+2; cs!=w07+3; cs+=1) *rr++ = *cs;
  /* #134: @27 = (@5*@22) */
  w27  = (w05*w22);
  /* #135: @13 = @3[2] */
  for (rr=(&w13), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #136: @2 = @7[1] */
  for (rr=(&w02), cs=w07+1; cs!=w07+2; cs+=1) *rr++ = *cs;
  /* #137: @18 = (@13*@2) */
  w18  = (w13*w02);
  /* #138: @27 = (@27-@18) */
  w27 -= w18;
  /* #139: @18 = @7[0] */
  for (rr=(&w18), cs=w07+0; cs!=w07+1; cs+=1) *rr++ = *cs;
  /* #140: @13 = (@13*@18) */
  w13 *= w18;
  /* #141: @26 = @3[0] */
  for (rr=(&w26), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #142: @22 = (@26*@22) */
  w22  = (w26*w22);
  /* #143: @13 = (@13-@22) */
  w13 -= w22;
  /* #144: @26 = (@26*@2) */
  w26 *= w02;
  /* #145: @5 = (@5*@18) */
  w05 *= w18;
  /* #146: @26 = (@26-@5) */
  w26 -= w05;
  /* #147: @3 = vertcat(@27, @13, @26) */
  rr=w03;
  *rr++ = w27;
  *rr++ = w13;
  *rr++ = w26;
  /* #148: @3 = (@8*@3) */
  for (i=0, rr=w03, cs=w03; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #149: @4 = (@4+@3) */
  for (i=0, rr=w04, cs=w03; i<3; ++i) (*rr++) += (*cs++);
  /* #150: @30 = 
  [[0.00167, 0, 0], 
   [0, 0.00167, 0], 
   [0, 0, 0.00333]] */
  wr30 = casadi_c5;
  /* #151: @3 = @0[10:13] */
  wr03 = wr00+10;
  /* #152: @7 = mac(@30,@3,@1) */
  casadi_copy(w01, 3, w07);
  for (i=0, rr=w07; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr30+j, ct=wr03+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #153: @8 = @7[2] */
  for (rr=(&w08), cs=w07+2; cs!=w07+3; cs+=1) *rr++ = *cs;
  /* #154: @27 = (@15*@8) */
  w27  = (w15*w08);
  /* #155: @13 = @7[1] */
  for (rr=(&w13), cs=w07+1; cs!=w07+2; cs+=1) *rr++ = *cs;
  /* #156: @26 = (@17*@13) */
  w26  = (w17*w13);
  /* #157: @27 = (@27-@26) */
  w27 -= w26;
  /* #158: @26 = @7[0] */
  for (rr=(&w26), cs=w07+0; cs!=w07+1; cs+=1) *rr++ = *cs;
  /* #159: @17 = (@17*@26) */
  w17 *= w26;
  /* #160: @8 = (@12*@8) */
  w08  = (w12*w08);
  /* #161: @17 = (@17-@8) */
  w17 -= w08;
  /* #162: @12 = (@12*@13) */
  w12 *= w13;
  /* #163: @15 = (@15*@26) */
  w15 *= w26;
  /* #164: @12 = (@12-@15) */
  w12 -= w15;
  /* #165: @7 = vertcat(@27, @17, @12) */
  rr=w07;
  *rr++ = w27;
  *rr++ = w17;
  *rr++ = w12;
  /* #166: @4 = (@4-@7) */
  for (i=0, rr=w04, cs=w07; i<3; ++i) (*rr++) -= (*cs++);
  /* #167: @1 = mac(@24,@4,@1) */
  for (i=0, rr=w01; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr24+j, ct=w04+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #168: output[0][3] = @1 */
  if (res[0]) casadi_copy(w01, 3, res[0]+10);
  /* #169: @27 = @0[17] */
  w27 = wr00[17];
  /* #170: @17 = @0[15] */
  w17 = wr00[15];
  /* #171: @12 = (@27*@17) */
  w12  = (w27*w17);
  /* #172: @15 = @0[18] */
  w15 = wr00[18];
  /* #173: @26 = @0[14] */
  w26 = wr00[14];
  /* #174: @13 = (@15*@26) */
  w13  = (w15*w26);
  /* #175: @12 = (@12-@13) */
  w12 -= w13;
  /* #176: output[0][4] = @12 */
  if (res[0]) res[0][13] = w12;
  /* #177: @12 = @0[13] */
  w12 = wr00[13];
  /* #178: @15 = (@15*@12) */
  w15 *= w12;
  /* #179: @13 = @0[16] */
  w13 = wr00[16];
  /* #180: @17 = (@13*@17) */
  w17  = (w13*w17);
  /* #181: @15 = (@15-@17) */
  w15 -= w17;
  /* #182: output[0][5] = @15 */
  if (res[0]) res[0][14] = w15;
  /* #183: @13 = (@13*@26) */
  w13 *= w26;
  /* #184: @27 = (@27*@12) */
  w27 *= w12;
  /* #185: @13 = (@13-@27) */
  w13 -= w27;
  /* #186: output[0][6] = @13 */
  if (res[0]) res[0][15] = w13;
  /* #187: @1 = @0[19:22] */
  wr01 = wr00+19;
  /* #188: output[0][7] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+16);
  /* #189: @1 = @0[22:25] */
  wr01 = wr00+22;
  /* #190: output[0][8] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+19);
  /* #191: @31 = input[1][0] */
  wr31 = arg[1] ? arg[1] : casadi_zeros;
  /* #192: @1 = @31[:3] */
  wr01 = wr31+0;
  /* #193: output[0][9] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+22);
  /* #194: @13 = @0[26] */
  w13 = wr00[26];
  /* #195: output[0][10] = @13 */
  if (res[0]) res[0][25] = w13;
  /* #196: @13 = @31[3] */
  w13 = wr31[3];
  /* #197: output[0][11] = @13 */
  if (res[0]) res[0][26] = w13;
  /* #198: @13 = @0[31] */
  w13 = wr00[31];
  /* #199: @27 = @0[29] */
  w27 = wr00[29];
  /* #200: @12 = (@13*@27) */
  w12  = (w13*w27);
  /* #201: @26 = @0[32] */
  w26 = wr00[32];
  /* #202: @15 = @0[28] */
  w15 = wr00[28];
  /* #203: @17 = (@26*@15) */
  w17  = (w26*w15);
  /* #204: @12 = (@12-@17) */
  w12 -= w17;
  /* #205: output[0][12] = @12 */
  if (res[0]) res[0][27] = w12;
  /* #206: @12 = @0[27] */
  w12 = wr00[27];
  /* #207: @26 = (@26*@12) */
  w26 *= w12;
  /* #208: @17 = @0[30] */
  w17 = wr00[30];
  /* #209: @27 = (@17*@27) */
  w27  = (w17*w27);
  /* #210: @26 = (@26-@27) */
  w26 -= w27;
  /* #211: output[0][13] = @26 */
  if (res[0]) res[0][28] = w26;
  /* #212: @17 = (@17*@15) */
  w17 *= w15;
  /* #213: @13 = (@13*@12) */
  w13 *= w12;
  /* #214: @17 = (@17-@13) */
  w17 -= w13;
  /* #215: output[0][14] = @17 */
  if (res[0]) res[0][29] = w17;
  /* #216: @1 = @0[33:36] */
  wr01 = wr00+33;
  /* #217: output[0][15] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+30);
  /* #218: @1 = @0[36:39] */
  wr01 = wr00+36;
  /* #219: output[0][16] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+33);
  /* #220: @1 = @31[4:7] */
  wr01 = wr31+4;
  /* #221: output[0][17] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+36);
  /* #222: @17 = @0[40] */
  w17 = wr00[40];
  /* #223: output[0][18] = @17 */
  if (res[0]) res[0][39] = w17;
  /* #224: @17 = @31[7] */
  w17 = wr31[7];
  /* #225: output[0][19] = @17 */
  if (res[0]) res[0][40] = w17;
  /* #226: @17 = @0[45] */
  w17 = wr00[45];
  /* #227: @13 = @0[43] */
  w13 = wr00[43];
  /* #228: @12 = (@17*@13) */
  w12  = (w17*w13);
  /* #229: @15 = @0[46] */
  w15 = wr00[46];
  /* #230: @26 = @0[42] */
  w26 = wr00[42];
  /* #231: @27 = (@15*@26) */
  w27  = (w15*w26);
  /* #232: @12 = (@12-@27) */
  w12 -= w27;
  /* #233: output[0][20] = @12 */
  if (res[0]) res[0][41] = w12;
  /* #234: @12 = @0[41] */
  w12 = wr00[41];
  /* #235: @15 = (@15*@12) */
  w15 *= w12;
  /* #236: @27 = @0[44] */
  w27 = wr00[44];
  /* #237: @13 = (@27*@13) */
  w13  = (w27*w13);
  /* #238: @15 = (@15-@13) */
  w15 -= w13;
  /* #239: output[0][21] = @15 */
  if (res[0]) res[0][42] = w15;
  /* #240: @27 = (@27*@26) */
  w27 *= w26;
  /* #241: @17 = (@17*@12) */
  w17 *= w12;
  /* #242: @27 = (@27-@17) */
  w27 -= w17;
  /* #243: output[0][22] = @27 */
  if (res[0]) res[0][43] = w27;
  /* #244: @1 = @0[47:50] */
  wr01 = wr00+47;
  /* #245: output[0][23] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+44);
  /* #246: @1 = @0[50:53] */
  wr01 = wr00+50;
  /* #247: output[0][24] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+47);
  /* #248: @1 = @31[8:11] */
  wr01 = wr31+8;
  /* #249: output[0][25] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+50);
  /* #250: @27 = @0[54] */
  w27 = wr00[54];
  /* #251: output[0][26] = @27 */
  if (res[0]) res[0][53] = w27;
  /* #252: @27 = @31[11] */
  w27 = wr31[11];
  /* #253: output[0][27] = @27 */
  if (res[0]) res[0][54] = w27;
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_3_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int load_cable_3_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_3_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void load_cable_3_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int load_cable_3_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void load_cable_3_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void load_cable_3_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void load_cable_3_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int load_cable_3_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int load_cable_3_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real load_cable_3_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* load_cable_3_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* load_cable_3_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* load_cable_3_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* load_cable_3_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int load_cable_3_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 133;
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_3_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 133*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
