/drone_model_3:
  ros__parameters:
    frame_prefix: ''
    ignore_timestamp: false
    publish_frequency: 20.0
    qos_overrides:
      /clock:
        subscription:
          depth: 1
          durability: volatile
          history: keep_last
          reliability: best_effort
      /joint_states:
        subscription:
          depth: 5
          history: keep_last
          reliability: best_effort
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf:
        publisher:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf_static:
        publisher:
          depth: 1
          history: keep_last
          reliability: reliable
    robot_description: "<?xml version=\"1.0\"?>\n<robot name=\"tbs_sourceone_v5\"\
      >\n  <link name=\"drone_3_mocap\">\n    <visual>\n      <origin xyz=\"0 0 -0.02\"\
      \ rpy=\"0 0 1.57\"/>\n      <geometry>\n        <mesh filename=\"package://drone_visualisation/meshes/tbs_sourceone_v5.stl\"\
      \n              scale=\"0.001 0.001 0.001\"/>\n      </geometry>\n      <material\
      \ name=\"carbon\"><color rgba=\"0.84 0.15 0.16 0.9\"/></material>\n    </visual>\n\
      \    <collision>\n      <origin xyz=\"0 0 -0.02\" rpy=\"0 0 1.57\"/>\n     \
      \ <geometry>\n        <mesh filename=\"package://drone_visualisation/meshes/tbs_sourceone_v5.stl\"\
      \n              scale=\"0.001 0.001 0.001\"/>\n      </geometry>\n    </collision>\n\
      \  </link>\n</robot>"
    use_sim_time: true

