/magnet_tip_publisher:
  ros__parameters:
    drone_index: -1
    frame_id: map
    magnet_index: 0
    magnet_tip_topic: /magnet_tip_pose
    use_sim_time: true
    warn_throttle_s: 2.0
    x3_link_poses_are_relative: true
    x3_pose_topic: /model/x3_drone3/pose

