/motor_bridge_1:
  ros__parameters:
    config_file: ''
    lazy: false
    qos_overrides:
      /clock:
        subscription:
          depth: 1
          durability: volatile
          history: keep_last
          reliability: best_effort
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
      /x3_drone1/gazebo/command/motor_speed:
        subscription:
          depth: 10
          history: keep_last
          reliability: reliable
    subscription_heartbeat: 1000
    use_sim_time: true

