/sim_telemetry:
  ros__parameters:
    battery_mah_used: 0
    battery_voltage: 16.4
    mode: SIM
    num_drones: 4
    rate_hz: 2.0
    rssi: -55
    use_sim_time: true
    voltage_drone_0: 16.4
    voltage_drone_1: 16.4
    voltage_drone_2: 16.4
    voltage_drone_3: 16.4

