/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) load_cable_2_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {41, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {4, 1, 1};

static const casadi_real casadi_c0[3] = {0., 0., -9.8100000000000005e+00};
static const casadi_real casadi_c1[9] = 
  {5.9880239520958082e+02, 0., 0., 0., 5.9880239520958082e+02, 0., 0., 0.,
  3.0030030030030031e+02};
static const casadi_real casadi_c2[3] = {8.0000000000000002e-02, 0., 2.5000000000000001e-02};
static const casadi_real casadi_c3[3] = {-8.0000000000000002e-02, 9.7971743931788255e-18, 2.5000000000000001e-02};
static const casadi_real casadi_c4[9] = 
  {1.6700000000000000e-03, 0., 0., 0., 1.6700000000000000e-03, 0., 0., 0.,
  3.3300000000000001e-03};

static const casadi_real casadi_zeros[41] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* load_cable_2_expl_ode_fun:(i0[41],i1[8],i2[4])->(o0[41]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w01=w+44, w02, *w03=w+48, *w04=w+51, w05, *w06=w+55, *w07=w+58, w08, w09, w10, w11;
  casadi_real w12, w13, w14, w15, w16, w17, w18, w19, w20, *w21=w+74, w23, w24;
  casadi_real w25, w26, *w27=w+91, *w28=w+94;
  const casadi_real *cs, *ct, *wr00, *wr01, *wr03, *wr06, *wr22, *wr28, *wr29;
  /* #0: @0 = input[0][0] */
  wr00 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = @0[3:6] */
  wr01 = wr00+3;
  /* #2: output[0][0] = @1 */
  casadi_copy(wr01, 3, res[0]);
  /* #3: @1 = [0, 0, -9.81] */
  casadi_copy(casadi_c0, 3, w01);
  /* #4: @2 = @0[25] */
  w02 = wr00[25];
  /* #5: @3 = @0[13:16] */
  wr03 = wr00+13;
  /* #6: @4 = (@2*@3) */
  for (i=0, rr=w04, cs=wr03; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #7: @5 = @0[39] */
  w05 = wr00[39];
  /* #8: @6 = @0[27:30] */
  wr06 = wr00+27;
  /* #9: @7 = (@5*@6) */
  for (i=0, rr=w07, cs=wr06; i<3; ++i) (*rr++)  = (w05*(*cs++));
  /* #10: @4 = (@4+@7) */
  for (i=0, rr=w04, cs=w07; i<3; ++i) (*rr++) += (*cs++);
  /* #11: @8 = 0.4 */
  w08 = 4.0000000000000002e-01;
  /* #12: @4 = (@4/@8) */
  for (i=0, rr=w04; i<3; ++i) (*rr++) /= w08;
  /* #13: @1 = (@1-@4) */
  for (i=0, rr=w01, cs=w04; i<3; ++i) (*rr++) -= (*cs++);
  /* #14: output[0][1] = @1 */
  if (res[0]) casadi_copy(w01, 3, res[0]+3);
  /* #15: @8 = 0.5 */
  w08 = 5.0000000000000000e-01;
  /* #16: @9 = @0[7] */
  w09 = wr00[7];
  /* #17: @10 = @0[10] */
  w10 = wr00[10];
  /* #18: @11 = (@9*@10) */
  w11  = (w09*w10);
  /* #19: @11 = (-@11) */
  w11 = (- w11 );
  /* #20: @12 = @0[8] */
  w12 = wr00[8];
  /* #21: @13 = @0[11] */
  w13 = wr00[11];
  /* #22: @14 = (@12*@13) */
  w14  = (w12*w13);
  /* #23: @11 = (@11-@14) */
  w11 -= w14;
  /* #24: @14 = @0[9] */
  w14 = wr00[9];
  /* #25: @15 = @0[12] */
  w15 = wr00[12];
  /* #26: @16 = (@14*@15) */
  w16  = (w14*w15);
  /* #27: @11 = (@11-@16) */
  w11 -= w16;
  /* #28: @16 = @0[6] */
  w16 = wr00[6];
  /* #29: @17 = (@16*@10) */
  w17  = (w16*w10);
  /* #30: @18 = (@12*@15) */
  w18  = (w12*w15);
  /* #31: @17 = (@17+@18) */
  w17 += w18;
  /* #32: @18 = (@14*@13) */
  w18  = (w14*w13);
  /* #33: @17 = (@17-@18) */
  w17 -= w18;
  /* #34: @18 = (@16*@13) */
  w18  = (w16*w13);
  /* #35: @19 = (@9*@15) */
  w19  = (w09*w15);
  /* #36: @18 = (@18-@19) */
  w18 -= w19;
  /* #37: @19 = (@14*@10) */
  w19  = (w14*w10);
  /* #38: @18 = (@18+@19) */
  w18 += w19;
  /* #39: @19 = (@16*@15) */
  w19  = (w16*w15);
  /* #40: @20 = (@9*@13) */
  w20  = (w09*w13);
  /* #41: @19 = (@19+@20) */
  w19 += w20;
  /* #42: @20 = (@12*@10) */
  w20  = (w12*w10);
  /* #43: @19 = (@19-@20) */
  w19 -= w20;
  /* #44: @21 = vertcat(@11, @17, @18, @19) */
  rr=w21;
  *rr++ = w11;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  /* #45: @21 = (@8*@21) */
  for (i=0, rr=w21, cs=w21; i<4; ++i) (*rr++)  = (w08*(*cs++));
  /* #46: output[0][2] = @21 */
  if (res[0]) casadi_copy(w21, 4, res[0]+6);
  /* #47: @1 = zeros(3x1) */
  casadi_clear(w01, 3);
  /* #48: @22 = 
  [[598.802, 0, 0], 
   [0, 598.802, 0], 
   [0, 0, 300.3]] */
  wr22 = casadi_c1;
  /* #49: @8 = 1 */
  w08 = 1.;
  /* #50: @11 = sq(@12) */
  w11 = casadi_sq( w12 );
  /* #51: @17 = sq(@14) */
  w17 = casadi_sq( w14 );
  /* #52: @18 = (@11+@17) */
  w18  = (w11+w17);
  /* #53: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #54: @18 = (@8-@18) */
  w18  = (w08-w18);
  /* #55: @19 = (@9*@12) */
  w19  = (w09*w12);
  /* #56: @20 = (@16*@14) */
  w20  = (w16*w14);
  /* #57: @23 = (@19-@20) */
  w23  = (w19-w20);
  /* #58: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #59: @24 = (@9*@14) */
  w24  = (w09*w14);
  /* #60: @25 = (@16*@12) */
  w25  = (w16*w12);
  /* #61: @26 = (@24+@25) */
  w26  = (w24+w25);
  /* #62: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #63: @4 = horzcat(@18, @23, @26) */
  rr=w04;
  *rr++ = w18;
  *rr++ = w23;
  *rr++ = w26;
  /* #64: @4 = @4' */
  /* #65: @19 = (@19+@20) */
  w19 += w20;
  /* #66: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #67: @20 = sq(@9) */
  w20 = casadi_sq( w09 );
  /* #68: @17 = (@20+@17) */
  w17  = (w20+w17);
  /* #69: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #70: @17 = (@8-@17) */
  w17  = (w08-w17);
  /* #71: @12 = (@12*@14) */
  w12 *= w14;
  /* #72: @16 = (@16*@9) */
  w16 *= w09;
  /* #73: @9 = (@12-@16) */
  w09  = (w12-w16);
  /* #74: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #75: @7 = horzcat(@19, @17, @9) */
  rr=w07;
  *rr++ = w19;
  *rr++ = w17;
  *rr++ = w09;
  /* #76: @7 = @7' */
  /* #77: @24 = (@24-@25) */
  w24 -= w25;
  /* #78: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #79: @12 = (@12+@16) */
  w12 += w16;
  /* #80: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #81: @20 = (@20+@11) */
  w20 += w11;
  /* #82: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #83: @8 = (@8-@20) */
  w08 -= w20;
  /* #84: @27 = horzcat(@24, @12, @8) */
  rr=w27;
  *rr++ = w24;
  *rr++ = w12;
  *rr++ = w08;
  /* #85: @27 = @27' */
  /* #86: @28 = horzcat(@4, @7, @27) */
  rr=w28;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w07; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<3; ++i) *rr++ = *cs++;
  /* #87: @4 = mac(@28,@3,@1) */
  casadi_copy(w01, 3, w04);
  for (i=0, rr=w04; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w28+j, ct=wr03+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #88: @24 = @4[1] */
  for (rr=(&w24), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #89: @3 = [0.08, 0, 0.025] */
  casadi_copy(casadi_c2, 3, w03);
  /* #90: @12 = @3[2] */
  for (rr=(&w12), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #91: @8 = (@24*@12) */
  w08  = (w24*w12);
  /* #92: @20 = @4[2] */
  for (rr=(&w20), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #93: @11 = @3[1] */
  for (rr=(&w11), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #94: @16 = (@20*@11) */
  w16  = (w20*w11);
  /* #95: @8 = (@8-@16) */
  w08 -= w16;
  /* #96: @16 = @3[0] */
  for (rr=(&w16), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #97: @20 = (@20*@16) */
  w20 *= w16;
  /* #98: @25 = @4[0] */
  for (rr=(&w25), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #99: @12 = (@25*@12) */
  w12  = (w25*w12);
  /* #100: @20 = (@20-@12) */
  w20 -= w12;
  /* #101: @25 = (@25*@11) */
  w25 *= w11;
  /* #102: @24 = (@24*@16) */
  w24 *= w16;
  /* #103: @25 = (@25-@24) */
  w25 -= w24;
  /* #104: @4 = vertcat(@8, @20, @25) */
  rr=w04;
  *rr++ = w08;
  *rr++ = w20;
  *rr++ = w25;
  /* #105: @4 = (@2*@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #106: @3 = mac(@28,@6,@1) */
  casadi_copy(w01, 3, w03);
  for (i=0, rr=w03; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w28+j, ct=wr06+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #107: @2 = @3[1] */
  for (rr=(&w02), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #108: @6 = [-0.08, 9.79717e-18, 0.025] */
  casadi_copy(casadi_c3, 3, w06);
  /* #109: @8 = @6[2] */
  for (rr=(&w08), cs=w06+2; cs!=w06+3; cs+=1) *rr++ = *cs;
  /* #110: @20 = (@2*@8) */
  w20  = (w02*w08);
  /* #111: @25 = @3[2] */
  for (rr=(&w25), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #112: @24 = @6[1] */
  for (rr=(&w24), cs=w06+1; cs!=w06+2; cs+=1) *rr++ = *cs;
  /* #113: @16 = (@25*@24) */
  w16  = (w25*w24);
  /* #114: @20 = (@20-@16) */
  w20 -= w16;
  /* #115: @16 = @6[0] */
  for (rr=(&w16), cs=w06+0; cs!=w06+1; cs+=1) *rr++ = *cs;
  /* #116: @25 = (@25*@16) */
  w25 *= w16;
  /* #117: @11 = @3[0] */
  for (rr=(&w11), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #118: @8 = (@11*@8) */
  w08  = (w11*w08);
  /* #119: @25 = (@25-@8) */
  w25 -= w08;
  /* #120: @11 = (@11*@24) */
  w11 *= w24;
  /* #121: @2 = (@2*@16) */
  w02 *= w16;
  /* #122: @11 = (@11-@2) */
  w11 -= w02;
  /* #123: @3 = vertcat(@20, @25, @11) */
  rr=w03;
  *rr++ = w20;
  *rr++ = w25;
  *rr++ = w11;
  /* #124: @3 = (@5*@3) */
  for (i=0, rr=w03, cs=w03; i<3; ++i) (*rr++)  = (w05*(*cs++));
  /* #125: @4 = (@4+@3) */
  for (i=0, rr=w04, cs=w03; i<3; ++i) (*rr++) += (*cs++);
  /* #126: @28 = 
  [[0.00167, 0, 0], 
   [0, 0.00167, 0], 
   [0, 0, 0.00333]] */
  wr28 = casadi_c4;
  /* #127: @3 = @0[10:13] */
  wr03 = wr00+10;
  /* #128: @6 = mac(@28,@3,@1) */
  casadi_copy(w01, 3, w06);
  for (i=0, rr=w06; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr28+j, ct=wr03+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #129: @5 = @6[2] */
  for (rr=(&w05), cs=w06+2; cs!=w06+3; cs+=1) *rr++ = *cs;
  /* #130: @20 = (@13*@5) */
  w20  = (w13*w05);
  /* #131: @25 = @6[1] */
  for (rr=(&w25), cs=w06+1; cs!=w06+2; cs+=1) *rr++ = *cs;
  /* #132: @11 = (@15*@25) */
  w11  = (w15*w25);
  /* #133: @20 = (@20-@11) */
  w20 -= w11;
  /* #134: @11 = @6[0] */
  for (rr=(&w11), cs=w06+0; cs!=w06+1; cs+=1) *rr++ = *cs;
  /* #135: @15 = (@15*@11) */
  w15 *= w11;
  /* #136: @5 = (@10*@5) */
  w05  = (w10*w05);
  /* #137: @15 = (@15-@5) */
  w15 -= w05;
  /* #138: @10 = (@10*@25) */
  w10 *= w25;
  /* #139: @13 = (@13*@11) */
  w13 *= w11;
  /* #140: @10 = (@10-@13) */
  w10 -= w13;
  /* #141: @6 = vertcat(@20, @15, @10) */
  rr=w06;
  *rr++ = w20;
  *rr++ = w15;
  *rr++ = w10;
  /* #142: @4 = (@4-@6) */
  for (i=0, rr=w04, cs=w06; i<3; ++i) (*rr++) -= (*cs++);
  /* #143: @1 = mac(@22,@4,@1) */
  for (i=0, rr=w01; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr22+j, ct=w04+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #144: output[0][3] = @1 */
  if (res[0]) casadi_copy(w01, 3, res[0]+10);
  /* #145: @20 = @0[17] */
  w20 = wr00[17];
  /* #146: @15 = @0[15] */
  w15 = wr00[15];
  /* #147: @10 = (@20*@15) */
  w10  = (w20*w15);
  /* #148: @13 = @0[18] */
  w13 = wr00[18];
  /* #149: @11 = @0[14] */
  w11 = wr00[14];
  /* #150: @25 = (@13*@11) */
  w25  = (w13*w11);
  /* #151: @10 = (@10-@25) */
  w10 -= w25;
  /* #152: output[0][4] = @10 */
  if (res[0]) res[0][13] = w10;
  /* #153: @10 = @0[13] */
  w10 = wr00[13];
  /* #154: @13 = (@13*@10) */
  w13 *= w10;
  /* #155: @25 = @0[16] */
  w25 = wr00[16];
  /* #156: @15 = (@25*@15) */
  w15  = (w25*w15);
  /* #157: @13 = (@13-@15) */
  w13 -= w15;
  /* #158: output[0][5] = @13 */
  if (res[0]) res[0][14] = w13;
  /* #159: @25 = (@25*@11) */
  w25 *= w11;
  /* #160: @20 = (@20*@10) */
  w20 *= w10;
  /* #161: @25 = (@25-@20) */
  w25 -= w20;
  /* #162: output[0][6] = @25 */
  if (res[0]) res[0][15] = w25;
  /* #163: @1 = @0[19:22] */
  wr01 = wr00+19;
  /* #164: output[0][7] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+16);
  /* #165: @1 = @0[22:25] */
  wr01 = wr00+22;
  /* #166: output[0][8] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+19);
  /* #167: @29 = input[1][0] */
  wr29 = arg[1] ? arg[1] : casadi_zeros;
  /* #168: @1 = @29[:3] */
  wr01 = wr29+0;
  /* #169: output[0][9] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+22);
  /* #170: @25 = @0[26] */
  w25 = wr00[26];
  /* #171: output[0][10] = @25 */
  if (res[0]) res[0][25] = w25;
  /* #172: @25 = @29[3] */
  w25 = wr29[3];
  /* #173: output[0][11] = @25 */
  if (res[0]) res[0][26] = w25;
  /* #174: @25 = @0[31] */
  w25 = wr00[31];
  /* #175: @20 = @0[29] */
  w20 = wr00[29];
  /* #176: @10 = (@25*@20) */
  w10  = (w25*w20);
  /* #177: @11 = @0[32] */
  w11 = wr00[32];
  /* #178: @13 = @0[28] */
  w13 = wr00[28];
  /* #179: @15 = (@11*@13) */
  w15  = (w11*w13);
  /* #180: @10 = (@10-@15) */
  w10 -= w15;
  /* #181: output[0][12] = @10 */
  if (res[0]) res[0][27] = w10;
  /* #182: @10 = @0[27] */
  w10 = wr00[27];
  /* #183: @11 = (@11*@10) */
  w11 *= w10;
  /* #184: @15 = @0[30] */
  w15 = wr00[30];
  /* #185: @20 = (@15*@20) */
  w20  = (w15*w20);
  /* #186: @11 = (@11-@20) */
  w11 -= w20;
  /* #187: output[0][13] = @11 */
  if (res[0]) res[0][28] = w11;
  /* #188: @15 = (@15*@13) */
  w15 *= w13;
  /* #189: @25 = (@25*@10) */
  w25 *= w10;
  /* #190: @15 = (@15-@25) */
  w15 -= w25;
  /* #191: output[0][14] = @15 */
  if (res[0]) res[0][29] = w15;
  /* #192: @1 = @0[33:36] */
  wr01 = wr00+33;
  /* #193: output[0][15] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+30);
  /* #194: @1 = @0[36:39] */
  wr01 = wr00+36;
  /* #195: output[0][16] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+33);
  /* #196: @1 = @29[4:7] */
  wr01 = wr29+4;
  /* #197: output[0][17] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+36);
  /* #198: @15 = @0[40] */
  w15 = wr00[40];
  /* #199: output[0][18] = @15 */
  if (res[0]) res[0][39] = w15;
  /* #200: @15 = @29[7] */
  w15 = wr29[7];
  /* #201: output[0][19] = @15 */
  if (res[0]) res[0][40] = w15;
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_2_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int load_cable_2_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_2_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void load_cable_2_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int load_cable_2_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void load_cable_2_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void load_cable_2_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void load_cable_2_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int load_cable_2_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int load_cable_2_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real load_cable_2_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* load_cable_2_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* load_cable_2_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* load_cable_2_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* load_cable_2_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int load_cable_2_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 111;
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_2_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 111*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
