/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) load_cable_3_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

static const casadi_int casadi_s0[3] = {55, 1, 1};
static const casadi_int casadi_s1[3] = {12, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {4, 1, 1};
static const casadi_int casadi_s4[3] = {3, 1, 1};

static const casadi_real casadi_c0[3] = {0., 0., -9.8100000000000005e+00};
static const casadi_real casadi_c1[9] = 
  {5.9880239520958082e+02, 0., 0., 0., 5.9880239520958082e+02, 0., 0., 0.,
  3.0030030030030031e+02};
static const casadi_real casadi_c2[3] = {8.0000000000000002e-02, 0., 2.5000000000000001e-02};
static const casadi_real casadi_c3[3] = {-3.9999999999999980e-02, 6.9282032302755092e-02, 2.5000000000000001e-02};
static const casadi_real casadi_c4[3] = {-4.0000000000000036e-02, -6.9282032302755078e-02, 2.5000000000000001e-02};
static const casadi_real casadi_c5[9] = 
  {1.6700000000000000e-03, 0., 0., 0., 1.6700000000000000e-03, 0., 0., 0.,
  3.3300000000000001e-03};

static const casadi_real casadi_zeros[55] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0.};

/* load_cable_3_constr_h_fun:(i0[55],i1[12],i2[0],i3[4])->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+4, w03, *w04=w+63, *w05=w+66, w06, *w07=w+70, *w08=w+73, *w09=w+76, w10, *w11=w+80;
  casadi_real *w12=w+83, w13, *w14=w+87, w15, w16, w17, w18, w19, w20, w21, w22, w23;
  casadi_real w24, w25, w26, w27, *w28=w+103, *w29=w+106, *w30=w+109, *w31=w+112, *w32=w+121, w34, w35, w36;
  casadi_real w37;
  const casadi_real *cr, *cs, *ct, *wr02, *wr04, *wr07, *wr11, *wr31, *wr33;
  /* #0: @0 = 0.6 */
  w00 = 5.9999999999999998e-01;
  /* #1: @1 = [0, 0, -9.81] */
  casadi_copy(casadi_c0, 3, w01);
  /* #2: @2 = input[0][0] */
  wr02 = arg[0] ? arg[0] : casadi_zeros;
  /* #3: @3 = @2[25] */
  w03 = wr02[25];
  /* #4: @4 = @2[13:16] */
  wr04 = wr02+13;
  /* #5: @5 = (@3*@4) */
  for (i=0, rr=w05, cs=wr04; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #6: @6 = @2[39] */
  w06 = wr02[39];
  /* #7: @7 = @2[27:30] */
  wr07 = wr02+27;
  /* #8: @8 = (@6*@7) */
  for (i=0, rr=w08, cs=wr07; i<3; ++i) (*rr++)  = (w06*(*cs++));
  /* #9: @9 = (@5+@8) */
  for (i=0, rr=w09, cr=w05, cs=w08; i<3; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #10: @10 = @2[53] */
  w10 = wr02[53];
  /* #11: @11 = @2[41:44] */
  wr11 = wr02+41;
  /* #12: @12 = (@10*@11) */
  for (i=0, rr=w12, cs=wr11; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #13: @9 = (@9+@12) */
  for (i=0, rr=w09, cs=w12; i<3; ++i) (*rr++) += (*cs++);
  /* #14: @13 = 0.4 */
  w13 = 4.0000000000000002e-01;
  /* #15: @9 = (@9/@13) */
  for (i=0, rr=w09; i<3; ++i) (*rr++) /= w13;
  /* #16: @9 = (@1-@9) */
  for (i=0, rr=w09, cr=w01, cs=w09; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #17: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #18: @13 = 1 */
  w13 = 1.;
  /* #19: @15 = @2[8] */
  w15 = wr02[8];
  /* #20: @16 = sq(@15) */
  w16 = casadi_sq( w15 );
  /* #21: @17 = @2[9] */
  w17 = wr02[9];
  /* #22: @18 = sq(@17) */
  w18 = casadi_sq( w17 );
  /* #23: @19 = (@16+@18) */
  w19  = (w16+w18);
  /* #24: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #25: @19 = (@13-@19) */
  w19  = (w13-w19);
  /* #26: @20 = @2[7] */
  w20 = wr02[7];
  /* #27: @21 = (@20*@15) */
  w21  = (w20*w15);
  /* #28: @22 = @2[6] */
  w22 = wr02[6];
  /* #29: @23 = (@22*@17) */
  w23  = (w22*w17);
  /* #30: @24 = (@21-@23) */
  w24  = (w21-w23);
  /* #31: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #32: @25 = (@20*@17) */
  w25  = (w20*w17);
  /* #33: @26 = (@22*@15) */
  w26  = (w22*w15);
  /* #34: @27 = (@25+@26) */
  w27  = (w25+w26);
  /* #35: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #36: @28 = horzcat(@19, @24, @27) */
  rr=w28;
  *rr++ = w19;
  *rr++ = w24;
  *rr++ = w27;
  /* #37: @28 = @28' */
  /* #38: @21 = (@21+@23) */
  w21 += w23;
  /* #39: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #40: @23 = sq(@20) */
  w23 = casadi_sq( w20 );
  /* #41: @18 = (@23+@18) */
  w18  = (w23+w18);
  /* #42: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #43: @18 = (@13-@18) */
  w18  = (w13-w18);
  /* #44: @15 = (@15*@17) */
  w15 *= w17;
  /* #45: @22 = (@22*@20) */
  w22 *= w20;
  /* #46: @20 = (@15-@22) */
  w20  = (w15-w22);
  /* #47: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #48: @29 = horzcat(@21, @18, @20) */
  rr=w29;
  *rr++ = w21;
  *rr++ = w18;
  *rr++ = w20;
  /* #49: @29 = @29' */
  /* #50: @25 = (@25-@26) */
  w25 -= w26;
  /* #51: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #52: @15 = (@15+@22) */
  w15 += w22;
  /* #53: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #54: @23 = (@23+@16) */
  w23 += w16;
  /* #55: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #56: @13 = (@13-@23) */
  w13 -= w23;
  /* #57: @30 = horzcat(@25, @15, @13) */
  rr=w30;
  *rr++ = w25;
  *rr++ = w15;
  *rr++ = w13;
  /* #58: @30 = @30' */
  /* #59: @31 = horzcat(@28, @29, @30) */
  rr=w31;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<3; ++i) *rr++ = *cs++;
  /* #60: @32 = @31' */
  for (i=0, rr=w32, cs=w31; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #61: @33 = 
  [[598.802, 0, 0], 
   [0, 598.802, 0], 
   [0, 0, 300.3]] */
  wr33 = casadi_c1;
  /* #62: @28 = mac(@31,@4,@14) */
  casadi_copy(w14, 3, w28);
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w31+j, ct=wr04+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #63: @25 = @28[1] */
  for (rr=(&w25), cs=w28+1; cs!=w28+2; cs+=1) *rr++ = *cs;
  /* #64: @4 = [0.08, 0, 0.025] */
  casadi_copy(casadi_c2, 3, w04);
  /* #65: @15 = @4[2] */
  for (rr=(&w15), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #66: @13 = (@25*@15) */
  w13  = (w25*w15);
  /* #67: @23 = @28[2] */
  for (rr=(&w23), cs=w28+2; cs!=w28+3; cs+=1) *rr++ = *cs;
  /* #68: @16 = @4[1] */
  for (rr=(&w16), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #69: @22 = (@23*@16) */
  w22  = (w23*w16);
  /* #70: @13 = (@13-@22) */
  w13 -= w22;
  /* #71: @22 = @4[0] */
  for (rr=(&w22), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #72: @23 = (@23*@22) */
  w23 *= w22;
  /* #73: @26 = @28[0] */
  for (rr=(&w26), cs=w28+0; cs!=w28+1; cs+=1) *rr++ = *cs;
  /* #74: @21 = (@26*@15) */
  w21  = (w26*w15);
  /* #75: @23 = (@23-@21) */
  w23 -= w21;
  /* #76: @26 = (@26*@16) */
  w26 *= w16;
  /* #77: @25 = (@25*@22) */
  w25 *= w22;
  /* #78: @26 = (@26-@25) */
  w26 -= w25;
  /* #79: @28 = vertcat(@13, @23, @26) */
  rr=w28;
  *rr++ = w13;
  *rr++ = w23;
  *rr++ = w26;
  /* #80: @28 = (@3*@28) */
  for (i=0, rr=w28, cs=w28; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #81: @4 = mac(@31,@7,@14) */
  casadi_copy(w14, 3, w04);
  for (i=0, rr=w04; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w31+j, ct=wr07+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #82: @3 = @4[1] */
  for (rr=(&w03), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #83: @7 = [-0.04, 0.069282, 0.025] */
  casadi_copy(casadi_c3, 3, w07);
  /* #84: @13 = @7[2] */
  for (rr=(&w13), cs=w07+2; cs!=w07+3; cs+=1) *rr++ = *cs;
  /* #85: @23 = (@3*@13) */
  w23  = (w03*w13);
  /* #86: @26 = @4[2] */
  for (rr=(&w26), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #87: @25 = @7[1] */
  for (rr=(&w25), cs=w07+1; cs!=w07+2; cs+=1) *rr++ = *cs;
  /* #88: @21 = (@26*@25) */
  w21  = (w26*w25);
  /* #89: @23 = (@23-@21) */
  w23 -= w21;
  /* #90: @21 = @7[0] */
  for (rr=(&w21), cs=w07+0; cs!=w07+1; cs+=1) *rr++ = *cs;
  /* #91: @26 = (@26*@21) */
  w26 *= w21;
  /* #92: @18 = @4[0] */
  for (rr=(&w18), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #93: @20 = (@18*@13) */
  w20  = (w18*w13);
  /* #94: @26 = (@26-@20) */
  w26 -= w20;
  /* #95: @18 = (@18*@25) */
  w18 *= w25;
  /* #96: @3 = (@3*@21) */
  w03 *= w21;
  /* #97: @18 = (@18-@3) */
  w18 -= w03;
  /* #98: @4 = vertcat(@23, @26, @18) */
  rr=w04;
  *rr++ = w23;
  *rr++ = w26;
  *rr++ = w18;
  /* #99: @4 = (@6*@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) (*rr++)  = (w06*(*cs++));
  /* #100: @28 = (@28+@4) */
  for (i=0, rr=w28, cs=w04; i<3; ++i) (*rr++) += (*cs++);
  /* #101: @4 = mac(@31,@11,@14) */
  casadi_copy(w14, 3, w04);
  for (i=0, rr=w04; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w31+j, ct=wr11+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #102: @6 = @4[1] */
  for (rr=(&w06), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #103: @11 = [-0.04, -0.069282, 0.025] */
  casadi_copy(casadi_c4, 3, w11);
  /* #104: @23 = @11[2] */
  for (rr=(&w23), cs=w11+2; cs!=w11+3; cs+=1) *rr++ = *cs;
  /* #105: @26 = (@6*@23) */
  w26  = (w06*w23);
  /* #106: @18 = @4[2] */
  for (rr=(&w18), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #107: @3 = @11[1] */
  for (rr=(&w03), cs=w11+1; cs!=w11+2; cs+=1) *rr++ = *cs;
  /* #108: @20 = (@18*@3) */
  w20  = (w18*w03);
  /* #109: @26 = (@26-@20) */
  w26 -= w20;
  /* #110: @20 = @11[0] */
  for (rr=(&w20), cs=w11+0; cs!=w11+1; cs+=1) *rr++ = *cs;
  /* #111: @18 = (@18*@20) */
  w18 *= w20;
  /* #112: @17 = @4[0] */
  for (rr=(&w17), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #113: @19 = (@17*@23) */
  w19  = (w17*w23);
  /* #114: @18 = (@18-@19) */
  w18 -= w19;
  /* #115: @17 = (@17*@3) */
  w17 *= w03;
  /* #116: @6 = (@6*@20) */
  w06 *= w20;
  /* #117: @17 = (@17-@6) */
  w17 -= w06;
  /* #118: @4 = vertcat(@26, @18, @17) */
  rr=w04;
  *rr++ = w26;
  *rr++ = w18;
  *rr++ = w17;
  /* #119: @4 = (@10*@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #120: @28 = (@28+@4) */
  for (i=0, rr=w28, cs=w04; i<3; ++i) (*rr++) += (*cs++);
  /* #121: @10 = @2[11] */
  w10 = wr02[11];
  /* #122: @31 = 
  [[0.00167, 0, 0], 
   [0, 0.00167, 0], 
   [0, 0, 0.00333]] */
  wr31 = casadi_c5;
  /* #123: @4 = @2[10:13] */
  wr04 = wr02+10;
  /* #124: @11 = mac(@31,@4,@14) */
  casadi_copy(w14, 3, w11);
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr31+j, ct=wr04+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #125: @26 = @11[2] */
  for (rr=(&w26), cs=w11+2; cs!=w11+3; cs+=1) *rr++ = *cs;
  /* #126: @18 = (@10*@26) */
  w18  = (w10*w26);
  /* #127: @17 = @2[12] */
  w17 = wr02[12];
  /* #128: @6 = @11[1] */
  for (rr=(&w06), cs=w11+1; cs!=w11+2; cs+=1) *rr++ = *cs;
  /* #129: @19 = (@17*@6) */
  w19  = (w17*w06);
  /* #130: @18 = (@18-@19) */
  w18 -= w19;
  /* #131: @19 = @11[0] */
  for (rr=(&w19), cs=w11+0; cs!=w11+1; cs+=1) *rr++ = *cs;
  /* #132: @24 = (@17*@19) */
  w24  = (w17*w19);
  /* #133: @27 = @2[10] */
  w27 = wr02[10];
  /* #134: @26 = (@27*@26) */
  w26  = (w27*w26);
  /* #135: @24 = (@24-@26) */
  w24 -= w26;
  /* #136: @6 = (@27*@6) */
  w06  = (w27*w06);
  /* #137: @19 = (@10*@19) */
  w19  = (w10*w19);
  /* #138: @6 = (@6-@19) */
  w06 -= w19;
  /* #139: @11 = vertcat(@18, @24, @6) */
  rr=w11;
  *rr++ = w18;
  *rr++ = w24;
  *rr++ = w06;
  /* #140: @28 = (@28-@11) */
  for (i=0, rr=w28, cs=w11; i<3; ++i) (*rr++) -= (*cs++);
  /* #141: @11 = mac(@33,@28,@14) */
  casadi_copy(w14, 3, w11);
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr33+j, ct=w28+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #142: @18 = @11[1] */
  for (rr=(&w18), cs=w11+1; cs!=w11+2; cs+=1) *rr++ = *cs;
  /* #143: @24 = (@18*@15) */
  w24  = (w18*w15);
  /* #144: @6 = @11[2] */
  for (rr=(&w06), cs=w11+2; cs!=w11+3; cs+=1) *rr++ = *cs;
  /* #145: @19 = (@6*@16) */
  w19  = (w06*w16);
  /* #146: @24 = (@24-@19) */
  w24 -= w19;
  /* #147: @19 = (@6*@22) */
  w19  = (w06*w22);
  /* #148: @26 = @11[0] */
  for (rr=(&w26), cs=w11+0; cs!=w11+1; cs+=1) *rr++ = *cs;
  /* #149: @34 = (@26*@15) */
  w34  = (w26*w15);
  /* #150: @19 = (@19-@34) */
  w19 -= w34;
  /* #151: @34 = (@26*@16) */
  w34  = (w26*w16);
  /* #152: @35 = (@18*@22) */
  w35  = (w18*w22);
  /* #153: @34 = (@34-@35) */
  w34 -= w35;
  /* #154: @11 = vertcat(@24, @19, @34) */
  rr=w11;
  *rr++ = w24;
  *rr++ = w19;
  *rr++ = w34;
  /* #155: @24 = (@27*@16) */
  w24  = (w27*w16);
  /* #156: @19 = (@10*@22) */
  w19  = (w10*w22);
  /* #157: @24 = (@24-@19) */
  w24 -= w19;
  /* #158: @19 = (@10*@24) */
  w19  = (w10*w24);
  /* #159: @22 = (@17*@22) */
  w22  = (w17*w22);
  /* #160: @34 = (@27*@15) */
  w34  = (w27*w15);
  /* #161: @22 = (@22-@34) */
  w22 -= w34;
  /* #162: @34 = (@17*@22) */
  w34  = (w17*w22);
  /* #163: @19 = (@19-@34) */
  w19 -= w34;
  /* #164: @15 = (@10*@15) */
  w15  = (w10*w15);
  /* #165: @16 = (@17*@16) */
  w16  = (w17*w16);
  /* #166: @15 = (@15-@16) */
  w15 -= w16;
  /* #167: @16 = (@17*@15) */
  w16  = (w17*w15);
  /* #168: @24 = (@27*@24) */
  w24  = (w27*w24);
  /* #169: @16 = (@16-@24) */
  w16 -= w24;
  /* #170: @22 = (@27*@22) */
  w22  = (w27*w22);
  /* #171: @15 = (@10*@15) */
  w15  = (w10*w15);
  /* #172: @22 = (@22-@15) */
  w22 -= w15;
  /* #173: @28 = vertcat(@19, @16, @22) */
  rr=w28;
  *rr++ = w19;
  *rr++ = w16;
  *rr++ = w22;
  /* #174: @11 = (@11+@28) */
  for (i=0, rr=w11, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #175: @28 = mac(@32,@11,@14) */
  casadi_copy(w14, 3, w28);
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w32+j, ct=w11+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #176: @28 = (@9+@28) */
  for (i=0, rr=w28, cr=w09, cs=w28; i<3; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #177: @19 = @2[20] */
  w19 = wr02[20];
  /* #178: @16 = @2[15] */
  w16 = wr02[15];
  /* #179: @22 = (@19*@16) */
  w22  = (w19*w16);
  /* #180: @15 = @2[21] */
  w15 = wr02[21];
  /* #181: @24 = @2[14] */
  w24 = wr02[14];
  /* #182: @34 = (@15*@24) */
  w34  = (w15*w24);
  /* #183: @22 = (@22-@34) */
  w22 -= w34;
  /* #184: @34 = @2[13] */
  w34 = wr02[13];
  /* #185: @15 = (@15*@34) */
  w15 *= w34;
  /* #186: @35 = @2[19] */
  w35 = wr02[19];
  /* #187: @36 = (@35*@16) */
  w36  = (w35*w16);
  /* #188: @15 = (@15-@36) */
  w15 -= w36;
  /* #189: @35 = (@35*@24) */
  w35 *= w24;
  /* #190: @19 = (@19*@34) */
  w19 *= w34;
  /* #191: @35 = (@35-@19) */
  w35 -= w19;
  /* #192: @11 = vertcat(@22, @15, @35) */
  rr=w11;
  *rr++ = w22;
  *rr++ = w15;
  *rr++ = w35;
  /* #193: @22 = @2[17] */
  w22 = wr02[17];
  /* #194: @15 = @2[16] */
  w15 = wr02[16];
  /* #195: @35 = (@15*@24) */
  w35  = (w15*w24);
  /* #196: @19 = (@22*@34) */
  w19  = (w22*w34);
  /* #197: @35 = (@35-@19) */
  w35 -= w19;
  /* #198: @19 = (@22*@35) */
  w19  = (w22*w35);
  /* #199: @36 = @2[18] */
  w36 = wr02[18];
  /* #200: @34 = (@36*@34) */
  w34  = (w36*w34);
  /* #201: @37 = (@15*@16) */
  w37  = (w15*w16);
  /* #202: @34 = (@34-@37) */
  w34 -= w37;
  /* #203: @37 = (@36*@34) */
  w37  = (w36*w34);
  /* #204: @19 = (@19-@37) */
  w19 -= w37;
  /* #205: @16 = (@22*@16) */
  w16  = (w22*w16);
  /* #206: @24 = (@36*@24) */
  w24  = (w36*w24);
  /* #207: @16 = (@16-@24) */
  w16 -= w24;
  /* #208: @36 = (@36*@16) */
  w36 *= w16;
  /* #209: @35 = (@15*@35) */
  w35  = (w15*w35);
  /* #210: @36 = (@36-@35) */
  w36 -= w35;
  /* #211: @15 = (@15*@34) */
  w15 *= w34;
  /* #212: @22 = (@22*@16) */
  w22 *= w16;
  /* #213: @15 = (@15-@22) */
  w15 -= w22;
  /* #214: @4 = vertcat(@19, @36, @15) */
  rr=w04;
  *rr++ = w19;
  *rr++ = w36;
  *rr++ = w15;
  /* #215: @11 = (@11+@4) */
  for (i=0, rr=w11, cs=w04; i<3; ++i) (*rr++) += (*cs++);
  /* #216: @11 = (@0*@11) */
  for (i=0, rr=w11, cs=w11; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #217: @28 = (@28-@11) */
  for (i=0, rr=w28, cs=w11; i<3; ++i) (*rr++) -= (*cs++);
  /* #218: @28 = (@28-@1) */
  for (i=0, rr=w28, cs=w01; i<3; ++i) (*rr++) -= (*cs++);
  /* #219: @28 = (@0*@28) */
  for (i=0, rr=w28, cs=w28; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #220: @28 = (@28-@5) */
  for (i=0, rr=w28, cs=w05; i<3; ++i) (*rr++) -= (*cs++);
  /* #221: @19 = ||@28||_F */
  w19 = casadi_norm_2(3, w28);
  /* #222: output[0][0] = @19 */
  if (res[0]) res[0][0] = w19;
  /* #223: @19 = (@18*@13) */
  w19  = (w18*w13);
  /* #224: @36 = (@6*@25) */
  w36  = (w06*w25);
  /* #225: @19 = (@19-@36) */
  w19 -= w36;
  /* #226: @36 = (@6*@21) */
  w36  = (w06*w21);
  /* #227: @15 = (@26*@13) */
  w15  = (w26*w13);
  /* #228: @36 = (@36-@15) */
  w36 -= w15;
  /* #229: @15 = (@26*@25) */
  w15  = (w26*w25);
  /* #230: @22 = (@18*@21) */
  w22  = (w18*w21);
  /* #231: @15 = (@15-@22) */
  w15 -= w22;
  /* #232: @28 = vertcat(@19, @36, @15) */
  rr=w28;
  *rr++ = w19;
  *rr++ = w36;
  *rr++ = w15;
  /* #233: @19 = (@27*@25) */
  w19  = (w27*w25);
  /* #234: @36 = (@10*@21) */
  w36  = (w10*w21);
  /* #235: @19 = (@19-@36) */
  w19 -= w36;
  /* #236: @36 = (@10*@19) */
  w36  = (w10*w19);
  /* #237: @21 = (@17*@21) */
  w21  = (w17*w21);
  /* #238: @15 = (@27*@13) */
  w15  = (w27*w13);
  /* #239: @21 = (@21-@15) */
  w21 -= w15;
  /* #240: @15 = (@17*@21) */
  w15  = (w17*w21);
  /* #241: @36 = (@36-@15) */
  w36 -= w15;
  /* #242: @13 = (@10*@13) */
  w13  = (w10*w13);
  /* #243: @25 = (@17*@25) */
  w25  = (w17*w25);
  /* #244: @13 = (@13-@25) */
  w13 -= w25;
  /* #245: @25 = (@17*@13) */
  w25  = (w17*w13);
  /* #246: @19 = (@27*@19) */
  w19  = (w27*w19);
  /* #247: @25 = (@25-@19) */
  w25 -= w19;
  /* #248: @21 = (@27*@21) */
  w21  = (w27*w21);
  /* #249: @13 = (@10*@13) */
  w13  = (w10*w13);
  /* #250: @21 = (@21-@13) */
  w21 -= w13;
  /* #251: @5 = vertcat(@36, @25, @21) */
  rr=w05;
  *rr++ = w36;
  *rr++ = w25;
  *rr++ = w21;
  /* #252: @28 = (@28+@5) */
  for (i=0, rr=w28, cs=w05; i<3; ++i) (*rr++) += (*cs++);
  /* #253: @5 = mac(@32,@28,@14) */
  casadi_copy(w14, 3, w05);
  for (i=0, rr=w05; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w32+j, ct=w28+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #254: @5 = (@9+@5) */
  for (i=0, rr=w05, cr=w09, cs=w05; i<3; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #255: @36 = @2[34] */
  w36 = wr02[34];
  /* #256: @25 = @2[29] */
  w25 = wr02[29];
  /* #257: @21 = (@36*@25) */
  w21  = (w36*w25);
  /* #258: @13 = @2[35] */
  w13 = wr02[35];
  /* #259: @19 = @2[28] */
  w19 = wr02[28];
  /* #260: @15 = (@13*@19) */
  w15  = (w13*w19);
  /* #261: @21 = (@21-@15) */
  w21 -= w15;
  /* #262: @15 = @2[27] */
  w15 = wr02[27];
  /* #263: @13 = (@13*@15) */
  w13 *= w15;
  /* #264: @22 = @2[33] */
  w22 = wr02[33];
  /* #265: @16 = (@22*@25) */
  w16  = (w22*w25);
  /* #266: @13 = (@13-@16) */
  w13 -= w16;
  /* #267: @22 = (@22*@19) */
  w22 *= w19;
  /* #268: @36 = (@36*@15) */
  w36 *= w15;
  /* #269: @22 = (@22-@36) */
  w22 -= w36;
  /* #270: @28 = vertcat(@21, @13, @22) */
  rr=w28;
  *rr++ = w21;
  *rr++ = w13;
  *rr++ = w22;
  /* #271: @21 = @2[31] */
  w21 = wr02[31];
  /* #272: @13 = @2[30] */
  w13 = wr02[30];
  /* #273: @22 = (@13*@19) */
  w22  = (w13*w19);
  /* #274: @36 = (@21*@15) */
  w36  = (w21*w15);
  /* #275: @22 = (@22-@36) */
  w22 -= w36;
  /* #276: @36 = (@21*@22) */
  w36  = (w21*w22);
  /* #277: @16 = @2[32] */
  w16 = wr02[32];
  /* #278: @15 = (@16*@15) */
  w15  = (w16*w15);
  /* #279: @34 = (@13*@25) */
  w34  = (w13*w25);
  /* #280: @15 = (@15-@34) */
  w15 -= w34;
  /* #281: @34 = (@16*@15) */
  w34  = (w16*w15);
  /* #282: @36 = (@36-@34) */
  w36 -= w34;
  /* #283: @25 = (@21*@25) */
  w25  = (w21*w25);
  /* #284: @19 = (@16*@19) */
  w19  = (w16*w19);
  /* #285: @25 = (@25-@19) */
  w25 -= w19;
  /* #286: @16 = (@16*@25) */
  w16 *= w25;
  /* #287: @22 = (@13*@22) */
  w22  = (w13*w22);
  /* #288: @16 = (@16-@22) */
  w16 -= w22;
  /* #289: @13 = (@13*@15) */
  w13 *= w15;
  /* #290: @21 = (@21*@25) */
  w21 *= w25;
  /* #291: @13 = (@13-@21) */
  w13 -= w21;
  /* #292: @11 = vertcat(@36, @16, @13) */
  rr=w11;
  *rr++ = w36;
  *rr++ = w16;
  *rr++ = w13;
  /* #293: @28 = (@28+@11) */
  for (i=0, rr=w28, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #294: @28 = (@0*@28) */
  for (i=0, rr=w28, cs=w28; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #295: @5 = (@5-@28) */
  for (i=0, rr=w05, cs=w28; i<3; ++i) (*rr++) -= (*cs++);
  /* #296: @5 = (@5-@1) */
  for (i=0, rr=w05, cs=w01; i<3; ++i) (*rr++) -= (*cs++);
  /* #297: @5 = (@0*@5) */
  for (i=0, rr=w05, cs=w05; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #298: @5 = (@5-@8) */
  for (i=0, rr=w05, cs=w08; i<3; ++i) (*rr++) -= (*cs++);
  /* #299: @36 = ||@5||_F */
  w36 = casadi_norm_2(3, w05);
  /* #300: output[0][1] = @36 */
  if (res[0]) res[0][1] = w36;
  /* #301: @36 = (@18*@23) */
  w36  = (w18*w23);
  /* #302: @16 = (@6*@3) */
  w16  = (w06*w03);
  /* #303: @36 = (@36-@16) */
  w36 -= w16;
  /* #304: @6 = (@6*@20) */
  w06 *= w20;
  /* #305: @16 = (@26*@23) */
  w16  = (w26*w23);
  /* #306: @6 = (@6-@16) */
  w06 -= w16;
  /* #307: @26 = (@26*@3) */
  w26 *= w03;
  /* #308: @18 = (@18*@20) */
  w18 *= w20;
  /* #309: @26 = (@26-@18) */
  w26 -= w18;
  /* #310: @5 = vertcat(@36, @6, @26) */
  rr=w05;
  *rr++ = w36;
  *rr++ = w06;
  *rr++ = w26;
  /* #311: @36 = (@27*@3) */
  w36  = (w27*w03);
  /* #312: @6 = (@10*@20) */
  w06  = (w10*w20);
  /* #313: @36 = (@36-@6) */
  w36 -= w06;
  /* #314: @6 = (@10*@36) */
  w06  = (w10*w36);
  /* #315: @20 = (@17*@20) */
  w20  = (w17*w20);
  /* #316: @26 = (@27*@23) */
  w26  = (w27*w23);
  /* #317: @20 = (@20-@26) */
  w20 -= w26;
  /* #318: @26 = (@17*@20) */
  w26  = (w17*w20);
  /* #319: @6 = (@6-@26) */
  w06 -= w26;
  /* #320: @23 = (@10*@23) */
  w23  = (w10*w23);
  /* #321: @3 = (@17*@3) */
  w03  = (w17*w03);
  /* #322: @23 = (@23-@3) */
  w23 -= w03;
  /* #323: @17 = (@17*@23) */
  w17 *= w23;
  /* #324: @36 = (@27*@36) */
  w36  = (w27*w36);
  /* #325: @17 = (@17-@36) */
  w17 -= w36;
  /* #326: @27 = (@27*@20) */
  w27 *= w20;
  /* #327: @10 = (@10*@23) */
  w10 *= w23;
  /* #328: @27 = (@27-@10) */
  w27 -= w10;
  /* #329: @8 = vertcat(@6, @17, @27) */
  rr=w08;
  *rr++ = w06;
  *rr++ = w17;
  *rr++ = w27;
  /* #330: @5 = (@5+@8) */
  for (i=0, rr=w05, cs=w08; i<3; ++i) (*rr++) += (*cs++);
  /* #331: @14 = mac(@32,@5,@14) */
  for (i=0, rr=w14; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w32+j, ct=w05+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #332: @9 = (@9+@14) */
  for (i=0, rr=w09, cs=w14; i<3; ++i) (*rr++) += (*cs++);
  /* #333: @6 = @2[48] */
  w06 = wr02[48];
  /* #334: @17 = @2[43] */
  w17 = wr02[43];
  /* #335: @27 = (@6*@17) */
  w27  = (w06*w17);
  /* #336: @10 = @2[49] */
  w10 = wr02[49];
  /* #337: @23 = @2[42] */
  w23 = wr02[42];
  /* #338: @20 = (@10*@23) */
  w20  = (w10*w23);
  /* #339: @27 = (@27-@20) */
  w27 -= w20;
  /* #340: @20 = @2[41] */
  w20 = wr02[41];
  /* #341: @10 = (@10*@20) */
  w10 *= w20;
  /* #342: @36 = @2[47] */
  w36 = wr02[47];
  /* #343: @3 = (@36*@17) */
  w03  = (w36*w17);
  /* #344: @10 = (@10-@3) */
  w10 -= w03;
  /* #345: @36 = (@36*@23) */
  w36 *= w23;
  /* #346: @6 = (@6*@20) */
  w06 *= w20;
  /* #347: @36 = (@36-@6) */
  w36 -= w06;
  /* #348: @14 = vertcat(@27, @10, @36) */
  rr=w14;
  *rr++ = w27;
  *rr++ = w10;
  *rr++ = w36;
  /* #349: @27 = @2[45] */
  w27 = wr02[45];
  /* #350: @10 = @2[44] */
  w10 = wr02[44];
  /* #351: @36 = (@10*@23) */
  w36  = (w10*w23);
  /* #352: @6 = (@27*@20) */
  w06  = (w27*w20);
  /* #353: @36 = (@36-@6) */
  w36 -= w06;
  /* #354: @6 = (@27*@36) */
  w06  = (w27*w36);
  /* #355: @3 = @2[46] */
  w03 = wr02[46];
  /* #356: @20 = (@3*@20) */
  w20  = (w03*w20);
  /* #357: @26 = (@10*@17) */
  w26  = (w10*w17);
  /* #358: @20 = (@20-@26) */
  w20 -= w26;
  /* #359: @26 = (@3*@20) */
  w26  = (w03*w20);
  /* #360: @6 = (@6-@26) */
  w06 -= w26;
  /* #361: @17 = (@27*@17) */
  w17  = (w27*w17);
  /* #362: @23 = (@3*@23) */
  w23  = (w03*w23);
  /* #363: @17 = (@17-@23) */
  w17 -= w23;
  /* #364: @3 = (@3*@17) */
  w03 *= w17;
  /* #365: @36 = (@10*@36) */
  w36  = (w10*w36);
  /* #366: @3 = (@3-@36) */
  w03 -= w36;
  /* #367: @10 = (@10*@20) */
  w10 *= w20;
  /* #368: @27 = (@27*@17) */
  w27 *= w17;
  /* #369: @10 = (@10-@27) */
  w10 -= w27;
  /* #370: @5 = vertcat(@6, @3, @10) */
  rr=w05;
  *rr++ = w06;
  *rr++ = w03;
  *rr++ = w10;
  /* #371: @14 = (@14+@5) */
  for (i=0, rr=w14, cs=w05; i<3; ++i) (*rr++) += (*cs++);
  /* #372: @14 = (@0*@14) */
  for (i=0, rr=w14, cs=w14; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #373: @9 = (@9-@14) */
  for (i=0, rr=w09, cs=w14; i<3; ++i) (*rr++) -= (*cs++);
  /* #374: @9 = (@9-@1) */
  for (i=0, rr=w09, cs=w01; i<3; ++i) (*rr++) -= (*cs++);
  /* #375: @9 = (@0*@9) */
  for (i=0, rr=w09, cs=w09; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #376: @9 = (@9-@12) */
  for (i=0, rr=w09, cs=w12; i<3; ++i) (*rr++) -= (*cs++);
  /* #377: @0 = ||@9||_F */
  w00 = casadi_norm_2(3, w09);
  /* #378: output[0][2] = @0 */
  if (res[0]) res[0][2] = w00;
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_3_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int load_cable_3_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_3_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void load_cable_3_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int load_cable_3_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void load_cable_3_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void load_cable_3_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void load_cable_3_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int load_cable_3_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int load_cable_3_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real load_cable_3_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* load_cable_3_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* load_cable_3_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* load_cable_3_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* load_cable_3_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int load_cable_3_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 143;
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_3_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 143*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
