/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) load_cable_2_cost_y_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {41, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {4, 1, 1};
static const casadi_int casadi_s5[3] = {34, 1, 1};

static const casadi_real casadi_zeros[41] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* load_cable_2_cost_y_fun:(i0[41],i1[8],i2[0],i3[],i4[4])->(o0[34]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w01=w+41, *w02=w+44, w03, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14;
  const casadi_real *cs, *wr00, *wr01, *wr15;
  /* #0: @0 = input[0][0] */
  wr00 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = @0[:3] */
  wr01 = wr00+0;
  /* #2: output[0][0] = @1 */
  casadi_copy(wr01, 3, res[0]);
  /* #3: @1 = @0[3:6] */
  wr01 = wr00+3;
  /* #4: output[0][1] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+3);
  /* #5: @2 = input[4][0] */
  casadi_copy(arg[4], 4, w02);
  /* #6: @3 = @2[0] */
  for (rr=(&w03), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #7: @4 = @0[6] */
  w04 = wr00[6];
  /* #8: @5 = (@3*@4) */
  w05  = (w03*w04);
  /* #9: @6 = @2[1] */
  for (rr=(&w06), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #10: @7 = @0[7] */
  w07 = wr00[7];
  /* #11: @8 = (@6*@7) */
  w08  = (w06*w07);
  /* #12: @5 = (@5+@8) */
  w05 += w08;
  /* #13: @8 = @2[2] */
  for (rr=(&w08), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #14: @9 = @0[8] */
  w09 = wr00[8];
  /* #15: @10 = (@8*@9) */
  w10  = (w08*w09);
  /* #16: @5 = (@5+@10) */
  w05 += w10;
  /* #17: @10 = @2[3] */
  for (rr=(&w10), cs=w02+3; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #18: @11 = @0[9] */
  w11 = wr00[9];
  /* #19: @12 = (@10*@11) */
  w12  = (w10*w11);
  /* #20: @5 = (@5+@12) */
  w05 += w12;
  /* #21: @12 = (@6*@4) */
  w12  = (w06*w04);
  /* #22: @13 = (@3*@7) */
  w13  = (w03*w07);
  /* #23: @12 = (@12-@13) */
  w12 -= w13;
  /* #24: @13 = (@8*@11) */
  w13  = (w08*w11);
  /* #25: @12 = (@12-@13) */
  w12 -= w13;
  /* #26: @13 = (@10*@9) */
  w13  = (w10*w09);
  /* #27: @12 = (@12+@13) */
  w12 += w13;
  /* #28: @13 = (@6*@11) */
  w13  = (w06*w11);
  /* #29: @14 = (@3*@9) */
  w14  = (w03*w09);
  /* #30: @13 = (@13-@14) */
  w13 -= w14;
  /* #31: @14 = (@8*@4) */
  w14  = (w08*w04);
  /* #32: @13 = (@13+@14) */
  w13 += w14;
  /* #33: @14 = (@10*@7) */
  w14  = (w10*w07);
  /* #34: @13 = (@13-@14) */
  w13 -= w14;
  /* #35: @6 = (@6*@9) */
  w06 *= w09;
  /* #36: @6 = (-@6) */
  w06 = (- w06 );
  /* #37: @3 = (@3*@11) */
  w03 *= w11;
  /* #38: @6 = (@6-@3) */
  w06 -= w03;
  /* #39: @8 = (@8*@7) */
  w08 *= w07;
  /* #40: @6 = (@6+@8) */
  w06 += w08;
  /* #41: @10 = (@10*@4) */
  w10 *= w04;
  /* #42: @6 = (@6+@10) */
  w06 += w10;
  /* #43: @2 = vertcat(@5, @12, @13, @6) */
  rr=w02;
  *rr++ = w05;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w06;
  /* #44: @1 = @2[1:4] */
  for (rr=w01, cs=w02+1; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #45: @1 = (2.*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #46: output[0][2] = @1 */
  if (res[0]) casadi_copy(w01, 3, res[0]+6);
  /* #47: @1 = @0[10:13] */
  wr01 = wr00+10;
  /* #48: output[0][3] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+9);
  /* #49: @1 = @0[13:16] */
  wr01 = wr00+13;
  /* #50: output[0][4] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+12);
  /* #51: @1 = @0[27:30] */
  wr01 = wr00+27;
  /* #52: output[0][5] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+15);
  /* #53: @5 = @0[25] */
  w05 = wr00[25];
  /* #54: output[0][6] = @5 */
  if (res[0]) res[0][18] = w05;
  /* #55: @5 = @0[39] */
  w05 = wr00[39];
  /* #56: output[0][7] = @5 */
  if (res[0]) res[0][19] = w05;
  /* #57: @1 = @0[16:19] */
  wr01 = wr00+16;
  /* #58: output[0][8] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+20);
  /* #59: @1 = @0[30:33] */
  wr01 = wr00+30;
  /* #60: output[0][9] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+23);
  /* #61: @15 = input[1][0] */
  wr15 = arg[1] ? arg[1] : casadi_zeros;
  /* #62: output[0][10] = @15 */
  if (res[0]) casadi_copy(wr15, 8, res[0]+26);
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_2_cost_y_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int load_cable_2_cost_y_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_2_cost_y_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void load_cable_2_cost_y_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int load_cable_2_cost_y_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void load_cable_2_cost_y_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void load_cable_2_cost_y_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void load_cable_2_cost_y_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int load_cable_2_cost_y_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int load_cable_2_cost_y_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real load_cable_2_cost_y_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* load_cable_2_cost_y_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* load_cable_2_cost_y_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* load_cable_2_cost_y_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* load_cable_2_cost_y_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int load_cable_2_cost_y_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 68;
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_2_cost_y_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 68*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
