"""
mpc_four_soft_launch.py
-----------------------
MPC control stack for four_soft.sdf — 4 drones carrying a rigid payload via
soft cables (the world generated by simulation_assets/generate_soft_world.py
with --n 4, drones 90 deg apart at radius 0.5 m, 0.4 kg payload).

Identical to mpc_three_soft_launch.py but at N=4 and with trajectory='hover':
each drone runs the per-drone MPC tracking its OWN lift-and-hold trajectory over
its spawn point (reference_source defaults to 'internal'). Climbing straight up
makes the slack 0.6 m cables go taut at ~45 deg and lifts the load 1:1, instead
of the wide circle that fought the tethers. Formation comes from the SDF spawn
positions, so no formation offsets are needed here.

This is the cable-aware PLANNER-free stack: getting four_soft flying the way
two_soft did, before layering the centralized load planner back on.

Run Gazebo first (separate terminal):
    gz sim four_soft.sdf -v 4 -r
then:
    ros2 launch controller_mpc_multi mpc_four_soft_launch.py
then drive the fleet:
    ros2 topic pub --once /fleet/command std_msgs/msg/String "{data: ARM}"
    ros2 topic pub --once /fleet/command std_msgs/msg/String "{data: TAKEOFF}"

Notes:
  * SetParameter(use_sim_time=True) applies to the BRIDGES (mocap velocity dt).
    The MPC controller / fleet nodes pin use_sim_time=False internally.
  * acados compilation is serialised by a file lock inside controller_mpc.py,
    so the four controllers starting together is safe.
  * four_soft.sdf includes the world-fixed `anchor` link, so the nested
    /model/lift_system/model/x3_drone{i}/pose topics report WORLD poses.
"""

from launch import LaunchDescription
from launch_ros.actions import Node, SetParameter

PARENT_MODEL = 'lift_system'
DRONE_NAMES  = ['x3_drone0', 'x3_drone1', 'x3_drone2', 'x3_drone3']
N            = len(DRONE_NAMES)


def generate_launch_description():
    # use_sim_time for the bridge nodes (mocap velocity dt). MPC nodes override
    # this internally, so it only affects the bridges — which is what we want.
    nodes = [SetParameter(name='use_sim_time', value=True)]

    # ── Clock bridge ──────────────────────────────────────────────────────────
    nodes.append(Node(
        package='ros_gz_bridge',
        executable='parameter_bridge',
        name='clock_bridge',
        arguments=['/clock@rosgraph_msgs/msg/Clock[gz.msgs.Clock'],
        output='screen',
    ))

    # ── Payload pose bridge ───────────────────────────────────────────────────
    nodes.append(Node(
        package='ros_gz_bridge',
        executable='parameter_bridge',
        name='payload_pose_bridge',
        arguments=[
            f'/model/{PARENT_MODEL}/model/payload/pose'
            f'@geometry_msgs/msg/PoseArray[ignition.msgs.Pose_V'
        ],
    ))

    for i, drone_name in enumerate(DRONE_NAMES):
        # ── Drone pose bridge ─────────────────────────────────────────────────
        nodes.append(Node(
            package='ros_gz_bridge',
            executable='parameter_bridge',
            name=f'drone_pose_bridge_{i}',
            arguments=[
                f'/model/{PARENT_MODEL}/model/{drone_name}/pose'
                f'@geometry_msgs/msg/PoseArray[ignition.msgs.Pose_V'
            ],
        ))

        # ── Motor command bridge ──────────────────────────────────────────────
        nodes.append(Node(
            package='ros_gz_bridge',
            executable='parameter_bridge',
            name=f'motor_bridge_{i}',
            arguments=[
                f'/{drone_name}/gazebo/command/motor_speed'
                f'@actuator_msgs/msg/Actuators]ignition.msgs.Actuators'
            ],
        ))

        # ── Betaflight inner-loop ─────────────────────────────────────────────
        nodes.append(Node(
            package='simulation_communication',
            executable='payload_betaflight_comm',
            name=f'bf_comm_{i}',
            parameters=[{
                'drone_id':     i,
                'drone_name':   drone_name,
                'parent_model': PARENT_MODEL,
            }],
        ))

        # ── Mocap emulator (drone 0 also publishes the payload pose) ──────────
        nodes.append(Node(
            package='simulation_communication',
            executable='payload_mocap_emulator',
            name=f'mocap_{i}',
            parameters=[{
                'drone_id':        i,
                'drone_name':      drone_name,
                'parent_model':    PARENT_MODEL,
                'publish_payload': (i == 0),
            }],
        ))

        # ── Per-drone MPC controller (lift-and-hold over spawn) ───────────────
        # trajectory='hover': climb straight up so the slack cables go taut and
        # the load lifts 1:1, instead of a wide circle that fights the tethers.
        nodes.append(Node(
            package='controller_mpc_multi',
            executable='controller',
            name=f'controller_{i}',
            parameters=[{'drone_id': i, 'trajectory': 'hover'}],
            output='screen',
        ))

    # ── Central fleet manager ─────────────────────────────────────────────────
    nodes.append(Node(
        package='controller_mpc_multi',
        executable='main',
        name='central_controller',
        parameters=[{'num_drones': N}],
        output='screen',
    ))

    return LaunchDescription(nodes)
