- ros_topic_name: "/m2b/gz/attach"
  gz_topic_name: "/payload/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: ROS_TO_GZ
- ros_topic_name: "/m2b/gz/detach"
  gz_topic_name: "/payload/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: ROS_TO_GZ
