- ros_topic_name: "/drone_0/magnet/attach"
  gz_topic_name: "/drone_0/magnet/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: ROS_TO_GZ
- ros_topic_name: "/drone_0/magnet/detach"
  gz_topic_name: "/drone_0/magnet/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: ROS_TO_GZ
- ros_topic_name: "/drone_1/magnet/attach"
  gz_topic_name: "/drone_1/magnet/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: ROS_TO_GZ
- ros_topic_name: "/drone_1/magnet/detach"
  gz_topic_name: "/drone_1/magnet/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: ROS_TO_GZ
- ros_topic_name: "/drone_2/magnet/attach"
  gz_topic_name: "/drone_2/magnet/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: ROS_TO_GZ
- ros_topic_name: "/drone_2/magnet/detach"
  gz_topic_name: "/drone_2/magnet/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: ROS_TO_GZ
- ros_topic_name: "/drone_3/magnet/attach"
  gz_topic_name: "/drone_3/magnet/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: ROS_TO_GZ
- ros_topic_name: "/drone_3/magnet/detach"
  gz_topic_name: "/drone_3/magnet/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: ROS_TO_GZ
