/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) load_cable_4_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_c6 CASADI_PREFIX(c6)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {69, 1, 1};
static const casadi_int casadi_s1[3] = {16, 1, 1};
static const casadi_int casadi_s2[3] = {4, 1, 1};

static const casadi_real casadi_c0[3] = {0., 0., -9.8100000000000005e+00};
static const casadi_real casadi_c1[9] = 
  {5.9880239520958082e+02, 0., 0., 0., 5.9880239520958082e+02, 0., 0., 0.,
  3.0030030030030031e+02};
static const casadi_real casadi_c2[3] = {8.0000000000000002e-02, 0., 2.5000000000000001e-02};
static const casadi_real casadi_c3[3] = {4.8985871965894128e-18, 8.0000000000000002e-02, 2.5000000000000001e-02};
static const casadi_real casadi_c4[3] = {-8.0000000000000002e-02, 9.7971743931788255e-18, 2.5000000000000001e-02};
static const casadi_real casadi_c5[3] = {-1.4695761589768237e-17, -8.0000000000000002e-02, 2.5000000000000001e-02};
static const casadi_real casadi_c6[9] = 
  {1.6700000000000000e-03, 0., 0., 0., 1.6700000000000000e-03, 0., 0., 0.,
  3.3300000000000001e-03};

static const casadi_real casadi_zeros[69] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0.};

/* load_cable_4_expl_ode_fun:(i0[69],i1[16],i2[4])->(o0[69]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w01=w+72, w02, *w03=w+76, *w04=w+79, w05, *w06=w+83, *w07=w+86, w08, *w09=w+90, w10, *w11=w+94;
  casadi_real w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23;
  casadi_real w24, *w25=w+110, w27, w28, w29, w30, *w31=w+127, *w32=w+130;
  const casadi_real *cs, *ct, *wr00, *wr01, *wr03, *wr06, *wr07, *wr09, *wr26, *wr32, *wr33;
  /* #0: @0 = input[0][0] */
  wr00 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = @0[3:6] */
  wr01 = wr00+3;
  /* #2: output[0][0] = @1 */
  casadi_copy(wr01, 3, res[0]);
  /* #3: @1 = [0, 0, -9.81] */
  casadi_copy(casadi_c0, 3, w01);
  /* #4: @2 = @0[25] */
  w02 = wr00[25];
  /* #5: @3 = @0[13:16] */
  wr03 = wr00+13;
  /* #6: @4 = (@2*@3) */
  for (i=0, rr=w04, cs=wr03; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #7: @5 = @0[39] */
  w05 = wr00[39];
  /* #8: @6 = @0[27:30] */
  wr06 = wr00+27;
  /* #9: @7 = (@5*@6) */
  for (i=0, rr=w07, cs=wr06; i<3; ++i) (*rr++)  = (w05*(*cs++));
  /* #10: @4 = (@4+@7) */
  for (i=0, rr=w04, cs=w07; i<3; ++i) (*rr++) += (*cs++);
  /* #11: @8 = @0[53] */
  w08 = wr00[53];
  /* #12: @7 = @0[41:44] */
  wr07 = wr00+41;
  /* #13: @9 = (@8*@7) */
  for (i=0, rr=w09, cs=wr07; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #14: @4 = (@4+@9) */
  for (i=0, rr=w04, cs=w09; i<3; ++i) (*rr++) += (*cs++);
  /* #15: @10 = @0[67] */
  w10 = wr00[67];
  /* #16: @9 = @0[55:58] */
  wr09 = wr00+55;
  /* #17: @11 = (@10*@9) */
  for (i=0, rr=w11, cs=wr09; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #18: @4 = (@4+@11) */
  for (i=0, rr=w04, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #19: @12 = 0.4 */
  w12 = 4.0000000000000002e-01;
  /* #20: @4 = (@4/@12) */
  for (i=0, rr=w04; i<3; ++i) (*rr++) /= w12;
  /* #21: @1 = (@1-@4) */
  for (i=0, rr=w01, cs=w04; i<3; ++i) (*rr++) -= (*cs++);
  /* #22: output[0][1] = @1 */
  if (res[0]) casadi_copy(w01, 3, res[0]+3);
  /* #23: @12 = 0.5 */
  w12 = 5.0000000000000000e-01;
  /* #24: @13 = @0[7] */
  w13 = wr00[7];
  /* #25: @14 = @0[10] */
  w14 = wr00[10];
  /* #26: @15 = (@13*@14) */
  w15  = (w13*w14);
  /* #27: @15 = (-@15) */
  w15 = (- w15 );
  /* #28: @16 = @0[8] */
  w16 = wr00[8];
  /* #29: @17 = @0[11] */
  w17 = wr00[11];
  /* #30: @18 = (@16*@17) */
  w18  = (w16*w17);
  /* #31: @15 = (@15-@18) */
  w15 -= w18;
  /* #32: @18 = @0[9] */
  w18 = wr00[9];
  /* #33: @19 = @0[12] */
  w19 = wr00[12];
  /* #34: @20 = (@18*@19) */
  w20  = (w18*w19);
  /* #35: @15 = (@15-@20) */
  w15 -= w20;
  /* #36: @20 = @0[6] */
  w20 = wr00[6];
  /* #37: @21 = (@20*@14) */
  w21  = (w20*w14);
  /* #38: @22 = (@16*@19) */
  w22  = (w16*w19);
  /* #39: @21 = (@21+@22) */
  w21 += w22;
  /* #40: @22 = (@18*@17) */
  w22  = (w18*w17);
  /* #41: @21 = (@21-@22) */
  w21 -= w22;
  /* #42: @22 = (@20*@17) */
  w22  = (w20*w17);
  /* #43: @23 = (@13*@19) */
  w23  = (w13*w19);
  /* #44: @22 = (@22-@23) */
  w22 -= w23;
  /* #45: @23 = (@18*@14) */
  w23  = (w18*w14);
  /* #46: @22 = (@22+@23) */
  w22 += w23;
  /* #47: @23 = (@20*@19) */
  w23  = (w20*w19);
  /* #48: @24 = (@13*@17) */
  w24  = (w13*w17);
  /* #49: @23 = (@23+@24) */
  w23 += w24;
  /* #50: @24 = (@16*@14) */
  w24  = (w16*w14);
  /* #51: @23 = (@23-@24) */
  w23 -= w24;
  /* #52: @25 = vertcat(@15, @21, @22, @23) */
  rr=w25;
  *rr++ = w15;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  /* #53: @25 = (@12*@25) */
  for (i=0, rr=w25, cs=w25; i<4; ++i) (*rr++)  = (w12*(*cs++));
  /* #54: output[0][2] = @25 */
  if (res[0]) casadi_copy(w25, 4, res[0]+6);
  /* #55: @1 = zeros(3x1) */
  casadi_clear(w01, 3);
  /* #56: @26 = 
  [[598.802, 0, 0], 
   [0, 598.802, 0], 
   [0, 0, 300.3]] */
  wr26 = casadi_c1;
  /* #57: @12 = 1 */
  w12 = 1.;
  /* #58: @15 = sq(@16) */
  w15 = casadi_sq( w16 );
  /* #59: @21 = sq(@18) */
  w21 = casadi_sq( w18 );
  /* #60: @22 = (@15+@21) */
  w22  = (w15+w21);
  /* #61: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #62: @22 = (@12-@22) */
  w22  = (w12-w22);
  /* #63: @23 = (@13*@16) */
  w23  = (w13*w16);
  /* #64: @24 = (@20*@18) */
  w24  = (w20*w18);
  /* #65: @27 = (@23-@24) */
  w27  = (w23-w24);
  /* #66: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #67: @28 = (@13*@18) */
  w28  = (w13*w18);
  /* #68: @29 = (@20*@16) */
  w29  = (w20*w16);
  /* #69: @30 = (@28+@29) */
  w30  = (w28+w29);
  /* #70: @30 = (2.*@30) */
  w30 = (2.* w30 );
  /* #71: @4 = horzcat(@22, @27, @30) */
  rr=w04;
  *rr++ = w22;
  *rr++ = w27;
  *rr++ = w30;
  /* #72: @4 = @4' */
  /* #73: @23 = (@23+@24) */
  w23 += w24;
  /* #74: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #75: @24 = sq(@13) */
  w24 = casadi_sq( w13 );
  /* #76: @21 = (@24+@21) */
  w21  = (w24+w21);
  /* #77: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #78: @21 = (@12-@21) */
  w21  = (w12-w21);
  /* #79: @16 = (@16*@18) */
  w16 *= w18;
  /* #80: @20 = (@20*@13) */
  w20 *= w13;
  /* #81: @13 = (@16-@20) */
  w13  = (w16-w20);
  /* #82: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #83: @11 = horzcat(@23, @21, @13) */
  rr=w11;
  *rr++ = w23;
  *rr++ = w21;
  *rr++ = w13;
  /* #84: @11 = @11' */
  /* #85: @28 = (@28-@29) */
  w28 -= w29;
  /* #86: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #87: @16 = (@16+@20) */
  w16 += w20;
  /* #88: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #89: @24 = (@24+@15) */
  w24 += w15;
  /* #90: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #91: @12 = (@12-@24) */
  w12 -= w24;
  /* #92: @31 = horzcat(@28, @16, @12) */
  rr=w31;
  *rr++ = w28;
  *rr++ = w16;
  *rr++ = w12;
  /* #93: @31 = @31' */
  /* #94: @32 = horzcat(@4, @11, @31) */
  rr=w32;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<3; ++i) *rr++ = *cs++;
  /* #95: @4 = mac(@32,@3,@1) */
  casadi_copy(w01, 3, w04);
  for (i=0, rr=w04; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w32+j, ct=wr03+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #96: @28 = @4[1] */
  for (rr=(&w28), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #97: @3 = [0.08, 0, 0.025] */
  casadi_copy(casadi_c2, 3, w03);
  /* #98: @16 = @3[2] */
  for (rr=(&w16), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #99: @12 = (@28*@16) */
  w12  = (w28*w16);
  /* #100: @24 = @4[2] */
  for (rr=(&w24), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #101: @15 = @3[1] */
  for (rr=(&w15), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #102: @20 = (@24*@15) */
  w20  = (w24*w15);
  /* #103: @12 = (@12-@20) */
  w12 -= w20;
  /* #104: @20 = @3[0] */
  for (rr=(&w20), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #105: @24 = (@24*@20) */
  w24 *= w20;
  /* #106: @29 = @4[0] */
  for (rr=(&w29), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #107: @16 = (@29*@16) */
  w16  = (w29*w16);
  /* #108: @24 = (@24-@16) */
  w24 -= w16;
  /* #109: @29 = (@29*@15) */
  w29 *= w15;
  /* #110: @28 = (@28*@20) */
  w28 *= w20;
  /* #111: @29 = (@29-@28) */
  w29 -= w28;
  /* #112: @4 = vertcat(@12, @24, @29) */
  rr=w04;
  *rr++ = w12;
  *rr++ = w24;
  *rr++ = w29;
  /* #113: @4 = (@2*@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #114: @3 = mac(@32,@6,@1) */
  casadi_copy(w01, 3, w03);
  for (i=0, rr=w03; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w32+j, ct=wr06+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #115: @2 = @3[1] */
  for (rr=(&w02), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #116: @6 = [4.89859e-18, 0.08, 0.025] */
  casadi_copy(casadi_c3, 3, w06);
  /* #117: @12 = @6[2] */
  for (rr=(&w12), cs=w06+2; cs!=w06+3; cs+=1) *rr++ = *cs;
  /* #118: @24 = (@2*@12) */
  w24  = (w02*w12);
  /* #119: @29 = @3[2] */
  for (rr=(&w29), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #120: @28 = @6[1] */
  for (rr=(&w28), cs=w06+1; cs!=w06+2; cs+=1) *rr++ = *cs;
  /* #121: @20 = (@29*@28) */
  w20  = (w29*w28);
  /* #122: @24 = (@24-@20) */
  w24 -= w20;
  /* #123: @20 = @6[0] */
  for (rr=(&w20), cs=w06+0; cs!=w06+1; cs+=1) *rr++ = *cs;
  /* #124: @29 = (@29*@20) */
  w29 *= w20;
  /* #125: @15 = @3[0] */
  for (rr=(&w15), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #126: @12 = (@15*@12) */
  w12  = (w15*w12);
  /* #127: @29 = (@29-@12) */
  w29 -= w12;
  /* #128: @15 = (@15*@28) */
  w15 *= w28;
  /* #129: @2 = (@2*@20) */
  w02 *= w20;
  /* #130: @15 = (@15-@2) */
  w15 -= w02;
  /* #131: @3 = vertcat(@24, @29, @15) */
  rr=w03;
  *rr++ = w24;
  *rr++ = w29;
  *rr++ = w15;
  /* #132: @3 = (@5*@3) */
  for (i=0, rr=w03, cs=w03; i<3; ++i) (*rr++)  = (w05*(*cs++));
  /* #133: @4 = (@4+@3) */
  for (i=0, rr=w04, cs=w03; i<3; ++i) (*rr++) += (*cs++);
  /* #134: @3 = mac(@32,@7,@1) */
  casadi_copy(w01, 3, w03);
  for (i=0, rr=w03; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w32+j, ct=wr07+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #135: @5 = @3[1] */
  for (rr=(&w05), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #136: @7 = [-0.08, 9.79717e-18, 0.025] */
  casadi_copy(casadi_c4, 3, w07);
  /* #137: @24 = @7[2] */
  for (rr=(&w24), cs=w07+2; cs!=w07+3; cs+=1) *rr++ = *cs;
  /* #138: @29 = (@5*@24) */
  w29  = (w05*w24);
  /* #139: @15 = @3[2] */
  for (rr=(&w15), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #140: @2 = @7[1] */
  for (rr=(&w02), cs=w07+1; cs!=w07+2; cs+=1) *rr++ = *cs;
  /* #141: @20 = (@15*@2) */
  w20  = (w15*w02);
  /* #142: @29 = (@29-@20) */
  w29 -= w20;
  /* #143: @20 = @7[0] */
  for (rr=(&w20), cs=w07+0; cs!=w07+1; cs+=1) *rr++ = *cs;
  /* #144: @15 = (@15*@20) */
  w15 *= w20;
  /* #145: @28 = @3[0] */
  for (rr=(&w28), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #146: @24 = (@28*@24) */
  w24  = (w28*w24);
  /* #147: @15 = (@15-@24) */
  w15 -= w24;
  /* #148: @28 = (@28*@2) */
  w28 *= w02;
  /* #149: @5 = (@5*@20) */
  w05 *= w20;
  /* #150: @28 = (@28-@5) */
  w28 -= w05;
  /* #151: @3 = vertcat(@29, @15, @28) */
  rr=w03;
  *rr++ = w29;
  *rr++ = w15;
  *rr++ = w28;
  /* #152: @3 = (@8*@3) */
  for (i=0, rr=w03, cs=w03; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #153: @4 = (@4+@3) */
  for (i=0, rr=w04, cs=w03; i<3; ++i) (*rr++) += (*cs++);
  /* #154: @3 = mac(@32,@9,@1) */
  casadi_copy(w01, 3, w03);
  for (i=0, rr=w03; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w32+j, ct=wr09+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #155: @8 = @3[1] */
  for (rr=(&w08), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #156: @9 = [-1.46958e-17, -0.08, 0.025] */
  casadi_copy(casadi_c5, 3, w09);
  /* #157: @29 = @9[2] */
  for (rr=(&w29), cs=w09+2; cs!=w09+3; cs+=1) *rr++ = *cs;
  /* #158: @15 = (@8*@29) */
  w15  = (w08*w29);
  /* #159: @28 = @3[2] */
  for (rr=(&w28), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #160: @5 = @9[1] */
  for (rr=(&w05), cs=w09+1; cs!=w09+2; cs+=1) *rr++ = *cs;
  /* #161: @20 = (@28*@5) */
  w20  = (w28*w05);
  /* #162: @15 = (@15-@20) */
  w15 -= w20;
  /* #163: @20 = @9[0] */
  for (rr=(&w20), cs=w09+0; cs!=w09+1; cs+=1) *rr++ = *cs;
  /* #164: @28 = (@28*@20) */
  w28 *= w20;
  /* #165: @2 = @3[0] */
  for (rr=(&w02), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #166: @29 = (@2*@29) */
  w29  = (w02*w29);
  /* #167: @28 = (@28-@29) */
  w28 -= w29;
  /* #168: @2 = (@2*@5) */
  w02 *= w05;
  /* #169: @8 = (@8*@20) */
  w08 *= w20;
  /* #170: @2 = (@2-@8) */
  w02 -= w08;
  /* #171: @3 = vertcat(@15, @28, @2) */
  rr=w03;
  *rr++ = w15;
  *rr++ = w28;
  *rr++ = w02;
  /* #172: @3 = (@10*@3) */
  for (i=0, rr=w03, cs=w03; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #173: @4 = (@4+@3) */
  for (i=0, rr=w04, cs=w03; i<3; ++i) (*rr++) += (*cs++);
  /* #174: @32 = 
  [[0.00167, 0, 0], 
   [0, 0.00167, 0], 
   [0, 0, 0.00333]] */
  wr32 = casadi_c6;
  /* #175: @3 = @0[10:13] */
  wr03 = wr00+10;
  /* #176: @9 = mac(@32,@3,@1) */
  casadi_copy(w01, 3, w09);
  for (i=0, rr=w09; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr32+j, ct=wr03+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #177: @10 = @9[2] */
  for (rr=(&w10), cs=w09+2; cs!=w09+3; cs+=1) *rr++ = *cs;
  /* #178: @15 = (@17*@10) */
  w15  = (w17*w10);
  /* #179: @28 = @9[1] */
  for (rr=(&w28), cs=w09+1; cs!=w09+2; cs+=1) *rr++ = *cs;
  /* #180: @2 = (@19*@28) */
  w02  = (w19*w28);
  /* #181: @15 = (@15-@2) */
  w15 -= w02;
  /* #182: @2 = @9[0] */
  for (rr=(&w02), cs=w09+0; cs!=w09+1; cs+=1) *rr++ = *cs;
  /* #183: @19 = (@19*@2) */
  w19 *= w02;
  /* #184: @10 = (@14*@10) */
  w10  = (w14*w10);
  /* #185: @19 = (@19-@10) */
  w19 -= w10;
  /* #186: @14 = (@14*@28) */
  w14 *= w28;
  /* #187: @17 = (@17*@2) */
  w17 *= w02;
  /* #188: @14 = (@14-@17) */
  w14 -= w17;
  /* #189: @9 = vertcat(@15, @19, @14) */
  rr=w09;
  *rr++ = w15;
  *rr++ = w19;
  *rr++ = w14;
  /* #190: @4 = (@4-@9) */
  for (i=0, rr=w04, cs=w09; i<3; ++i) (*rr++) -= (*cs++);
  /* #191: @1 = mac(@26,@4,@1) */
  for (i=0, rr=w01; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr26+j, ct=w04+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #192: output[0][3] = @1 */
  if (res[0]) casadi_copy(w01, 3, res[0]+10);
  /* #193: @15 = @0[17] */
  w15 = wr00[17];
  /* #194: @19 = @0[15] */
  w19 = wr00[15];
  /* #195: @14 = (@15*@19) */
  w14  = (w15*w19);
  /* #196: @17 = @0[18] */
  w17 = wr00[18];
  /* #197: @2 = @0[14] */
  w02 = wr00[14];
  /* #198: @28 = (@17*@2) */
  w28  = (w17*w02);
  /* #199: @14 = (@14-@28) */
  w14 -= w28;
  /* #200: output[0][4] = @14 */
  if (res[0]) res[0][13] = w14;
  /* #201: @14 = @0[13] */
  w14 = wr00[13];
  /* #202: @17 = (@17*@14) */
  w17 *= w14;
  /* #203: @28 = @0[16] */
  w28 = wr00[16];
  /* #204: @19 = (@28*@19) */
  w19  = (w28*w19);
  /* #205: @17 = (@17-@19) */
  w17 -= w19;
  /* #206: output[0][5] = @17 */
  if (res[0]) res[0][14] = w17;
  /* #207: @28 = (@28*@2) */
  w28 *= w02;
  /* #208: @15 = (@15*@14) */
  w15 *= w14;
  /* #209: @28 = (@28-@15) */
  w28 -= w15;
  /* #210: output[0][6] = @28 */
  if (res[0]) res[0][15] = w28;
  /* #211: @1 = @0[19:22] */
  wr01 = wr00+19;
  /* #212: output[0][7] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+16);
  /* #213: @1 = @0[22:25] */
  wr01 = wr00+22;
  /* #214: output[0][8] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+19);
  /* #215: @33 = input[1][0] */
  wr33 = arg[1] ? arg[1] : casadi_zeros;
  /* #216: @1 = @33[:3] */
  wr01 = wr33+0;
  /* #217: output[0][9] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+22);
  /* #218: @28 = @0[26] */
  w28 = wr00[26];
  /* #219: output[0][10] = @28 */
  if (res[0]) res[0][25] = w28;
  /* #220: @28 = @33[3] */
  w28 = wr33[3];
  /* #221: output[0][11] = @28 */
  if (res[0]) res[0][26] = w28;
  /* #222: @28 = @0[31] */
  w28 = wr00[31];
  /* #223: @15 = @0[29] */
  w15 = wr00[29];
  /* #224: @14 = (@28*@15) */
  w14  = (w28*w15);
  /* #225: @2 = @0[32] */
  w02 = wr00[32];
  /* #226: @17 = @0[28] */
  w17 = wr00[28];
  /* #227: @19 = (@2*@17) */
  w19  = (w02*w17);
  /* #228: @14 = (@14-@19) */
  w14 -= w19;
  /* #229: output[0][12] = @14 */
  if (res[0]) res[0][27] = w14;
  /* #230: @14 = @0[27] */
  w14 = wr00[27];
  /* #231: @2 = (@2*@14) */
  w02 *= w14;
  /* #232: @19 = @0[30] */
  w19 = wr00[30];
  /* #233: @15 = (@19*@15) */
  w15  = (w19*w15);
  /* #234: @2 = (@2-@15) */
  w02 -= w15;
  /* #235: output[0][13] = @2 */
  if (res[0]) res[0][28] = w02;
  /* #236: @19 = (@19*@17) */
  w19 *= w17;
  /* #237: @28 = (@28*@14) */
  w28 *= w14;
  /* #238: @19 = (@19-@28) */
  w19 -= w28;
  /* #239: output[0][14] = @19 */
  if (res[0]) res[0][29] = w19;
  /* #240: @1 = @0[33:36] */
  wr01 = wr00+33;
  /* #241: output[0][15] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+30);
  /* #242: @1 = @0[36:39] */
  wr01 = wr00+36;
  /* #243: output[0][16] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+33);
  /* #244: @1 = @33[4:7] */
  wr01 = wr33+4;
  /* #245: output[0][17] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+36);
  /* #246: @19 = @0[40] */
  w19 = wr00[40];
  /* #247: output[0][18] = @19 */
  if (res[0]) res[0][39] = w19;
  /* #248: @19 = @33[7] */
  w19 = wr33[7];
  /* #249: output[0][19] = @19 */
  if (res[0]) res[0][40] = w19;
  /* #250: @19 = @0[45] */
  w19 = wr00[45];
  /* #251: @28 = @0[43] */
  w28 = wr00[43];
  /* #252: @14 = (@19*@28) */
  w14  = (w19*w28);
  /* #253: @17 = @0[46] */
  w17 = wr00[46];
  /* #254: @2 = @0[42] */
  w02 = wr00[42];
  /* #255: @15 = (@17*@2) */
  w15  = (w17*w02);
  /* #256: @14 = (@14-@15) */
  w14 -= w15;
  /* #257: output[0][20] = @14 */
  if (res[0]) res[0][41] = w14;
  /* #258: @14 = @0[41] */
  w14 = wr00[41];
  /* #259: @17 = (@17*@14) */
  w17 *= w14;
  /* #260: @15 = @0[44] */
  w15 = wr00[44];
  /* #261: @28 = (@15*@28) */
  w28  = (w15*w28);
  /* #262: @17 = (@17-@28) */
  w17 -= w28;
  /* #263: output[0][21] = @17 */
  if (res[0]) res[0][42] = w17;
  /* #264: @15 = (@15*@2) */
  w15 *= w02;
  /* #265: @19 = (@19*@14) */
  w19 *= w14;
  /* #266: @15 = (@15-@19) */
  w15 -= w19;
  /* #267: output[0][22] = @15 */
  if (res[0]) res[0][43] = w15;
  /* #268: @1 = @0[47:50] */
  wr01 = wr00+47;
  /* #269: output[0][23] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+44);
  /* #270: @1 = @0[50:53] */
  wr01 = wr00+50;
  /* #271: output[0][24] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+47);
  /* #272: @1 = @33[8:11] */
  wr01 = wr33+8;
  /* #273: output[0][25] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+50);
  /* #274: @15 = @0[54] */
  w15 = wr00[54];
  /* #275: output[0][26] = @15 */
  if (res[0]) res[0][53] = w15;
  /* #276: @15 = @33[11] */
  w15 = wr33[11];
  /* #277: output[0][27] = @15 */
  if (res[0]) res[0][54] = w15;
  /* #278: @15 = @0[59] */
  w15 = wr00[59];
  /* #279: @19 = @0[57] */
  w19 = wr00[57];
  /* #280: @14 = (@15*@19) */
  w14  = (w15*w19);
  /* #281: @2 = @0[60] */
  w02 = wr00[60];
  /* #282: @17 = @0[56] */
  w17 = wr00[56];
  /* #283: @28 = (@2*@17) */
  w28  = (w02*w17);
  /* #284: @14 = (@14-@28) */
  w14 -= w28;
  /* #285: output[0][28] = @14 */
  if (res[0]) res[0][55] = w14;
  /* #286: @14 = @0[55] */
  w14 = wr00[55];
  /* #287: @2 = (@2*@14) */
  w02 *= w14;
  /* #288: @28 = @0[58] */
  w28 = wr00[58];
  /* #289: @19 = (@28*@19) */
  w19  = (w28*w19);
  /* #290: @2 = (@2-@19) */
  w02 -= w19;
  /* #291: output[0][29] = @2 */
  if (res[0]) res[0][56] = w02;
  /* #292: @28 = (@28*@17) */
  w28 *= w17;
  /* #293: @15 = (@15*@14) */
  w15 *= w14;
  /* #294: @28 = (@28-@15) */
  w28 -= w15;
  /* #295: output[0][30] = @28 */
  if (res[0]) res[0][57] = w28;
  /* #296: @1 = @0[61:64] */
  wr01 = wr00+61;
  /* #297: output[0][31] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+58);
  /* #298: @1 = @0[64:67] */
  wr01 = wr00+64;
  /* #299: output[0][32] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+61);
  /* #300: @1 = @33[12:15] */
  wr01 = wr33+12;
  /* #301: output[0][33] = @1 */
  if (res[0]) casadi_copy(wr01, 3, res[0]+64);
  /* #302: @28 = @0[68] */
  w28 = wr00[68];
  /* #303: output[0][34] = @28 */
  if (res[0]) res[0][67] = w28;
  /* #304: @28 = @33[15] */
  w28 = wr33[15];
  /* #305: output[0][35] = @28 */
  if (res[0]) res[0][68] = w28;
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_4_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int load_cable_4_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_4_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void load_cable_4_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int load_cable_4_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void load_cable_4_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void load_cable_4_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void load_cable_4_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int load_cable_4_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int load_cable_4_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real load_cable_4_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* load_cable_4_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* load_cable_4_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* load_cable_4_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* load_cable_4_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int load_cable_4_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 155;
  return 0;
}

CASADI_SYMBOL_EXPORT int load_cable_4_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 155*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
