#!/usr/bin/env python3
"""
tools/thesis_figures.py — regenerate every thesis figure, in one command (§9.4)

    ./tools/thesis_figures.py                 # regenerate all of them
    ./tools/thesis_figures.py --check         # verify provenance only, draw nothing
    ./tools/thesis_figures.py F_attach_elevation_45_v_65

Figures are declared in `configs/thesis_figures.yaml` and written to `docs/figures/`,
so a late data fix propagates everywhere instead of leaving a stale PNG in the
document. Alongside them it writes `docs/figures/PROVENANCE.md`: for every figure, the
run ids behind it, each run's git SHA and whether its tree was dirty, and whether the
data is ARCHIVED or still only in the mutable results/ tree.

That last column is the point of the file. §4.3 makes `results_archive/` the only
copy of anything that is backed up off this machine, so a figure built from `results/`
is a figure whose data one `rm -rf` removes for good. It is regenerated, not refused --
one works from live data long before promoting it -- but it is called out every time.
"""
import argparse
import os
import shutil
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import metrics as M                                    # noqa: E402
from compare_runs import compare, expand               # noqa: E402
from plot_run import plot_run                          # noqa: E402
from run_dir import resolve                            # noqa: E402

REGISTRY = os.path.join(REPO, 'configs', 'thesis_figures.yaml')
ARCHIVE = os.path.join(REPO, 'results_archive')


def load_registry(path=REGISTRY):
    with open(path) as fh:
        reg = yaml.safe_load(fh) or {}
    figs = reg.get('figures') or []
    for f in figs:
        if not f.get('id') or f.get('kind') not in ('run', 'compare'):
            raise SystemExit(f'bad figure entry (needs id and kind run|compare): {f}')
    return reg.get('output', 'docs/figures'), figs


def provenance(spec):
    """(run_dir, {run_id, git_sha, dirty, archived}) for one run spec."""
    path = resolve(spec)
    mf = M.load_run(path)['manifest']
    return path, {
        'spec': spec,
        'run_id': mf.get('run_id', os.path.basename(path)[:5]),
        'git_sha': (mf.get('git_sha') or '')[:8],
        'dirty': mf.get('dirty_files', '?'),
        'archived': os.path.abspath(path).startswith(os.path.abspath(ARCHIVE)),
    }


def build(fig, out_root, check=False):
    """Regenerate one figure. Returns its provenance records."""
    specs = expand(fig.get('runs') or [])
    if not specs:
        raise SystemExit(f'{fig["id"]}: no runs listed')
    records = []
    paths = []
    for s in specs:
        p, rec = provenance(s)
        paths.append(p)
        records.append(rec)
    out_dir = os.path.join(out_root, fig['id'])
    if check:
        return records

    os.makedirs(out_dir, exist_ok=True)
    if fig['kind'] == 'compare':
        compare(specs, out_dir=out_dir, labels=fig.get('labels'),
                align=fig.get('align', 'auto'), quiet=True)
    else:
        # Draw into the figure's own directory rather than the run's plots/, so
        # regenerating a thesis figure never rewrites a run's recorded output.
        for p in paths:
            written = plot_run(p, out_dir=out_dir, quiet=True)
            keep = fig.get('keep')
            if keep:
                for w in written:
                    if os.path.splitext(os.path.basename(w))[0] not in keep:
                        os.remove(w)
    return records


def write_provenance(out_root, entries):
    path = os.path.join(out_root, 'PROVENANCE.md')
    lines = ['# Thesis figure provenance',
             '',
             'Regenerated by `tools/thesis_figures.py` from '
             '`configs/thesis_figures.yaml`.',
             'ARCHIVED = the data lives in `results_archive/` and is pushed off this '
             'machine; results/ = single copy, not backed up (§4.3).',
             '']
    for fig, records in entries:
        lines += [f'## {fig["id"]}', '']
        cap = (fig.get('caption') or '').strip()
        if cap:
            lines += [cap, '']
        lines += ['| run | git SHA | dirty files | data |',
                  '|---|---|---|---|']
        for r in records:
            where = 'ARCHIVED' if r['archived'] else '**results/ only**'
            lines.append(f'| {r["run_id"]} | `{r["git_sha"]}` | {r["dirty"]} | '
                         f'{where} |')
        lines.append('')
    with open(path, 'w') as fh:
        fh.write('\n'.join(lines) + '\n')
    return path


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('figure', nargs='*', help='figure ids (default: all)')
    ap.add_argument('--registry', default=REGISTRY)
    ap.add_argument('--out', help='output root (default: the registry\'s `output`)')
    ap.add_argument('--check', action='store_true',
                    help='resolve every run and report provenance; draw nothing')
    ap.add_argument('--clean', action='store_true',
                    help='delete the output root first, so a figure removed from the '
                         'registry cannot survive as a stale file')
    args = ap.parse_args()

    out_rel, figs = load_registry(args.registry)
    out_root = args.out or os.path.join(REPO, out_rel)
    if args.figure:
        wanted = set(args.figure)
        figs = [f for f in figs if f['id'] in wanted]
        missing = wanted - {f['id'] for f in figs}
        if missing:
            raise SystemExit(f'no such figure(s): {", ".join(sorted(missing))}')
    if not figs:
        raise SystemExit('the registry declares no figures')
    if args.clean and not args.check and os.path.isdir(out_root):
        shutil.rmtree(out_root)
    os.makedirs(out_root, exist_ok=True)

    entries, unarchived = [], 0
    for fig in figs:
        records = build(fig, out_root, check=args.check)
        entries.append((fig, records))
        n_arch = sum(1 for r in records if r['archived'])
        unarchived += len(records) - n_arch
        print(f'  [{"check" if args.check else "drew "}] {fig["id"]:34s} '
              f'{len(records)} run(s), {n_arch} archived')

    if not args.check:
        print(f'\n  -> {out_root}')
        print(f'  -> {write_provenance(out_root, entries)}')
    if unarchived:
        print(f'\n  !! {unarchived} run(s) behind these figures are NOT in '
              f'results_archive/ — that data is a single local copy (§4.3).')
        print('     Promote them before the figures are cited:')
        print('       tools/archive_run.sh <run_dir> "<reason>"')
    return 0


if __name__ == '__main__':
    sys.exit(main())
