"""ROS-independent M2B mission policy helpers.

``online_join_planner`` remains the authoritative mission executive.  This module
contains only M2B-specific policy, geometry and timers so the shared planner and
reference framework can be reused by this and future missions.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
import math
from typing import Optional

import numpy as np

from .mission_types import MissionPhase


# B1 phases whose references are generated by the M2B local-policy builder in
# online_join_planner.  Keep this classification in one ROS-independent place so
# shared reference generation and shared status reporting cannot disagree about
# whether a legacy RateProfile exists for a phase.
M2B_B1_LOCAL_REFERENCE_PHASES = frozenset({
    MissionPhase.M2_SETTLE_CAPTURE,
    MissionPhase.M2_ATTACH_APPROACH_HIGH,
    MissionPhase.M2_ATTACH_APPROACH_LOW,
    MissionPhase.M2_ATTACH_CAPTURE_WAIT,
    MissionPhase.M2_ATTACH_PROOF,
    MissionPhase.M2_ATTACHED_HOLD,
    MissionPhase.M2_DETACHED_RETREAT,
    MissionPhase.M2_LANDING_STAGE,
    MissionPhase.M2_FAULT,
})


def is_m2b_b1_local_reference_phase(phase: MissionPhase) -> bool:
    """Return whether B1 owns reference generation for ``phase`` locally."""

    return phase in M2B_B1_LOCAL_REFERENCE_PHASES


class BootstrapStatus(str, Enum):
    DETACHING = "DETACHING"
    SETTLING = "SETTLING"
    ARMABLE = "ARMABLE"
    FAULT = "FAULT"


@dataclass(frozen=True)
class M2BConfig:
    bootstrap_detach_dwell_s: float = 0.15
    bootstrap_settle_s: float = 0.50
    bootstrap_timeout_s: float = 3.0
    high_low_split_m: float = 0.08
    high_xy_tolerance_m: float = 0.05
    low_xy_tolerance_m: float = 0.025
    gross_xy_abort_m: float = 0.10
    alignment_pause_timeout_s: float = 2.0
    descent_speed_mps: float = 0.04
    contact_height_target_m: float = 0.0
    magnet_enable_height_m: float = 0.04
    magnet_enable_relative_speed_mps: float = 0.12
    capture_hold_normal_m: float = 0.020
    physical_latch_timeout_s: float = 0.75
    # After Gazebo reports a physical latch, freeze the pre-proof reference and
    # require a short measured stability dwell.  These are commissioning bounds,
    # not IRL magnetic-contact constants; all remain parameters at the mission
    # boundary so the real attachment experiment can retune them independently.
    latch_settle_dwell_s: float = 0.50
    latch_settle_timeout_s: float = 1.50
    latch_settle_speed_mps: float = 0.08
    latch_settle_accel_mps2: float = 2.0
    latch_abort_speed_mps: float = 0.50
    latch_abort_accel_mps2: float = 8.0
    latch_abort_displacement_m: float = 0.05
    capture_height_m: float = 0.30
    settle_position_tolerance_m: float = 0.05
    settle_speed_mps: float = 0.03
    settle_swing_deg: float = 3.0
    settle_dwell_s: float = 0.75
    evidence_timeout_s: float = 0.35
    approach_evidence_loss_abort_s: float = 0.75
    proof_timeout_s: float = 2.0
    attached_loss_grace_s: float = 0.50
    detach_verify_timeout_s: float = 1.50
    retreat_rise_m: float = 0.20
    # Proof motion is explicitly independent of the attached-hold tether angle.
    # Simulation defaults to a radial pull, which is compatible with the rigid
    # fixed-length tether.  The vector remains a mission parameter so IRL can
    # retune direction without changing state-machine semantics.
    proof_direction_plate_xyz: tuple[float, float, float] = (1.0, 0.0, 0.0)
    attached_hold_angle_deg: float = 15.0
    proof_command_m: float = 0.025
    proof_speed_mps: float = 0.03
    proof_min_measured_excitation_m: float = 0.012
    max_attempts: int = 3

    def __post_init__(self) -> None:
        nonnegative = (
            "bootstrap_detach_dwell_s",
            "bootstrap_settle_s",
            "high_low_split_m",
            "high_xy_tolerance_m",
            "low_xy_tolerance_m",
            "gross_xy_abort_m",
            "alignment_pause_timeout_s",
            "contact_height_target_m",
            "magnet_enable_height_m",
            "magnet_enable_relative_speed_mps",
            "capture_hold_normal_m",
            "physical_latch_timeout_s",
            "latch_settle_dwell_s",
            "latch_settle_timeout_s",
            "latch_settle_speed_mps",
            "latch_settle_accel_mps2",
            "latch_abort_speed_mps",
            "latch_abort_accel_mps2",
            "latch_abort_displacement_m",
            "capture_height_m",
            "settle_dwell_s",
            "evidence_timeout_s",
            "approach_evidence_loss_abort_s",
            "proof_timeout_s",
            "attached_loss_grace_s",
            "detach_verify_timeout_s",
            "retreat_rise_m",
            "proof_command_m",
            "proof_min_measured_excitation_m",
        )
        positive = (
            "bootstrap_timeout_s", "descent_speed_mps", "proof_speed_mps",
            "settle_position_tolerance_m", "settle_speed_mps", "settle_swing_deg",
        )
        for name in nonnegative:
            value = float(getattr(self, name))
            if not math.isfinite(value) or value < 0.0:
                raise ValueError(f"{name} must be finite and non-negative")
            object.__setattr__(self, name, value)
        for name in positive:
            value = float(getattr(self, name))
            if not math.isfinite(value) or value <= 0.0:
                raise ValueError(f"{name} must be finite and positive")
            object.__setattr__(self, name, value)
        proof_direction = np.asarray(self.proof_direction_plate_xyz, dtype=float).reshape(3)
        if not np.all(np.isfinite(proof_direction)):
            raise ValueError("proof_direction_plate_xyz must be a finite 3-vector")
        proof_norm = float(np.linalg.norm(proof_direction))
        if proof_norm <= 1e-12:
            raise ValueError("proof_direction_plate_xyz must be non-zero")
        proof_direction = proof_direction / proof_norm
        object.__setattr__(self, "proof_direction_plate_xyz", tuple(float(v) for v in proof_direction))

        hold_angle = float(self.attached_hold_angle_deg)
        if not math.isfinite(hold_angle) or not 0.0 < hold_angle < 90.0:
            raise ValueError("attached_hold_angle_deg must lie strictly between 0 and 90 degrees")
        object.__setattr__(self, "attached_hold_angle_deg", hold_angle)
        if self.latch_settle_timeout_s < self.latch_settle_dwell_s:
            raise ValueError("latch_settle_timeout_s must be >= latch_settle_dwell_s")
        if self.latch_abort_speed_mps <= self.latch_settle_speed_mps:
            raise ValueError("latch_abort_speed_mps must exceed latch_settle_speed_mps")
        if self.latch_abort_accel_mps2 <= self.latch_settle_accel_mps2:
            raise ValueError("latch_abort_accel_mps2 must exceed latch_settle_accel_mps2")
        if self.latch_abort_displacement_m <= 0.0:
            raise ValueError("latch_abort_displacement_m must be positive")
        if self.low_xy_tolerance_m >= self.high_xy_tolerance_m:
            raise ValueError("low_xy_tolerance_m must be strictly smaller than high_xy_tolerance_m")
        if self.gross_xy_abort_m <= self.high_xy_tolerance_m:
            raise ValueError("gross_xy_abort_m must exceed high_xy_tolerance_m")
        if self.proof_min_measured_excitation_m > self.proof_command_m:
            raise ValueError("proof_min_measured_excitation_m cannot exceed proof_command_m")
        attempts = int(self.max_attempts)
        if attempts < 1:
            raise ValueError("max_attempts must be at least one")
        object.__setattr__(self, "max_attempts", attempts)


@dataclass(frozen=True)
class BootstrapDecision:
    status: BootstrapStatus
    request_raw_detach: bool
    arm_permitted: bool
    reason: str


class M2BBootstrapGate:
    """Tracks the one exceptional pre-arm use of raw Gazebo joint truth."""

    def __init__(
        self,
        config: M2BConfig,
        *,
        start_time_s: float,
        release_required: bool = False,
    ) -> None:
        self.config = config
        self.release_required = bool(release_required)
        self.start_time_s = float(start_time_s)
        self.released = not self.release_required
        self.detached_since_s: Optional[float] = None
        self.settle_since_s: Optional[float] = None
        self.faulted = False

    def reset(self, *, start_time_s: float) -> None:
        self.start_time_s = float(start_time_s)
        self.released = not self.release_required
        self.detached_since_s = None
        self.settle_since_s = None
        self.faulted = False

    def release(self, *, now_s: float) -> None:
        """Open the supervised B1 detach gate and start its timeout clock.

        Before release, no raw detach command is permitted and the bootstrap
        timeout is intentionally suspended so the runner can verify the measured
        attached ground geometry while Gazebo remains paused.
        """
        if self.faulted or self.released:
            return
        self.released = True
        self.start_time_s = float(now_s)
        self.detached_since_s = None
        self.settle_since_s = None

    def step(
        self,
        now_s: float,
        *,
        joint_truth_fresh: bool,
        joint_detached: bool,
    ) -> BootstrapDecision:
        now = float(now_s)
        if self.faulted:
            return BootstrapDecision(BootstrapStatus.FAULT, False, False, "bootstrap fault latched")
        if self.release_required and not self.released:
            self.detached_since_s = None
            self.settle_since_s = None
            return BootstrapDecision(
                BootstrapStatus.DETACHING,
                False,
                False,
                "waiting for supervised bootstrap release",
            )
        if now - self.start_time_s > self.config.bootstrap_timeout_s:
            self.faulted = True
            return BootstrapDecision(
                BootstrapStatus.FAULT,
                False,
                False,
                "raw Gazebo detach was not verified before bootstrap timeout",
            )

        if not joint_truth_fresh or not joint_detached:
            self.detached_since_s = None
            self.settle_since_s = None
            reason = "waiting for fresh raw detached truth" if joint_truth_fresh else "raw joint truth unavailable/stale"
            if joint_truth_fresh and not joint_detached:
                reason = "raw joint truth still reports attached"
            return BootstrapDecision(BootstrapStatus.DETACHING, True, False, reason)

        if self.detached_since_s is None:
            self.detached_since_s = now
        detached_dwell = max(0.0, now - self.detached_since_s)
        if detached_dwell < self.config.bootstrap_detach_dwell_s:
            return BootstrapDecision(
                BootstrapStatus.DETACHING,
                True,
                False,
                f"detached truth dwell {detached_dwell:.3f}s",
            )

        if self.settle_since_s is None:
            self.settle_since_s = now
        settle_dwell = max(0.0, now - self.settle_since_s)
        if settle_dwell < self.config.bootstrap_settle_s:
            return BootstrapDecision(
                BootstrapStatus.SETTLING,
                False,
                False,
                f"post-detach ground settle {settle_dwell:.3f}s",
            )

        return BootstrapDecision(
            BootstrapStatus.ARMABLE,
            False,
            True,
            "fresh detached truth and post-detach settle complete",
        )


@dataclass(frozen=True)
class SettleDecision:
    settled: bool
    dwell_s: float
    reason: str


@dataclass(frozen=True)
class TakeoffClearanceDecision:
    ready: bool
    timed_out: bool
    rise_m: float
    reason: str


def evaluate_takeoff_magnet_clearance(
    *,
    enabled: bool,
    start_tip_z_m: Optional[float],
    current_tip_z_m: Optional[float],
    inputs_fresh: bool,
    minimum_rise_m: float,
    hover_elapsed_s: float,
    timeout_s: float,
) -> TakeoffClearanceDecision:
    """Require fresh measured magnet rise before post-takeoff settling."""

    if not enabled:
        return TakeoffClearanceDecision(True, False, float("nan"), "clearance gate disabled")

    elapsed = max(0.0, float(hover_elapsed_s))
    timeout = max(0.0, float(timeout_s))
    timed_out = bool(timeout > 0.0 and elapsed >= timeout)
    if not inputs_fresh or start_tip_z_m is None or current_tip_z_m is None:
        return TakeoffClearanceDecision(
            False,
            timed_out,
            float("nan"),
            "magnet-tip evidence unavailable/stale",
        )

    start = float(start_tip_z_m)
    current = float(current_tip_z_m)
    minimum = max(0.0, float(minimum_rise_m))
    if not all(math.isfinite(value) for value in (start, current, minimum, elapsed, timeout)):
        return TakeoffClearanceDecision(
            False,
            timed_out,
            float("nan"),
            "non-finite magnet-tip clearance evidence",
        )

    rise = current - start
    ready = bool(rise + 1e-9 >= minimum)
    return TakeoffClearanceDecision(
        ready,
        False if ready else timed_out,
        rise,
        "measured magnet ground clearance verified"
        if ready
        else "magnet has not cleared ground datum",
    )


class M2BSettleGate:
    """Continuous measured-state settle gate used before B1 local motion.

    A stale sample or any limit violation resets the dwell.  This makes the gate
    explicitly reject the large post-takeoff transient observed during B0 and
    avoids advancing the mission because a fixed timer happened to expire.
    """

    def __init__(self, config: M2BConfig) -> None:
        self.config = config
        self.good_since_s: Optional[float] = None

    def reset(self) -> None:
        self.good_since_s = None

    def step(
        self,
        *,
        now_s: float,
        inputs_fresh: bool,
        position_error_m: float,
        speed_mps: float,
        swing_magnitude_rad: float,
    ) -> SettleDecision:
        now = float(now_s)
        pos = abs(float(position_error_m))
        speed = abs(float(speed_mps))
        swing = abs(float(swing_magnitude_rad))
        values = (now, pos, speed, swing)
        if not all(math.isfinite(v) for v in values):
            self.good_since_s = None
            return SettleDecision(False, 0.0, "non-finite settle evidence")
        if not inputs_fresh:
            self.good_since_s = None
            return SettleDecision(False, 0.0, "settle evidence unavailable/stale")

        swing_limit = math.radians(self.config.settle_swing_deg)
        good = bool(
            pos <= self.config.settle_position_tolerance_m
            and speed <= self.config.settle_speed_mps
            and swing <= swing_limit
        )
        if not good:
            self.good_since_s = None
            if pos > self.config.settle_position_tolerance_m:
                reason = "position not settled"
            elif speed > self.config.settle_speed_mps:
                reason = "vehicle speed not settled"
            else:
                reason = "pendulum swing not settled"
            return SettleDecision(False, 0.0, reason)

        if self.good_since_s is None:
            self.good_since_s = now
        dwell = max(0.0, now - self.good_since_s)
        return SettleDecision(
            dwell >= self.config.settle_dwell_s,
            dwell,
            "measured settle dwell complete" if dwell >= self.config.settle_dwell_s else "measured settle dwell accumulating",
        )



class LatchStabilityStatus(str, Enum):
    SETTLING = "SETTLING"
    STABLE = "STABLE"
    FAILED = "FAILED"


@dataclass(frozen=True)
class LatchStabilityDecision:
    status: LatchStabilityStatus
    ready_for_proof: bool
    speed_mps: float
    acceleration_mps2: float
    displacement_m: float
    stable_dwell_s: float
    reason: str


class M2BLatchStabilityGate:
    """Measured post-latch gate before any proof reference is allowed to move.

    The gate separates a *settling* envelope from hard abort bounds.  Moderate
    latch transients reset the continuous stable dwell; a violent speed,
    acceleration or displacement jump fails the attempt immediately.  This
    specifically contains the Sep-10 Gazebo weld runaway while remaining
    parameterized for later IRL commissioning.
    """

    def __init__(
        self,
        config: M2BConfig,
        *,
        start_time_s: float,
        start_position_world,
        start_velocity_world,
    ) -> None:
        self.config = config
        self.reset(
            start_time_s=start_time_s,
            start_position_world=start_position_world,
            start_velocity_world=start_velocity_world,
        )

    def reset(
        self,
        *,
        start_time_s: float,
        start_position_world,
        start_velocity_world,
    ) -> None:
        self.start_time_s = float(start_time_s)
        self.start_position_world = np.asarray(start_position_world, dtype=float).reshape(3).copy()
        self.last_velocity_world = np.asarray(start_velocity_world, dtype=float).reshape(3).copy()
        self.last_time_s = float(start_time_s)
        if not (
            math.isfinite(self.start_time_s)
            and np.all(np.isfinite(self.start_position_world))
            and np.all(np.isfinite(self.last_velocity_world))
        ):
            raise ValueError("latch stability initial state must be finite")
        self.stable_since_s: Optional[float] = None
        self.ever_ready = False
        self.failed = False
        self.failure_reason = ""

    def step(self, now_s: float, *, position_world, velocity_world) -> LatchStabilityDecision:
        now = float(now_s)
        position = np.asarray(position_world, dtype=float).reshape(3)
        velocity = np.asarray(velocity_world, dtype=float).reshape(3)
        if self.failed:
            return LatchStabilityDecision(
                LatchStabilityStatus.FAILED, False, math.inf, math.inf, math.inf, 0.0,
                self.failure_reason or "latch stability fault latched",
            )
        if not (math.isfinite(now) and np.all(np.isfinite(position)) and np.all(np.isfinite(velocity))):
            self.failed = True
            self.failure_reason = "non-finite post-latch state"
            return LatchStabilityDecision(
                LatchStabilityStatus.FAILED, False, math.inf, math.inf, math.inf, 0.0,
                self.failure_reason,
            )

        speed = float(np.linalg.norm(velocity))
        displacement = float(np.linalg.norm(position - self.start_position_world))
        dt = now - self.last_time_s
        if dt < -1e-9:
            self.failed = True
            self.failure_reason = "post-latch time moved backwards"
            return LatchStabilityDecision(
                LatchStabilityStatus.FAILED, False, speed, math.inf, displacement, 0.0,
                self.failure_reason,
            )
        acceleration = 0.0
        if dt > 1e-6:
            acceleration = float(np.linalg.norm(velocity - self.last_velocity_world) / dt)
        self.last_time_s = now
        self.last_velocity_world = velocity.copy()

        hard_failure = None
        if speed > self.config.latch_abort_speed_mps:
            hard_failure = f"post-latch speed {speed:.3f} m/s exceeded abort bound"
        elif acceleration > self.config.latch_abort_accel_mps2:
            hard_failure = f"post-latch acceleration {acceleration:.3f} m/s^2 exceeded abort bound"
        elif displacement > self.config.latch_abort_displacement_m:
            hard_failure = f"post-latch displacement {displacement:.3f} m exceeded abort bound"
        elif (not self.ever_ready) and now - self.start_time_s > self.config.latch_settle_timeout_s:
            hard_failure = "post-latch stability timeout"

        if hard_failure is not None:
            self.failed = True
            self.failure_reason = hard_failure
            return LatchStabilityDecision(
                LatchStabilityStatus.FAILED, False, speed, acceleration, displacement, 0.0,
                hard_failure,
            )

        stable_now = bool(
            speed <= self.config.latch_settle_speed_mps
            and acceleration <= self.config.latch_settle_accel_mps2
        )
        if not stable_now:
            self.stable_since_s = None
            reason = "post-latch dynamics still settling"
            return LatchStabilityDecision(
                LatchStabilityStatus.SETTLING, False, speed, acceleration, displacement, 0.0,
                reason,
            )

        if self.stable_since_s is None:
            self.stable_since_s = now
        dwell = max(0.0, now - self.stable_since_s)
        ready = dwell >= self.config.latch_settle_dwell_s
        if ready:
            self.ever_ready = True
        return LatchStabilityDecision(
            LatchStabilityStatus.STABLE if ready else LatchStabilityStatus.SETTLING,
            ready,
            speed,
            acceleration,
            displacement,
            dwell,
            "post-latch measured stability dwell complete" if ready else "post-latch stable dwell accumulating",
        )


@dataclass(frozen=True)
class EvidenceFreshnessDecision:
    failed: bool
    bad_duration_s: float


class M2BEvidenceFreshnessGate:
    """Bound continuous loss of attachment evidence during approach.

    The approach holds position and keeps the magnet off while evidence is stale.
    A short dropout is tolerated; a sustained dropout ends the attempt rather
    than leaving the vehicle indefinitely suspended with ambiguous authority.
    """

    def __init__(self, config: M2BConfig) -> None:
        self.config = config
        self.bad_since_s: Optional[float] = None

    def reset(self) -> None:
        self.bad_since_s = None

    def step(self, *, now_s: float, fresh: bool) -> EvidenceFreshnessDecision:
        now = float(now_s)
        if not math.isfinite(now):
            self.bad_since_s = None
            return EvidenceFreshnessDecision(True, 0.0)
        if fresh:
            self.bad_since_s = None
            return EvidenceFreshnessDecision(False, 0.0)
        if self.bad_since_s is None:
            self.bad_since_s = now
        bad_duration = max(0.0, now - self.bad_since_s)
        return EvidenceFreshnessDecision(
            bad_duration >= self.config.approach_evidence_loss_abort_s,
            bad_duration,
        )

@dataclass(frozen=True)
class DescentDecision:
    band: str
    target_contact_height_m: float
    paused_for_xy: bool
    failed: bool
    reason: str


class M2BDescentProgress:
    """Stateful two-band contact-height progress with XY-conditioned Z freeze."""

    def __init__(self, config: M2BConfig, *, initial_contact_height_m: float) -> None:
        self.config = config
        self.target_contact_height_m = float(initial_contact_height_m)
        self.pause_started_s: Optional[float] = None

    def reset(self, initial_contact_height_m: float) -> None:
        self.target_contact_height_m = float(initial_contact_height_m)
        self.pause_started_s = None

    def _band_and_tolerance(self) -> tuple[str, float]:
        if self.target_contact_height_m > self.config.high_low_split_m:
            return "HIGH", self.config.high_xy_tolerance_m
        return "LOW", self.config.low_xy_tolerance_m

    def step(self, *, now_s: float, measured_xy_error_m: float, dt_s: float) -> DescentDecision:
        now = float(now_s)
        xy = abs(float(measured_xy_error_m))
        dt = max(0.0, float(dt_s))
        band, tolerance = self._band_and_tolerance()

        if not math.isfinite(xy):
            return DescentDecision(band, self.target_contact_height_m, True, True, "non-finite XY error")
        if xy >= self.config.gross_xy_abort_m:
            return DescentDecision(band, self.target_contact_height_m, True, True, "gross XY alignment error")

        if xy > tolerance:
            if self.pause_started_s is None:
                self.pause_started_s = now
            pause_duration = max(0.0, now - self.pause_started_s)
            failed = pause_duration >= self.config.alignment_pause_timeout_s
            return DescentDecision(
                band,
                self.target_contact_height_m,
                True,
                failed,
                "persistent XY alignment error" if failed else "Z frozen while XY catches up",
            )

        self.pause_started_s = None
        self.target_contact_height_m = max(
            self.config.contact_height_target_m,
            self.target_contact_height_m - self.config.descent_speed_mps * dt,
        )
        band, _ = self._band_and_tolerance()
        return DescentDecision(band, self.target_contact_height_m, False, False, "descent advancing")


@dataclass(frozen=True)
class RetryDecision:
    retry_allowed: bool
    terminal_failure: bool
    assigned_plate_id: int
    attempt_number: int


class M2BRetryTracker:
    def __init__(self, *, assigned_plate_id: int, max_attempts: int = 3) -> None:
        self.assigned_plate_id = int(assigned_plate_id)
        self.max_attempts = int(max_attempts)
        if self.assigned_plate_id < 0:
            raise ValueError("assigned_plate_id must be non-negative")
        if self.max_attempts < 1:
            raise ValueError("max_attempts must be at least one")
        self.failures = 0

    @property
    def attempt_number(self) -> int:
        return min(self.failures + 1, self.max_attempts)

    def record_failure(self) -> RetryDecision:
        self.failures += 1
        terminal = self.failures >= self.max_attempts
        return RetryDecision(
            retry_allowed=not terminal,
            terminal_failure=terminal,
            assigned_plate_id=self.assigned_plate_id,
            attempt_number=self.max_attempts if terminal else self.failures + 1,
        )


def should_enable_magnet(
    config: M2BConfig,
    *,
    contact_height_m: float,
    xy_error_m: float,
    detector_fresh: bool,
    relative_speed_mps: float,
) -> bool:
    return bool(
        detector_fresh
        and abs(float(contact_height_m)) <= config.magnet_enable_height_m
        and abs(float(xy_error_m)) <= config.low_xy_tolerance_m
        and abs(float(relative_speed_mps)) <= config.magnet_enable_relative_speed_mps
    )



def should_enter_capture_wait(
    config: M2BConfig,
    *,
    contact_height_m: float,
    magnet_enabled: bool,
) -> bool:
    """Freeze descent once measured contact is inside the physical-capture band.

    This deliberately uses measured plate-normal geometry rather than requiring
    the commanded contact-height ramp to reach zero, so steady vertical tracking
    bias cannot drive the simulated magnet through the plate before latch dwell.
    """
    height = float(contact_height_m)
    return bool(
        magnet_enabled
        and math.isfinite(height)
        and abs(height) <= config.capture_hold_normal_m
    )

def proof_command_distance(config: M2BConfig, *, elapsed_s: float) -> float:
    return min(config.proof_command_m, max(0.0, float(elapsed_s)) * config.proof_speed_mps)


def proof_direction_plate(config: M2BConfig) -> np.ndarray:
    """Unit proof-pull direction expressed in the assigned plate frame."""
    return np.asarray(config.proof_direction_plate_xyz, dtype=float).copy()


def attached_hold_direction_plate(config: M2BConfig) -> np.ndarray:
    """Contact-to-vehicle tether direction for the post-proof attached hold."""
    angle = math.radians(config.attached_hold_angle_deg)
    return np.array([math.sin(angle), 0.0, math.cos(angle)], dtype=float)


def proof_success(
    config: M2BConfig,
    *,
    detector_confirmed: bool,
    detector_fresh: bool,
    physical_latched: bool,
    measured_excitation_m: float,
) -> bool:
    return bool(
        detector_fresh
        and physical_latched
        and detector_confirmed
        and float(measured_excitation_m) >= config.proof_min_measured_excitation_m
    )


def contact_capture_position(plate_position_world, *, capture_height_m: float) -> np.ndarray:
    plate = np.asarray(plate_position_world, dtype=float).reshape(3)
    if not np.all(np.isfinite(plate)):
        raise ValueError("plate_position_world must be finite")
    height = float(capture_height_m)
    if not math.isfinite(height) or height < 0.0:
        raise ValueError("capture_height_m must be finite and non-negative")
    return plate + np.array([0.0, 0.0, height], dtype=float)


def body_reference_from_contact(
    *,
    contact_position_world,
    direction_contact_to_vehicle_world,
    tether_length_m: float,
    rotation_world_from_body,
    tether_anchor_body,
) -> np.ndarray:
    contact = np.asarray(contact_position_world, dtype=float).reshape(3)
    direction = np.asarray(direction_contact_to_vehicle_world, dtype=float).reshape(3)
    rotation = np.asarray(rotation_world_from_body, dtype=float).reshape(3, 3)
    anchor = np.asarray(tether_anchor_body, dtype=float).reshape(3)
    if not all(np.all(np.isfinite(value)) for value in (contact, direction, rotation, anchor)):
        raise ValueError("contact/body geometry must be finite")
    norm = float(np.linalg.norm(direction))
    if norm <= 1e-12:
        raise ValueError("direction_contact_to_vehicle_world must be non-zero")
    length = float(tether_length_m)
    if not math.isfinite(length) or length <= 0.0:
        raise ValueError("tether_length_m must be finite and positive")
    direction = direction / norm
    anchor_world = contact + length * direction
    return anchor_world - rotation @ anchor


def yaw_quaternion_xyzw(yaw_rad: float) -> np.ndarray:
    yaw = float(yaw_rad)
    if not math.isfinite(yaw):
        raise ValueError("yaw_rad must be finite")
    return np.array([0.0, 0.0, math.sin(0.5 * yaw), math.cos(0.5 * yaw)], dtype=float)


def m2b_mpc_mode_for_phase(phase: MissionPhase) -> str:
    if phase == MissionPhase.M2_VERTICAL_TAKEOFF:
        return "VERTICAL_TAKEOFF"
    if phase in {MissionPhase.M2_ATTACH_APPROACH_HIGH, MissionPhase.M2_ATTACH_APPROACH_LOW, MissionPhase.M2_ATTACH_CAPTURE_WAIT}:
        return "ATTACH_APPROACH"
    if phase == MissionPhase.M2_ATTACH_PROOF:
        return "ATTACH_PROOF"
    if phase == MissionPhase.M2_ATTACHED_HOLD:
        return "ATTACHED_HOLD"
    if phase == MissionPhase.M2_DETACHED_RETREAT:
        return "DETACHED_RETREAT"
    if phase in {MissionPhase.LANDING, MissionPhase.M2_LANDING_STAGE}:
        return "LANDING"
    return "FREE_SWING"
